### ISSUE TITLE
Add SEO to all pages

### ISSUE THREAD

**Issue by akashgreninja** [OSCode-Community/OSCodeCommunitySite#10]

**Comment by akrati-max** [comment]
I would like to work on this issue under GSSOC-23.

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by akshathar-navada** [comment]
> I would like to work on this issue under GSSOC-23.

Yes sure, go ahead!! @akrati-max
