### ISSUE TITLE
Fixing the issue of Get started button linked to Contact Us Section

### ISSUE THREAD

**Issue by Akanksha-202** [OSCode-Community/OSCodeCommunitySite#100]
Redirecting the Get Started button to the Chapters section when now it is linked to the Contact Us element.
Please assign this issue to me under the GSSoC label.

**Comment by akshathar-navada** [comment]
We want the get started linked to contact section itself.
Thank you @Akanksha-202 , open a PR if there is any issue , we would be happy to merge it :)
