### ISSUE TITLE
[Feat]: Css is not applied correctly all the html skeleton is not consistent on the chapters web page

### ISSUE THREAD

**Issue by Shubham12365** [OSCode-Community/OSCodeCommunitySite#1004]
### What feature?
 Css is not applied correctly all the html skeleton is not consistent on the chapters web page 

Problem :
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/95515278/8a194e7b-18c5-41a6-adcf-1c478a941fa6)

### Show us the magic with screenshots

Magic :

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/95515278/aecc55ba-81a0-4264-ad3a-40716123a580)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Purnima3** [comment]
hey , I can solve this issue please assign me this issue under GSSOC '23.

**Comment by Shubham12365** [comment]
Okk Purnima , You can work on this . All the best
