### ISSUE TITLE
[Feat]: ADD WORKFLOW SCRIPT TO PREVENT MULTIPLE ISSUES 🔐

### ISSUE THREAD

**Issue by 0xabdulkhaliq** [OSCode-Community/OSCodeCommunitySite#1012]
### What feature?

- We want to add a workflow script regarding closing the issues.
-  This script will look into the contributor created issue and checks if he already created an issue, If an issue exists the new issue will be closed.
-  According the GSSoC Contributing guidelines, A contributor must want to finish one issue before creating another issue.
- But in this repository the contributors are spamming multiple issues, This is strictly against the contributing guidelines.
- After adding this script you don't want to state that `please create one issue at a time` for every contributor who creates more than one issue at a time. 
- This script will automate the process and closes the new one if already an existing one is found.

### Show us the magic with screenshots

| EXAMPLE SCREENSHOT OF CLOSING MY SECOND ISSUE BY WORKFLOW |
| :--: |
| ![image](https://github-production-user-asset-6210df.s3.amazonaws.com/92252895/252186153-cbb02c2e-3e29-4254-b000-b01362a4afbd.png) |

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @Divesh2003, @Vaishnavi-Patil2211, @akshathar-navada & @akashgreninja 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you.

**Comment by 0xabdulkhalid** [comment]
Hey @Killer2-O, there are so many number of people who doing the same contributions.

Contributors don't want to add the **same Projects for multiple repositories**, I here to contribute workflow.
There are people who do the same contribution to every repository they are making changes to codebases or adding new codebases.

The restrictions is only for **adding new Projects**

I don't know who are you and why are you tracking other's progress, if you really want to win then first focus on yourself. Don't waste your time.

Hope you understood.

**Comment by 0xabdulkhalid** [comment]
I contacted with Moderator, he told that this is not appreciated.

So I'm closing this issue.
