### ISSUE TITLE
Improve Ui of contact section

### ISSUE THREAD

**Issue by akanksha984** [OSCode-Community/OSCodeCommunitySite#1014]
### What feature?

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/a78fd034-6aac-4484-83bd-cc6fca4db184)

Improve the ui of the contact is section. Please assign it to me under gssoc'23. I want to work upon this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
@Vaishnavi-Patil2211 Please assign this to me

**Comment by akanksha984** [comment]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/684507fa-a54d-4631-9082-a6c6a96c3985)

@Vaishnavi-Patil2211 does it go well ?

**Comment by Vaishnavi-Patil2211** [comment]
Can you change all the logo same as Instagram logo

**Comment by Vaishnavi-Patil2211** [comment]
add a different gradient for all if possible

**Comment by akanksha984** [comment]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/284bbe16-0757-4e3a-b369-160c57cef0c3)
 
Does it go well @Vaishnavi-Patil2211 ?

**Comment by Vaishnavi-Patil2211** [comment]
Yes nice!! Keep going

**Comment by akanksha984** [comment]
So should I keep this gradient for all or different gradient styles for different blocks?

**Comment by Vaishnavi-Patil2211** [comment]
As per your preference

**Comment by akanksha984** [comment]
@Vaishnavi-Patil2211  okay I have different gradients which goes well.
Can you please review https://github.com/OSCode-Community/OSCodeCommunitySite/pull/1090 this pr so that I could create another for this change

**Comment by Vaishnavi-Patil2211** [comment]
Ok

**Comment by Vaishnavi-Patil2211** [comment]
Can you provide me the link to 1090 pr

**Comment by akanksha984** [comment]
https://github.com/OSCode-Community/OSCodeCommunitySite/pull/1090 This is the link @Vaishnavi-Patil2211

**Comment by akanksha984** [comment]
@Vaishnavi-Patil2211 I have created the pr for this issue: https://github.com/OSCode-Community/OSCodeCommunitySite/pull/1098. Check if this goes well?
