### ISSUE TITLE
Adding error 404 page

### ISSUE THREAD

**Issue by VC6378** [OSCode-Community/OSCodeCommunitySite#103]
Heyy,
I would like to add an error 404 page for the website.
Thanks and regards,
Vibhuti Chandrakar

**Comment by Amankumarharsh** [comment]
pls assign this issue to me sir as I yet not resolved any issue or assign me any issue related to front end as I'm a beginner and unable to find issues

**Comment by Saurabhrajput1234** [comment]
Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .
I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
I will try to make it as different as possible and exciting also.
Please assign it to me. Thank you in advance.

**Comment by akshathar-navada** [comment]
error 404 page is already added
Thank you for stepping up, if u have any other idea of enhancing our repo, open a PR and we would be merging it soon:)
