### ISSUE TITLE
[Docs]: Grammar and Spelling Errors in the README.md File

### ISSUE THREAD

**Issue by IfeoluwaAroboto** [OSCode-Community/OSCodeCommunitySite#1065]
### Current State

1. In the About Us section, the beginning of the third bullet point has a grammatical error. " We help students to get start with their lifelong journey of coding."
2. In the About Us section, the fourth bullet point has a grammatical error. "Overall students will enjoy with this collaborative journey of learning, practicing and sharing technical skills with our enthusiastic community!!"

### Desired State

1. In the About Us section, the third bullet point corrected sentence should be. " We help students to get started with their lifelong journey of coding."
2. In the About Us section, the fourth bullet point sentence should be. "Overall students will enjoy this collaborative journey of learning, practicing, and sharing technical skills with our enthusiastic community!!"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by abhisar-yadav** [comment]
Please assign this issue to me under GSSoC 2023!
