### ISSUE TITLE
Chapter page need ui improvement

### ISSUE THREAD

**Issue by RitiChandak** [OSCode-Community/OSCodeCommunitySite#1079]
### Description

chapter page needs improvement

### Expected Behavior

I remember that the chapter page used to have a different appearance, similar to what is shown in the screenshot

![254763677-b0bc2dbd-e880-4a23-a3a4-b9423d10e1e8](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96969496/b48b0eac-af25-4c63-a165-d87d15cb5f66)

### Show us the trouble with screenshots

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96969496/33452e36-eb17-45f9-b15e-4a050e60e7e4)

### Enter the version of your web browser

chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@Vaishnavi-Patil2211 please assign me this issue

**Comment by RitiChandak** [comment]
Hello @Vaishnavi-Patil2211, I noticed that the code contains repetitive changes that have resulted in duplicate ID. As a consequence, multiple images are overlapping, making it difficult for me to edit the page effectively. To resolve this issue, I have two options:

1. Create a new basic page from scratch and gradually improve it over time. This will allow me to have a clean slate without any overlapping elements.

2. Alternatively,We can revert the previous changes made to this page, so that the duplicate IDs and overlapping images are eliminated. Once the code is back to its original state, We can then proceed with the necessary edits and improvements.

Please let me know which option you prefer or if you have any other suggestions to address the issue.

**Comment by RitiChandak** [comment]
@RitiChandak

**Comment by Vaishnavi-Patil2211** [comment]
Ok so resolve this issue I will merge it

**Comment by RitiChandak** [comment]
okay so i am reverting the changes and raising the pr
