### ISSUE TITLE
Improving text typing animation 

### ISSUE THREAD

**Issue by YaShRaJ0P** [OSCode-Community/OSCodeCommunitySite#108]
Landing page's text typing animation makes upper text to move few pixels top which hides the text.
![Screenshot_2023-05-21-05-28-40-80](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121381832/a53862a8-f2ab-4ce6-bea6-4ef2f6c5d2e6)

**Comment by YaShRaJ0P** [comment]
I want to work on this issue. Please assign me.

**Comment by akshathar-navada** [comment]
Yes ,go ahead @YaShRaJ0P
