### ISSUE TITLE
[Bug]:  Misalignment

### ISSUE THREAD

**Issue by akanksha984** [OSCode-Community/OSCodeCommunitySite#1085]
### Description

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/1c3c127e-6e6b-4ef3-b680-d6d0bc1fee9a)

@Vaishnavi-Patil2211 Please assign this to me I want to work upon this issue

### Expected Behavior

-

### Show us the trouble with screenshots

-

### Enter the version of your web browser

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/4fa6ad84-0b35-4ae2-9467-629767eb1061)

@Vaishnavi-Patil2211 is it good to go ?

**Comment by Vaishnavi-Patil2211** [comment]
Yes

**Comment by akanksha984** [comment]
@Vaishnavi-Patil2211 please check this pr https://github.com/OSCode-Community/OSCodeCommunitySite/pull/1102 So that i could create a new pr for contact section

**Comment by akanksha984** [comment]
I created the pr for this : https://github.com/OSCode-Community/OSCodeCommunitySite/pull/1112
