### ISSUE TITLE
Improving 'Our Accomplishments' grid

### ISSUE THREAD

**Issue by YaShRaJ0P** [OSCode-Community/OSCodeCommunitySite#109]
The containers in 'Our Accomplishments' are not equally sized. 
![Screenshot_2023-05-21-05-29-00-59](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121381832/bb81fd10-573c-4105-86b7-0c932b09490d)
Please assign me this issue. I want to work on it.

**Comment by akshathar-navada** [comment]
Yes sure @YaShRaJ0P
