### ISSUE TITLE
Contact Form isn't validated

### ISSUE THREAD

**Issue by raghavawasthi24** [OSCode-Community/OSCodeCommunitySite#111]
What is the bug?
The contact form is accepting entries like
-blank Your Name
-blank subject
-invalid email
-blank message

How I will fix?
I will add validations through frontend which will accept only valid entries.

![Screenshot (101)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/113261155/d0cb7b3f-19bf-46cd-b52f-68692da29c89)

**Comment by akshathar-navada** [comment]
Yes sure @raghavawasthi24 , go ahead and resolve the issue

**Comment by raghavawasthi24** [comment]
Thanks for this opportunity. I will surely resove it.
