### ISSUE TITLE
[Bug]:  Add scale to the text on hover

### ISSUE THREAD

**Issue by akanksha984** [OSCode-Community/OSCodeCommunitySite#1111]
### Description

@Vaishnavi-Patil2211 Please assign me this. I want to improve its hover so that it looks highlighting
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/e1116a76-0e6b-4d76-a306-9a8901194a18)

### Expected Behavior

-

### Show us the trouble with screenshots

-

### Enter the version of your web browser

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/698780e3-f3c9-453e-81c1-18a574f75648)

@Vaishnavi-Patil2211 does it go well?

**Comment by Vaishnavi-Patil2211** [comment]
Yah

**Comment by akanksha984** [comment]
Please check this one : https://github.com/OSCode-Community/OSCodeCommunitySite/pull/1112  so that I could create pr for this issue @Vaishnavi-Patil2211

**Comment by akanksha984** [comment]
created the pr https://github.com/OSCode-Community/OSCodeCommunitySite/pull/1115 @Vaishnavi-Patil2211
