### ISSUE TITLE
Links to websites of sponsors and partners

### ISSUE THREAD

**Issue by AbhaBarge** [OSCode-Community/OSCodeCommunitySite#112]
As a GSSOC' 23 contributor, I would like to add links to the logos of sponsors and partners that can redirect the visitors and users to those websites. Also, on the blog page, I would like to add a button that would take the user to the website home page. Please assign this issue to me.

**Comment by Vanshitgupta9717** [comment]
i can do this . please assign me under GSSOC'23

**Comment by Rutujeet** [comment]
I kindly request your consideration in assigning Issue #112 to me. I am eager to take on this task and contribute to the project's success.

**Comment by akshathar-navada** [comment]
Hello buddies, as of know don't need to link them to the respected links. It is just to show that there are our partners. 
Thank you!
