### ISSUE TITLE
[Bug]: Font need to be changed

### ISSUE THREAD

**Issue by akanksha984** [OSCode-Community/OSCodeCommunitySite#1121]
### Description

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/1b2d8d54-b891-48f6-a69c-b10baf41c482)

Why chose us font does not match with the font of the page. I want to fix this. Please assign it to me @Vaishnavi-Patil2211 

### Expected Behavior

-

### Show us the trouble with screenshots

-

### Enter the version of your web browser

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Pragati-3003** [comment]
@Vaishnavi-Patil2211 ,I would like to work on this issue ,please assign this issue to me.

**Comment by akanksha984** [comment]
please check https://github.com/OSCode-Community/OSCodeCommunitySite/pull/1146 @Vaishnavi-Patil2211 so that I can create pr for this one. 
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/23c60849-11c0-450d-9cfc-a094b8a2ad2e)

**Comment by akanksha984** [comment]
@Vaishnavi-Patil2211 please check #1146

**Comment by akanksha984** [comment]
Done this @Vaishnavi-Patil2211 at pr #1184
