### ISSUE TITLE
Adding link on  Sponsors

### ISSUE THREAD

**Issue by shreya26-bit** [OSCode-Community/OSCodeCommunitySite#115]
To create hover links for sponsors that redirect to their respective websites. I want to do it, please assign it to me

**Comment by Aahad-1526** [comment]
i want to work on this issue for adding the link on sponsors

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by akshathar-navada** [comment]
Hello buddies, as of know don't need to link them to the respected links. It is just to show that there are our partners.
Thank you!
