### ISSUE TITLE
feat: Toggle button

### ISSUE THREAD

**Issue by SINJINI-G** [OSCode-Community/OSCodeCommunitySite#116]
Hello!!

I want to add a toggle button for switching light and dark theme. Can I work on this for gssoc?

@akshathar-navada

**Comment by Aditi323** [comment]
Can you please assign this to me as a GSSOC Contributor.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead !!! It would be a great contribution

**Comment by SINJINI-G** [comment]
Kindly review the PR @akshathar-navada
