### ISSUE TITLE
update: improve the search bar ui

### ISSUE THREAD

**Issue by SINJINI-G** [OSCode-Community/OSCodeCommunitySite#117]
Hi  @akshathar-navada !!

I want to improve the search bar ui.. may I work on this issue for  gssoc?

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by akshathar-navada** [comment]
Actually this improvement is done, if u want to add on any new features on it, please add required screenshot, we will review it first , then u can proceed
