### ISSUE TITLE
[Bug]: wrong title

### ISSUE THREAD

**Issue by khadar1020** [OSCode-Community/OSCodeCommunitySite#1171]
### Description

for gallery page we can change the title name events to gallery 

### Expected Behavior

we can change the title

### Show us the trouble with screenshots

![Screenshot (472)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/124120102/fdbbc05c-4897-4793-8a2c-0f17576ad94e)

### Which browsers are affected?

Chrome

### Which OS are affected?

Windows

### Enter the version of your web browser

Version 115.0.5790.102 (Official Build) (64-bit)

### Device?

Desktop

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by khadar1020** [comment]
please assign me this issue @Vaishnavi-Patil2211

**Comment by 0xabdulkhalid** [comment]
Hey there @khadar1020,

I have already created an Issue #1164 for this problem.

Please close your issue and pr, **because it duplicate**

Hope you understood, Thank you!

**Comment by 0xabdulkhalid** [comment]
Additionally you are not permitted to open a PR without even getting assigned to this ISSUE.

**Make sure to follow contributing guidelines**, otherwise you want face problems in future from GSSOC Team.
