### ISSUE TITLE
update in home,chapter and color scheme

### ISSUE THREAD

**Issue by devjaveriasohail** [OSCode-Community/OSCodeCommunitySite#118]
Hi there as a contributor in GSSoC,23 I want to update the hero section of the home page as too much text is there. The search bar on the chapter page needed CSS and the blue color of your logo and the rest of the website does not match. Please assign me this.

**Comment by Aditi323** [comment]
Can you please assign this to me as a GSSOC Contributor.

**Comment by akshathar-navada** [comment]
Yes sure, open a PR . We will review it and merge it soon:)

**Comment by Aditi323** [comment]
> Hi there as a contributor in GSSoC,23 I want to update the hero section of the home page as too much text is there. The search bar on the chapter page needed CSS and the blue color of your logo and the rest of the website does not match. Please assign me this.

Are you working on it or could we work together?

**Comment by devjaveriasohail** [comment]
yes,  I am working on it.
