### ISSUE TITLE
update: UI of event gallery

### ISSUE THREAD

**Issue by SINJINI-G** [OSCode-Community/OSCodeCommunitySite#121]
# Solution
- Improve cards UI for each event
- Horizontal positioning of cards
- Multiple event cards on a single line 

This will improve the UX and let the user know about multiple events with less scrolling. 

Can I work on this issue for gssoc? @akshathar-navada

**Comment by Eninini** [comment]
I would also like to work on this issue.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @SINJINI-G . We will be happy for your contibution!!

**Comment by akshathar-navada** [comment]
Event page enhancement is pinned in the issue section, so will be closing this isssue. If there is any improvements u guys would like to make , can discuss in the pinned issue.
Thank you!
