### ISSUE TITLE
Update navbar blur in every page

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#127]
I want to change navbar blur in all the pages. Assign me this issue , Thanks
## some page with blur
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/352ffa01-17ed-4fca-b8e7-0f5689ab8b69)
## some without
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/f9ca75a5-2340-4e15-aeb9-19fb0a539d6f)

**Comment by Git21221** [comment]
@akshathar-navada kindly look into this issue and assign me this

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Git21221

**Comment by Git21221** [comment]
Someone already changed :(
