### ISSUE TITLE
Unable to Sign In with Google - Firebase Fatal Error 🚨

### ISSUE THREAD

**Issue by Nishitbaria** [OSCode-Community/OSCodeCommunitySite#1283]
**Issue Description:**
I am facing an issue while trying to sign in with Google on our platform. When attempting to sign in using a Google account, the following error is encountered:

```
util.ts:154 Uncaught Error: FIREBASE FATAL ERROR: Cannot parse Firebase URL. Please use https://<YOUR FIREBASE>.firebaseio.com
    at se (util.ts:154:19)
    at Ys (parser.ts:80:7)
    at Xr (Database.ts:137:14)
    at O.instanceFactory (register.ts:37:40)
    at Provider.getOrInitializeService (provider.ts:318:33)
    at Provider.getImmediate (provider.ts:115:21)
    at io (Database.ts:324:11)
    at firebase.js:18:18
```

**Steps to Reproduce:**
1. Navigate to the sign-in page on our platform.
2. Click on the "Sign In with Google" button.
3. Observe the error mentioned above.

**Expected Behavior:**
Upon clicking the "Sign In with Google" button, users should be able to successfully authenticate and access our platform. The error mentioned above should not occur.

**Additional Information:**
- This issue seems to be related to Firebase, as indicated by the error message.
- The error points to a parsing problem with the Firebase URL, suggesting that it should use the format "https://<YOUR FIREBASE>.firebaseio.com".

**Comment by Nishitbaria** [comment]
Hey @Vaishnavi-Patil2211 Plese assign me this issue

**Comment by Nishitbaria** [comment]
@Vaishnavi-Patil2211 ,I have solved firebase  error ,but after login you are redirecting to / ,Do you want me to make a profile page for displaying logged in user

**Comment by Vaishnavi-Patil2211** [comment]
Yes
