### ISSUE TITLE
Adding Images and Transitions in College Chapter Section to Improve UI

### ISSUE THREAD

**Issue by jasleen1316** [OSCode-Community/OSCodeCommunitySite#129]
I would like to add some images, transitions and overall improve the UI of the college chapters section using card view/grid view

**Comment by akshathar-navada** [comment]
Yes sure @jasleen1316 , but make sure to add required screenshots in PR, so that we can review them easily.

**Comment by vaibhav-xt** [comment]
Hey, Can I work on this issue? I am really interested.

**Comment by tripathishipra** [comment]
Hi , I am contributor under GSSOC'23 and I am eager to showcase my skills and make a meaningful contribution to this project.
Kindly assign me this issue.@akshathar-navada

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @tripathishipra

**Comment by tripathishipra** [comment]
Thankyou

**Comment by tripathishipra** [comment]
Can you please reassign me this project.
Sorry I accidentally removed the assignment.

**Comment by akshathar-navada** [comment]
Improving the UI of College chapter page is open to all. Open a PR with required screenshots, we will review it soon!

**Comment by tripathishipra** [comment]
Can I work in this again ? you can reassign me. @akshathar-navada

**Comment by akshathar-navada** [comment]
This is open to all, u can go ahead and open a PR with required screenshots, we will review it soon!
