### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by anan262** [OSCode-Community/OSCodeCommunitySite#131]
I'm super excited and thrilled to contribute to this one as I have immense experience in the same.

**Comment by mvpfrever** [comment]
hello sir it will be my pleasure if i work on it and can create a highly attractive login page 
GSSOC'23

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. There is no login page. I can do the login page. I have all the skills required. 
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by anan262** [comment]
I'm a GSSOC contributor too and have authored the thread! It would be my deep interest to work on the same and  I hope I could contribute on the same

**Comment by akshathar-navada** [comment]
Hello buddies, as of now don't need to create login page. If there is any requirement , we will let u guys know. 
Thank you!
