### ISSUE TITLE
Event Section Card Ui Improvement

### ISSUE THREAD

**Issue by SubhamB2003** [OSCode-Community/OSCodeCommunitySite#134]
@akshathar-navada Hey, I want to change the event section card UI. The border radius and shadow effect is too much.
You can see the better one
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/94003231/123b21aa-e423-415f-ac52-ceb82ad4fb10)

Card Hover
![Screenshot (4)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/94003231/687207e8-f2c9-4179-b9e2-58212168b650)

And Sorry I forgot to add the blur effect on the event and chapters section.
I can add the blur effect now.
Here it is (Event Section)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/94003231/9f63f2e8-5d93-48bc-ac74-766d37096c4d)

Please assign it to me under GSSOC 23, So I can create a pull request.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @SubhamB2003

**Comment by SubhamB2003** [comment]
@akshathar-navada Hey, I create a new PR, please check.
