### ISSUE TITLE
Logos in Our Sponsors & Parteners section are distorted.

### ISSUE THREAD

**Issue by curiousyuvi** [OSCode-Community/OSCodeCommunitySite#135]
The logos in **Our Sponsors & Parteners** section appear distorted, I would like to fix their styling so that the logos appear without 
 any distortion for different dimensions of images.

![Screenshot from 2023-05-21 17-17-39](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/58589519/dd8cf945-1de5-4b31-9b28-7cebe835eb1b)

Please assign this issue to me :)

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. Logos in the Our Sponsors & Partners section are distorted. I can fix this issue. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by akshathar-navada** [comment]
Yes sure , go ahead !!

**Comment by curiousyuvi** [comment]
@akshathar-navada I have created PR please review it, thanks 🙂.
