### ISSUE TITLE
Bug: Embedded link in logo on events page throws 404

### ISSUE THREAD

**Issue by rayyan016** [OSCode-Community/OSCodeCommunitySite#136]
Hi. The embedded link within the logo on the navbar on the events page is incorrect. It throws a 404 not found. I would like to fix this issue. Could you assign it to me under GsSOC'23?
![oscode issue1](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/102043379/7ab2c6a6-e3b6-4844-9cc3-c6ec36b31da4)

**Comment by Urmilasc** [comment]
Hello , Could I work on this issue, please let me know under GSSoc'23

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @rayyan016
