### ISSUE TITLE
Change Image format to webp

### ISSUE THREAD

**Issue by Anshul02092003** [OSCode-Community/OSCodeCommunitySite#137]
Why should we change the image format from png to WebP? cause WebP typically achieves an average of 30% more compression than JPEG and JPEG 2000, without losing image quality (see [Comparative Study](https://developers.google.com/speed/webp/docs/c_study)). The WebP format aims to create smaller, better-looking images that can help **_make the web faster_**. 

Changing image format will lead to any destructivity?
-Absolutely Not, it won't affect the site in any wrong way.

How I would contribute to this?
-I will change the formats of all the images to WebP and then correct all the image paths

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @Anshul02092003 . We would be happy to merge it!!

**Comment by Anshul02092003** [comment]
Created new PR, it has new folder name **webp img** it has all images of site in webp format
