### ISSUE TITLE
[Bug]: Improper Alignmnet

### ISSUE THREAD

**Issue by akanksha984** [OSCode-Community/OSCodeCommunitySite#1391]
### Description

The footer section has been distorted , I want to fix this @Vaishnavi-Patil2211 please assign it to me

### Expected Behavior

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/9c6aefba-e269-4d27-83ac-0fe282900a7b)

### Show us the trouble with screenshots

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/b5102e19-b6f2-4fa6-93db-862626deede4)

### Enter the version of your web browser

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Nishitbaria** [comment]
Hey @akanksha984 I have Already Created This issue  :https://github.com/OSCode-Community/OSCodeCommunitySite/issues/1378
