### ISSUE TITLE
Contact from design and adding to website

### ISSUE THREAD

**Issue by Urmilasc** [OSCode-Community/OSCodeCommunitySite#140]
Hello OSCode Community mentor, can I work on above mentioned  issue/functional feature , please assign it to me under label of GSSoC

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I can work on this issue. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by akshathar-navada** [comment]
Hey @Urmilasc , pls go ahead
