### ISSUE TITLE
making sponsors ad partners section move automatically 

### ISSUE THREAD

**Issue by laibaahsan27** [OSCode-Community/OSCodeCommunitySite#141]
i can make the manual scroll, which is taking a lot of time, to an automatic scroll as it will be more efficient, the user could see all the sponsors quickly without having to click on next themselves . the sponsors and partners logo will keep on moving without the user having to do anything.
i will also increase the logo size as it is little difficult to read.

![1](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/123810454/12c1a9f0-499b-43a7-99e0-e6e0f4b9f5fe)

please asssign it to me under the label GSSOC 2023.

**Comment by laibaahsan27** [comment]
i will add the infinite scroll feature to this section 
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/123810454/cae28cf9-744e-49bf-a90c-f0b9759dff6f)

**Comment by akshathar-navada** [comment]
Hey @laibaahsan27 , thanks for stepping up. 
The current one we don't have to manually click , it is also automatic scrolling itself. We prefer this than the infinite scroll feature, as in this there is some hover effect. If there is any other enhancement in which u would like to work on , please go ahead.
Thank you!!
