### ISSUE TITLE
chapter page active hover

### ISSUE THREAD

**Issue by laibaahsan27** [OSCode-Community/OSCodeCommunitySite#143]
As you can see when we are on the chapter page the chapter button on the navbar should have an active hover, which is not there. let me add it.

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/123810454/cf7911a4-5e4a-401b-8b65-7d9672f952b3)

please assign me this task under the label of GSSOC 2023.

**Comment by akshathar-navada** [comment]
Hey @laibaahsan27 , this issue is resolved now. Please check it. If u have any other issue, pls open a PR, we would be happy to merge it:)

**Comment by laibaahsan27** [comment]
No sir this problem is still there and now your allignment is also disturbed as you can see the horizontal line just below the search bar has moved from its position.
@akshathar-navada I can fix both the problems if you assign this issue to me
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/123810454/0b355beb-f541-47c8-8939-71a826eedf58)
please assign it to under the label of GSSOC 2023
