### ISSUE TITLE
Feature : Add  button that allow you to create a new chapter for your institute [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [OSCode-Community/OSCodeCommunitySite#144]
I would like to add a button on the chapters page of the website that enables students to create a chapter for their college or institute in case it has not already been added.
![IMG_20230521_164157](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132778037/5f02a721-bbab-44c4-a359-28126a670a4f)

**EXPECTED BEHAVIOUR**
I would like to include a button below the search bar. If your college is not registered, clicking on this button will prompt a form to appear. You will need to fill out this form to register your college or create a chapter for your college.

So, please assign this issue to me under GSSOC'23. 

Thanking You.

**Comment by GeekAmita** [comment]
I would like to add this new feature. Please assign me this issue under GSSoC'23.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by akshathar-navada** [comment]
Hello buddies, as of now don't need. As we are approaching the colleges and need the respective college permission too to start the chapter.
Thank you!
