### ISSUE TITLE
Improve Contact Section UI and add Validation to.

### ISSUE THREAD

**Issue by Geeta259** [OSCode-Community/OSCodeCommunitySite#148]
![Screenshot (232)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/75520947/e041fb72-55da-460d-b592-951891273b91)

Want to improve the contact section form by adding some hover effect on it.
when input field is empty it show field by add some red border outside it
Error message shown below the input field.

All these task I would like to change., if you assign me !!
@akshathar-navada

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I can improve Contact Section UI and add Validation. I will give a hover effect on map, Email Us & Call Us when the mouse arrow is kept on it. I have all the skills required.
![SharedScreensh](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93476373/f3b04153-a72a-4c51-a371-2b2aef681f09)

Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by akshathar-navada** [comment]
Yes sure @Geeta259 , go ahead

**Comment by akshathar-navada** [comment]
> ![Screenshot (237)](https://user-images.githubusercontent.com/75520947/239908142-22494fef-d597-4068-b3b2-75bebc33a0c9.png) @akshathar-navada Is this work for you? After click on button it validate all field and print error message without refreshing page as shown in ss. Let me know if any improvement need!

Hey @Geeta259 , I didn't check this:(
Yes, this is nice . PLease go ahead and open a PR, we will happy to merge yourcode!!

**Comment by akshathar-navada** [comment]
Hey @Geeta259 , due to some improper merge of PR, your commit of this code has been changed. I would request u to do these changes again in the pinned issue and help us validate the contact section form.
Thank you!

**Comment by Geeta259** [comment]
@akshathar-navada  yeah sure!!
