### ISSUE TITLE
Important [BUG] Testimonial view isn't responsive

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#149]
# before
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/aab2ea29-fd62-4388-91a7-9dd80e0e4861)
But at 768px it is perfect. I resolved this issue and I want to contribute this bug. Please assign me this @akshathar-navada 
# After
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/497e8766-a430-4153-b6c9-a9c7bcb06aae)
Thanks again GSSoC'23

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @Git21221 . We will soon review and merge it!!
