### ISSUE TITLE
color needs to be changed

### ISSUE THREAD

**Issue by GurleenSingh201** [OSCode-Community/OSCodeCommunitySite#150]
### Description

With respect to user experience, The color upon selection (auto/manual) of the carousel can confuse the user if it's selected/changing or not.

### Expected Behavior

I will change its color from grey to white (when in an **active** state).

### Screenshots

![Bug1](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/75172927/fdc705fb-525c-42d2-8826-2eb1c2e1bb11)

### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

-> @akshathar-navada Please assign this issue to me under **GSSOC (2023).**

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I can change the color. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.
