### ISSUE TITLE
[BUG] samsung galaxy fold view isn't good

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#153]
# Before
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/cf812960-cf6d-421e-9ae8-22f7ae944754)
# After
Image is still processing. I will update later...till now you can assign me to fix this issue. Thanks
GSSoC'23

**Comment by akshathar-navada** [comment]
Yes @Git21221 ,go ahead. Ya no worries, take you time to resolve it:)

**Comment by Git21221** [comment]
The bootstrap css in navbar causing too much problem. I am writing new css for this.
Is it ok?

**Comment by Git21221** [comment]
# Before
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/e4cc2433-e1f9-4824-9d17-cfd3d6d89878)
# After
![Screenshot (138)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/d180dd9b-5ad3-480c-9145-29a617e58678)
There is a small changes in CSS as well as HTML. I have just overwrite some bootstrap.
Check out this changes and let me know if I need to change anything.

**Comment by Git21221** [comment]
# Before
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/d0554ee5-b218-428e-96e8-d1d65cd0edc6)

# After 
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/0372fd87-18bd-4a7b-9500-2d8f8169ca05)

# what I have changed
1. I have changed the navbar html tags to make it use flex rather than bootstrap flex
2. I have override bootstrap css to use my own css flex.
# what I haven't changed
1. I haven't changed any javascript.
Let me know if this design is good or do I need to change anything
