### ISSUE TITLE
Redirect not working properly

### ISSUE THREAD

**Issue by lmalkam** [OSCode-Community/OSCodeCommunitySite#154]
After clicking the os-code at the top it is not redirecting the website to it's home page rather it's redirecting on a page with does not exist

the page should redirect the page to https://www.oscode.co.in/index.html rather than https://www.oscode.co.in/events/index.html

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/103716615/e618d484-e11f-4697-b45c-99c587f528ec)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Hey @lmalkam , this issue was discussed in #136 . I have assigned there. So ,if there is any other issue u would like to work on, please go ahead. 
Thank you!!
