### ISSUE TITLE
Footer UI Improvement

### ISSUE THREAD

**Issue by Suhaani07** [OSCode-Community/OSCodeCommunitySite#155]
### Current Behavior
Double coloured Footer with copyright information aligned towards left

### Desired Behavior
Uniform black coloured footer. Copyright information aligned center. Socials aligned center below copyright info

If possible please assign it to me under GSSOC 2023

---

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me under GSSOC'23.

**Comment by akshathar-navada** [comment]
Hey @Avinash-NCEIAN , go ahead. Open a PR and add a screenshot of how it actually looks. We will review it and merge it soon!!

**Comment by Suhaani07** [comment]
Hey @akshathar-navada  I wasn't sure if i should create a pull request since you assigned this to me but told @Avinash-NCEIAN to work on it. Nonetheless, I have made a pull request which improves the footer. You can check it out and see. Thank You

**Comment by akshathar-navada** [comment]
> Hey @akshathar-navada I wasn't sure if i should create a pull request since you assigned this to me but told @Avinash-NCEIAN to work on it. Nonetheless, I have made a pull request which improves the footer. You can check it out and see. Thank You

I had assigned to u too mainly @Suhaani07 , and also told the other person to enhance it. ANyway, I think I have checked your PR.
Thank you!
