### ISSUE TITLE
Enhancing the README file

### ISSUE THREAD

**Issue by gummitha-anushka** [OSCode-Community/OSCodeCommunitySite#156]
### Current State:
The about us section is very brief and I feel it could use some description regarding the website.

### Desired State
I would like to work on the description about what the project is, its aim, features, achievements etc. This would give provide more clarity and understanding about the project. 
Screenshots of the components of the website and a brief description could increase its effectiveness. 
As a GSSOC'23 contributor, I would like to work on this so that the projects purpose is conveyed through the README file.

**Comment by akshathar-navada** [comment]
Yes go ahead @gummitha-anushka . We will review and merge it soon!

**Comment by gummitha-anushka** [comment]
Thank you so much @akshathar-navada
