### ISSUE TITLE
Improvement in styling of Blog section 

### ISSUE THREAD

**Issue by dhruvishavaghani** [OSCode-Community/OSCodeCommunitySite#157]
- In the blog section background color combination, font size, and position of icons needs to be fixed according to the theme of the site.

![Screenshot 2023-05-21 222035](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/109460833/30cb76db-27f8-41fb-b6d2-c67cbafff71f)

- In the newsletter section background, text field size, and font size needs to be fixed.

![Screenshot 2023-05-21 224048](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/109460833/7782b489-4ff1-4c26-88ab-9fe2122ec28a)

- Background for the member section needs to be changed accordingly.
 
![Screenshot 2023-05-21 224359](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/109460833/66205832-b212-410a-84cb-a838b7f292cb)

**Comment by Suhanimodi13** [comment]
How I can contribute in your project?

**Comment by Suhanimodi13** [comment]
●We can use "pastel colours for background", for example, we can go with pastel pink or blue with the combination of white this will look more attractive because nowadays young people are more fond of pastel colours.
●and the Icon size should be medium

**Comment by akshathar-navada** [comment]
Hey @dhruvishavaghani , thanks for stepping up. But as we are creating the blogs through hashnode, we will not able to give the access to everyone. If you are interested in enhancing any other thing, please go ahead.
Thank you!!
