### ISSUE TITLE
Sponsers and partners ui improvement

### ISSUE THREAD

**Issue by Suhaani07** [OSCode-Community/OSCodeCommunitySite#159]
### Current Behavior
All grey images. On hover becomes coloured. Image size too small to highlight reputed sponser's names.

### Desired Behavior
Increasing the image size. Removing grayscale. Keeping opacity at 0.8. On hover, fully visible. 

### Screenshots / Mockups
<img width="1080" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98284331/11baec94-74bf-4fd2-b16a-a0ee7ce1c827">

If desirable, please assign it to me under gssoc 2023

---

**Comment by akshathar-navada** [comment]
Hey @Suhaani07 , currently when u hover on 1 sponsor, only that will get it's color. If u want to work on any other issue, please go ahead.
Thank you!!
