### ISSUE TITLE
Fix the responsiveness of the Navbar 

### ISSUE THREAD

**Issue by akashgreninja** [OSCode-Community/OSCodeCommunitySite#16]

**Comment by SK-ILLish-GIT** [comment]
Hi, @akashgreninja 
I am writing to request that I be assigned to fix the responsiveness of the Navbar. I have experience and expertise in this area, and I am confident that I can complete the job quickly and to a high standard. I understand the importance of having a responsive Navbar, and I am eager to get started. I'm available to begin work immediately and I am confident that I can deliver the desired result.

Please let me know if you have any questions or if you would like to discuss the project further.

Thank you for your consideration.

**Comment by akashgreninja** [comment]
Hey buddy thanks for stepping up yea try to make it responsive and as this is a Open source  project you can pull a request at any time we would be happy to merge it 
thank you @SK-ILLish-GIT

**Comment by akashgreninja** [comment]
Tell me once you create a PR ill close this

**Comment by SK-ILLish-GIT** [comment]
@akashgreninja I have created PR just now.Check it and let me know everything is fine or not?

**Comment by akshathar-navada** [comment]
Changed the responsiveness
