### ISSUE TITLE
Not redirecting to home page when clicked on 'OS-Code' in the navbar in events page

### ISSUE THREAD

**Issue by Suhaani07** [OSCode-Community/OSCodeCommunitySite#160]
### Description
According to code, should direct to home page on clicking the Brand name in navbar. Instead showing other page attached in Screenshot. 

### Screenshots
<img width="806" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98284331/4a1b3b26-bf0f-457e-976b-bfd53579b954">

Please assign me this issue to fix under gssic 2023

**Comment by akshathar-navada** [comment]
This issue is discussed in #136 , if there is any other queries let us know
