### ISSUE TITLE
"Blog" page should open in a new tab.

### ISSUE THREAD

**Issue by Eninini** [OSCode-Community/OSCodeCommunitySite#161]
## Current Behaviour
Upon clicking, "blog" opens in the same tab with the navigation bar gone. User has to press back multiple times to visit other sections or go back to home.

### Desired Behavior
"Blog" should open in a new tab as it is a separate entity. Better UX.

**Comment by akshathar-navada** [comment]
Even chapter page is redirecting in the same page, we prefer that for consistency. If there is any other issue, u would like to work on, please go ahead
