### ISSUE TITLE
On clicking on link it doesn't redirect us to homepage.

### ISSUE THREAD

**Issue by Aarav238** [OSCode-Community/OSCodeCommunitySite#162]
### Description
On clicking on link it doesn't redirect us to homepage.

### Expected Behavior
I will modify the codebase so that it redirect us to homepage

### Screenshots
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/95538627/be168936-7e83-44cb-9be1-e058f4c2478b)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Yes @Aarav238 , please resolve the issue.

**Comment by Aarav238** [comment]
okay  i will raise a PR asap .
