### ISSUE TITLE
Improve the search field UI.

### ISSUE THREAD

**Issue by Aarav238** [OSCode-Community/OSCodeCommunitySite#163]
### Current Behavior
 I want to improve the styling of Search field.

### Desired Behavior
I will some css to make it attractive.

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/95538627/78c5ef7e-c92f-4e20-8b68-f23f0fe3e7c7)

---

**Comment by akshathar-navada** [comment]
PLease add required screenshot, on how the final outlook. U can open a pR and do that :)

**Comment by Aarav238** [comment]
okay  i will raise a PR asap .
