### ISSUE TITLE
Add Margins and Proper background in events section

### ISSUE THREAD

**Issue by Moumita2002** [OSCode-Community/OSCodeCommunitySite#164]
Current Behaviour:
Earlier the margin for the cards was not given properly and the background for the event section was not very much impressive.
Here's the screenshot for the earlier events section:
![2023-05-22 (2)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/102172188/a6bd0de4-c5fb-4c31-840f-46371f0d021a)

Desired Behaviour: 
Added proper margins with attractive background:
Here's the screenshot after making changes:
![2023-05-22 (4)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/102172188/110f9cb3-c3de-4780-a5e7-9f72b1b6f9ef)

Please Assign me this issue under GSSoC'23.

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @Moumita2002

**Comment by Moumita2002** [comment]
Thanks for assigning me
