### ISSUE TITLE
improve the front section

### ISSUE THREAD

**Issue by ARYAN-CODES-STAR** [OSCode-Community/OSCodeCommunitySite#165]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78686630/2edc6d52-e6c6-45ef-b4f2-1954a52382f9)

It's need to improve this part, and also to provide better color combination for this section.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @ARYAN-CODES-STAR
