### ISSUE TITLE
Improve buttons

### ISSUE THREAD

**Issue by ARYAN-CODES-STAR** [OSCode-Community/OSCodeCommunitySite#166]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78686630/e0b17a6c-1910-48d7-aed8-49c94479d969)

I want to improve the buttons by using some hover or such effects on it.

**Comment by akshathar-navada** [comment]
Open a PR, we would be happy to merge it :) @ARYAN-CODES-STAR

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
