### ISSUE TITLE
Event section navigation bar need change [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [OSCode-Community/OSCodeCommunitySite#167]
### Current Behavior
Navigation bar looks weird ,looks like overlapping the content below it.

### Desired Behavior
Minor background colour change/ transparent effect, I would like to resolve this issue under GSSOC 2023 ,do assign it to me ,changes will be done in no time :)

### Screenshots / Mockups
---
![WhatsApp Image 2023-05-22 at 1 36 23 AM](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96622693/ffa60859-bd3f-48b4-b90c-1ce01eb95582)

**Comment by akshathar-navada** [comment]
Yes go ahead @ManishaSwain8 , recently the glassmorphic effect is added to it, so if u want to enhance it more, pls do it. 
Thank you for your interest:)

**Comment by ManishaSwain8** [comment]
Ok cool  : |)

**Comment by ManishaSwain8** [comment]
no changes from my side, you can close the issue !
