### ISSUE TITLE
Event section layout 

### ISSUE THREAD

**Issue by Kaivanshah1** [OSCode-Community/OSCodeCommunitySite#170]
the cards in the event sections need to be place in proper column as people need to scroll lot to see all information
<img width="868" alt="Screenshot 2023-05-22 074457" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110343220/d02147cb-d97e-4841-97d0-3b8d0e651c4d">
<img width="960" alt="Screenshot 2023-05-22 074523" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110343220/8fc65e28-6c27-4c91-b812-efc4c560273f">
<img width="960" alt="Screenshot 2023-05-22 074608" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110343220/6ce0f333-e2aa-4ff5-af7d-145ed5c07a15">

**Comment by Kaivanshah1** [comment]
please assign me this issue I will work on it

**Comment by akshathar-navada** [comment]
This issue has been already assigned, if u want to work in any enhancement , please go ahead
