### ISSUE TITLE
Footer buttons

### ISSUE THREAD

**Issue by AmanSingh6574** [OSCode-Community/OSCodeCommunitySite#174]
### Current Behavior

On Hovering all the button backgrounds are of the same color 

### Desired Behavior

Will change it according to the application's original color 

### Screenshots / Mockups
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/113782984/068e515a-8e95-4b35-bbbf-a8892086c119)

---
I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23
@akshathar-navada

**Comment by Avinash-NCEIAN** [comment]
I want to work on rhis Project. Plzz assign it to me.

**Comment by akshathar-navada** [comment]
Hello buddies, as of know don't need to do this change. We need to maintain the color behavior also right. If there is any other iissue, please let us know
Thank you!
