### ISSUE TITLE
Readme Updation[Docs]

### ISSUE THREAD

**Issue by shraddha761** [OSCode-Community/OSCodeCommunitySite#175]
![Screenshot 2023-05-21 160801](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/106100728/3bd2a432-dc8b-4040-930a-59a892acf3c9)
adding this badge in readme makes it more attractive right now the badges on readme is less request to assign me this issue under GSSOC'23 label

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @shraddha761
