### ISSUE TITLE
[GSSOC '23] Fixing the navbar

### ISSUE THREAD

**Issue by shivu2002a** [OSCode-Community/OSCodeCommunitySite#177]
### Description
When clicked on the **chapters** button in the navbar, two **"events"** buttons are shown. And as well, with respect to the **page** that is being viewed currently, some **navbar** links must be hidden. For example, **"about"** should only be shown on the home page. On every other page, it doesn't have a valid link. Assign this issue to me, I'll fix it.

### Expected Behavior
Navbar should be handled smoothly and accordingly with respect to the page the user is in.

### Screenshots
Here is a screenshot : 
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/88313126/9d8789af-0e7f-4654-a3b5-f7c49712e237)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Michelle031** [comment]
Please can I be assigned this issue

**Comment by akshathar-navada** [comment]
Hello buddies, the event thing appearing twice is resolved. We have linked the about section to let us know who we are . I think it's better to have. If there is any other issue, pls let us know
Thank you!
