### ISSUE TITLE
Navbar responsiveness issue in small devices.

### ISSUE THREAD

**Issue by Devil1205** [OSCode-Community/OSCodeCommunitySite#183]
### Description

Navbar size overflows and not positioned properly for small screen devices.
### Expected Behavior

It should be a litter lower than current position.
### Screenshots

![127 0 0 1_5501_index html (1)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/103431946/be3191f9-bb5b-47a2-a475-e9260d46da6f)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Please assign me to fix this issue.**

**Comment by akshathar-navada** [comment]
Hello buddies, I think the current position of it in terms of height is fine. If there is any other issue, u want work on, pls go ahead
