### ISSUE TITLE
Improving the UI of the landing page

### ISSUE THREAD

**Issue by Sreenija03** [OSCode-Community/OSCodeCommunitySite#184]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119659973/0dffb22e-3643-4653-a614-b33e6cedc468)
Improving the colour scheme of text and the buttons.

**Comment by Sreenija03** [comment]
Please assign this issue to me under GSSOC 2023

**Comment by akshathar-navada** [comment]
Yes, go ahead @Sreenija03 . Pls add a screenshot while you are opening a PR
