### ISSUE TITLE
Add the Chapter,Blogs and Events page as react component

### ISSUE THREAD

**Issue by PRIZZA21** [OSCode-Community/OSCodeCommunitySite#186]
### Current Behavior

Currently when you click on chapter , blog or event page the page reloads to render the  output

### Desired Behavior

I plan to use react component to prevent the reloading of pages upon clicking on them.

### Screenshots / Mockups

---

**Comment by Manvi1902** [comment]
i want to contribute in this

**Comment by akshathar-navada** [comment]
Yes go ahead @PRIZZA21 @Manvi1902 . I will be assigning this to both. Open a PR and we will be happy to merge it
