### ISSUE TITLE
[GSSOC'23] Adding hover to "college chapters"

### ISSUE THREAD

**Issue by purviporwal0** [OSCode-Community/OSCodeCommunitySite#187]
Adding hover effects to "college chapters" refers to applying interactive behavior to elements on a webpage when a user hovers their cursor over them. By implementing hover effects, one  can create a more engaging and dynamic user experience. 
![Screenshot (13)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/116807722/7f660c20-62bb-4a3c-b8ed-508a6c7659ff)

**Comment by akshathar-navada** [comment]
Hey @purviporwal0 , the image which u have added is not loaded, can u pls add it properly

**Comment by akshathar-navada** [comment]
Yes go ahead @purviporwal0 , open a PR with required screenshot . We will soon review and merge it!!
