### ISSUE TITLE
Full form is not correct in Readme.md[Docs]

### ISSUE THREAD

**Issue by shraddha761** [OSCode-Community/OSCodeCommunitySite#188]
In the readme section full of GSSOC is not correct Assign me this issue under GSSOC'23 label

**Comment by akshathar-navada** [comment]
> In the Readme file Full Form of GSSOC is mistakenly wrong !! It is Global Summer Of Code !! I would like to correct it to Girl Script Summer Of Code !! Please assign this task to me!! ![image](https://user-images.githubusercontent.com/110019310/239917523-c0d3b2f1-ce61-479a-8bd9-b236593d65ef.png)

Hey @jayshivare7 , thanks for letting us know, pls add this image to the readme file and also update the line below it , which is currently there

**Comment by shraddha761** [comment]
@akshathar-navada Just to let you know that I raised the issue first

**Comment by shraddha761** [comment]
@akshathar-navada just to let you know I raised the issue first

**Comment by jayshivare7** [comment]
Hey Mentor Here is the Mistake in Readme file!
![abc gthub](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110019310/ef394fd6-d181-4bb5-9b21-1ef93d7be11a)
And the correct full form is -:
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110019310/8d05e24e-aeec-4687-9d6a-61cd3ee5fb11)
