### ISSUE TITLE
Adding blogs in the blogs section

### ISSUE THREAD

**Issue by trisharaj06** [OSCode-Community/OSCodeCommunitySite#192]
I want to add some blogs in the form of cards, user can click and read that particular blogs, please assign this to me

**Comment by akshathar-navada** [comment]
Hey @trisharaj06 , thanks for stepping up. Actually we are creating the blogs using hashnode. SO we won't be able to give access to everyone. If there is anything else in which u would like to work on ,pls go ahead:)
