### ISSUE TITLE
Add a gallery section 

### ISSUE THREAD

**Issue by arjun26122002** [OSCode-Community/OSCodeCommunitySite#194]
### Current Behavior
 This will be make a huge organisation one day , &  i think if there was a gallery section then this should be  show nice .
 
i am under the Gssoc'23 ,can i work on this ?
### Screenshots / Mockups

---
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/88227330/bb289292-ae9e-408a-bf2a-b5a03c3cd55b)

**Comment by akshathar-navada** [comment]
Hey @arjun26122002 , as of now don't need to create a separate section for gallery, as we are planning to add it in our blog.
And we are also quite active in social medias. If there is any other issue, which u would like to work on.. pls go ahead.
Thank you:)

**Comment by arjun26122002** [comment]
@akshathar-navada ok thank you sir
