### ISSUE TITLE
Remove console messages

### ISSUE THREAD

**Issue by Avinash905** [OSCode-Community/OSCodeCommunitySite#20]
![Screenshot (414)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/56786344/08740069-f0c5-4955-ae47-ac5927389ed2)

The console.log messages are appearing in the console tab.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can remove the console.log messages under GSSOC-23

**Comment by akshathar-navada** [comment]
Yes sure, go ahead!! @Avinash905

**Comment by Avinash905** [comment]
> Yes sure, go ahead!! @Avinash905

Can you please add GSSOC'23 label to this issue?

**Comment by akshathar-navada** [comment]
> > Yes sure, go ahead!! @Avinash905
> 
> Can you please add GSSOC'23 label to this issue?

@Avinash905 Open a PR , we will review it and the label soon

**Comment by Avinash905** [comment]
> > > Yes sure, go ahead!! @Avinash905
> > 
> > 
> > Can you please add GSSOC'23 label to this issue?
> 
> @Avinash905 Open a PR , we will review it and the label soon

Ok sure

**Comment by Avinash905** [comment]
@akshathar-navada is this counted in the GSSOC'23?

**Comment by akshathar-navada** [comment]
Yes, I will add the label:)

**Comment by Avinash905** [comment]
> Yes, I will add the label:)

Thank You
