### ISSUE TITLE
Improving search list

### ISSUE THREAD

**Issue by trisharaj06** [OSCode-Community/OSCodeCommunitySite#201]
even after deleting characters from search bar, the search list still appears on the page. Also I want to make changes on the UI of search list to make  it more readable. kindly assign this issue to me.
![Screenshot (723)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/109025651/959674d6-d298-4d0d-a682-6e65b86f0af4)

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @trisharaj06
