### ISSUE TITLE
Not redirecting to Home page when clicked on 'OS-CODE' in navbar when on chapters page

### ISSUE THREAD

**Issue by Suhaani07** [OSCode-Community/OSCodeCommunitySite#204]
### Description
Redirects to the attached screenshot instead of home
<img width="724" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98284331/3d442203-1ab7-4ccd-99c3-654b1d1c448c">

Please assign me this issue to fix under GSSOC 2023. Mostly it is a path problem which I'll be able to fix

**Comment by Shreyadr09** [comment]
I want to work on this issue under GSSOC 2023. Can you assign it to me?

**Comment by akshathar-navada** [comment]
Yes sure @Shreyadr09 ,pls go ahead

**Comment by Suhaani07** [comment]
Hi @akshathar-navada wanted to ask, any particular reason you assigned @Shreyadr09 for this issue? Because I think I raised the issue and as far as I know, the assignment is on first come basis. So if it's by mistake, please assign me the issue as I raised it. Thank you

**Comment by Suhaani07** [comment]
Hi @akshathar-navada i think this issue needs to be closed as in the latest commit the issue is fixed. Thank you
