### ISSUE TITLE
Add transition effect in events card.

### ISSUE THREAD

**Issue by Aarav238** [OSCode-Community/OSCodeCommunitySite#208]
### Current Behavior
there is not transition effect in the box shadow.

### Desired Behavior
 I will add transition effect that will make it more attractive.

### Screenshots / Mockups
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/95538627/788eb207-3474-48e7-ad76-a1b26c9a0e14)
I will transition effect on it.

---

**Comment by Aarav238** [comment]
I have raised a PR  #203 regarding this. Please assign this issue to me under gssoc. Please review the PR and mention me  if any changes are required.

**Comment by akshathar-navada** [comment]
Thanks Aarav, we have merged your PR:)
