### ISSUE TITLE
Improve design of responsive navbar

### ISSUE THREAD

**Issue by Avinash905** [OSCode-Community/OSCodeCommunitySite#21]
Current mobile navbar looks like this:

![Screenshot (415)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/56786344/011c4f05-2300-458a-9c82-f76ceda5c3ca)

Please assign me this issue so that I can improve the design under GSSOC-23

**Comment by imrish4** [comment]
Please assign me this issue under GSSOC 23

**Comment by smritimangal26** [comment]
I would like to enhance the look of the navbar, kindly assign me this issue under GSSOC'23

**Comment by MohnishK7** [comment]
Kindly assign me this issue under GSSOC'23.
The navigation bar component will encompass the following key features:
**Menu Items:** The navigation bar will support multiple menu items, allowing users to navigate to different sections or pages of the web application or website.
**Dropdown Menus:** It will provide the ability to include dropdown menus, enabling hierarchical navigation and organizing related links.
**Responsive Design:** The navigation bar will be responsive, adapting to different screen sizes and devices for optimal user experience.
**Customizability:** The component will be highly customizable, allowing users to modify the appearance, colors, and styles to match their project's branding and design requirements.
**Accessibility:** Accessibility features, such as keyboard navigation, ARIA attributes, and proper semantic structure, will be implemented to ensure an inclusive user experience.
The tech stack will be HTML, Tailwindcss, and Javascript for responsiveness.
and I can Implement Neumorphism and Glassmorphism UI Designs.

**Comment by akshathar-navada** [comment]
This issue will be open to all . Open a PR and we will merge the best one!!

Go ahead 🤩 @Avinash905 @MohnishK7 @imrish4 @smritimangal26

**Comment by shraddha761** [comment]
Hye assign me this issue under GSSOC'23

**Comment by akshathar-navada** [comment]
> @akshathar-navada Hye assign me this issue under GSSOC'23

Hey @shraddha761 , this issue is resolved, if there is any other issue u want to work on, pls go ahead and open a PR. We would be happy to merge it:)
