### ISSUE TITLE
Back to website from privacy policy page and Blog page.

### ISSUE THREAD

**Issue by Killer2OP** [OSCode-Community/OSCodeCommunitySite#211]
### Current Behavior
As we go to privacy policy page or Blog page from the main website there is no option to go back to the main website.
### Desired Behavior
I can add a button or can add logo of the website which can act as back to home button.
Assign me this issue under GSSoC'23
### Screenshots / Mockups
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/111378171/e093310b-5c44-42a4-83de-8db8da327376)

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/111378171/bdfe7564-14ce-4a68-975a-c80db35b26ab)

---

**Comment by akshathar-navada** [comment]
@Killer2OP We are creating the blog page through hashnode. So , we won't be able to give access to that.
U can add the logo to the privacy page. Please add a screenshort as well, while opening a PR

**Comment by Killer2OP** [comment]
OK I will do so.
