### ISSUE TITLE
Contact us and About are not working

### ISSUE THREAD

**Issue by Killer2OP** [OSCode-Community/OSCodeCommunitySite#213]
### Description
When we go to chapters page then the about and contact us button are not giving us the desired result as they used too.
### Expected Behavior
The about button should take us to about section in home page and contact us button to contact section in main page.

Assign me this under GSSoC'23

**Comment by akshathar-navada** [comment]
Hey @Killer2OP ,it was made to redirect to the chapter page itself, to maintain the consistency
