### ISSUE TITLE
Enhance : Cards of the accomplishment section [GSSOC'23].

### ISSUE THREAD

**Issue by Pragati-3003** [OSCode-Community/OSCodeCommunitySite#218]
I would like to change the ui/ux of the cards in accomplishment section as the size of the cards are inconsistent. Also, I would also like to enhance the ui of while accomplishment section. 
![IMG_20230522_220339](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132778037/b6f56190-4fd7-47fe-8c65-3088b849aebc)

So, please assign this issue to me . 

Thanking you.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Pragati-3003

**Comment by Pragati-3003** [comment]
Please add level no.  to this issue. 
Thanking you.
