### ISSUE TITLE
Size of Youtube icon

### ISSUE THREAD

**Issue by Shreyans2004** [OSCode-Community/OSCodeCommunitySite#219]
### Description

The size of Youtube icon(in the footer section of main page) is not increasing  on hovering
### Expected Behavior

Other icons (example Instagram and others) in the footer section are increasing in size when they are hovered. But only the Youtube icon is not increasing in size. I can increase the size of the icon so that it will look same as other icons in the vicinity .
I would like to work on this issue .Can you assign it to me?
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Shreyadr09** [comment]
Hey Can I work on this issue with @dhawansolanki under GSSOC 2023

**Comment by akshathar-navada** [comment]
Hey @Shreyans2004 , thanks for noticing it, pls resolve this issue
