### ISSUE TITLE
Enhance : Testimonial section. 

### ISSUE THREAD

**Issue by Pragati-3003** [OSCode-Community/OSCodeCommunitySite#220]
I would like to improve the ui of the testimonial section. 
I would like to change the background color and would like to make  a cards for the same. 
![IMG_20230522_222752](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132778037/99da7c48-cca7-453a-817a-a8fb157d462b)

So, please assign this issue to me under GSSOC'23. 

Thanking you.

**Comment by akshathar-navada** [comment]
Yes sure,go ahead @Pragati-3003 :)

**Comment by Pragati-3003** [comment]
> Yes sure,go ahead @Pragati-3003 :)
Thanks for assigning this issue to me.

**Comment by Shrejal123** [comment]
I wants to add hover effect on testimonials section .Please assign this issue under GSSoC 23
