### ISSUE TITLE
chapter page is not responsive[GSSOC'23]

### ISSUE THREAD

**Issue by madtitan02** [OSCode-Community/OSCodeCommunitySite#222]
when clicked on chapter through navigation bar. A list of college appears but when clicked on college name it directs to the same page in new tab not the college site it was mentioned. Also add hover over college names. Assign this to me i will fix it.

**Comment by akshathar-navada** [comment]
Hey @madtitan02 , we are actually creating separate pages to each  colleges. Working in progress:)
If there is any other isssue, u would like to work on, pls go ahead
