### ISSUE TITLE
number's say it all cards section 

### ISSUE THREAD

**Issue by NexusNeeraj** [OSCode-Community/OSCodeCommunitySite#223]
### Current Behavior
on hovering over the number say it all cards section it doesn't show any animation

### Desired Behavior
I'll add some animation on hovering these cards.

pls assign this issue to me in Gssoc 2023
---

**Comment by akshathar-navada** [comment]
Yes sure @NexusNeeraj

**Comment by NexusNeeraj** [comment]
As this issues (#223)  was assigned to me so how one can change it?
It's showing hanges which was supposed to do with my own .but it seems like
someone has changed this so what should I do ?
