### ISSUE TITLE
NO link associated with logo

### ISSUE THREAD

**Issue by Shreyans2004** [OSCode-Community/OSCodeCommunitySite#224]
### Description

The  logo has no link associated with it. There is no option to click on logo and navigate to the website
### Expected Behavior

Generally the logo with the website name is asscoiated with a link of some website . When we click the logo or the name of website ,we navigate to other website. In the Front page upon clicking on the website we are navigating to it  but this feature is not there with the logo.I can add the link to the logo so that clicking on either of the logo or website ,the user can navigate  .Can you assign this task to me?
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
@Shreyans2004 As the OS-COde text beside the logo is directing to the link, we think this is not required. 
If there is any other issue in which u would like to work on, pls go ahead:)
