### ISSUE TITLE
os-code logo redirection not working [Gssoc'23]

### ISSUE THREAD

**Issue by madtitan02** [OSCode-Community/OSCodeCommunitySite#225]
when clicked on os-code logo from other page eg,I clicked on os code logo from chapters page redirection to main page is not working.It shows the following error
![Screenshot (10)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96717231/40e3906a-36fd-414a-a105-35221a5ee4b1)

also we can add os-logo in blog section so that we can get redirected to main page easily.

**Comment by akshathar-navada** [comment]
Yes,pls resolve it @madtitan02
