### ISSUE TITLE
Improving the readme file

### ISSUE THREAD

**Issue by harshsingh32** [OSCode-Community/OSCodeCommunitySite#23]
I would like to improve the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by akshathar-navada** [comment]
Hello buddies, thanks for stepping up. As this is a Open source project you can pull a request at any time we would be happy to merge it
Thank you! @harshsingh32 @SamridhiNancy
