### ISSUE TITLE
Header UI update 

### ISSUE THREAD

**Issue by KashiwalHarsh** [OSCode-Community/OSCodeCommunitySite#230]
This is an Enhancement Update I want to make to this project as the current Header UI gives the feel of a newbie frontend work. And personally, I feel it can look a lot better 

I can update the header UI to make it look more professional and elegant

here is one idea from my previous project

<img width="663" alt="Screenshot 2023-05-22 233713" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/77677724/9b7b2d28-c491-4ed7-bda5-9bd50a13b8a3">

Can you please assign this work to me under GSSOC 
Thanks.

**Comment by akshathar-navada** [comment]
Nice @KashiwalHarsh ,please go ahead !
