### ISSUE TITLE
[GSSOC'23] Adding underline to navbar items on hover 

### ISSUE THREAD

**Issue by purviporwal0** [OSCode-Community/OSCodeCommunitySite#231]
![Screenshot (25)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/116807722/f7ccfa49-fa3b-4470-a477-69c5aae2a8f5)
it will improve the ui , and navbar will look beautiful

**Comment by akshathar-navada** [comment]
@purviporwal0 Yes , u can improve this. Open a PR  with required screenshot, we will review and merge it soon:)

**Comment by khushi767** [comment]
i can work on the required issue can you please assign me this
