### ISSUE TITLE
[GSSOC'23] Changing color of "Os-code" in the footer 

### ISSUE THREAD

**Issue by purviporwal0** [OSCode-Community/OSCodeCommunitySite#232]
![Screenshot (26)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/116807722/6f083813-dbcf-4586-a88b-ce323bea50eb)
As this is not clearly visible in the footer in "chapters" section

**Comment by akshathar-navada** [comment]
Yes sure @purviporwal0 , go ahead

**Comment by ayushrathore111** [comment]
can you please assign it to me
