### ISSUE TITLE
[GSSOC'23] Adding same navbar in the blogs section

### ISSUE THREAD

**Issue by purviporwal0** [OSCode-Community/OSCodeCommunitySite#234]
Adding same navbar in the blogs section as in the other sections of the page 

By doing this the blogs section will not look different from the rest of the page and other sections could be navigated easily from the blogs section
![Screenshot (28)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/116807722/1b785229-5b18-4395-9f5e-ff030d6e5713)

**Comment by AnkitAnandMastery17** [comment]
Hi, I am interested in solving this issue. Can you assign this to me?
