### ISSUE TITLE
Footer in home and events page is different. GSSoC'23

### ISSUE THREAD

**Issue by AdityaLahane-2003** [OSCode-Community/OSCodeCommunitySite#235]
### Description

The footer in home and events page is different 
### Expected Behavior

On both pages, the footer should be similar in design.
### Screenshots

![cu](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108022893/b8282cfb-ab17-464c-bc4e-d8c88bad228d)
![cu2](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108022893/b72fd717-a3ed-4878-a3e9-60c9bf238c50)

### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

I would like to work on this issue, as a part of GSSoC'23, Please assign this issue to me.

**Comment by akshathar-navada** [comment]
We will review it soon @AdityaLahane-2003
