### ISSUE TITLE
Animating text on Home page. [GSSoC'23]

### ISSUE THREAD

**Issue by AdityaLahane-2003** [OSCode-Community/OSCodeCommunitySite#239]
### Current Behavior

Stable Text.
### Desired Behavior

'A Community of Learners, Creators, and Contributors' To give animation and hover effect to this text.
### Screenshots / Mockups

---
- Please assign this issue to me, I want to solve it as a part of GSSoC'23.

**Comment by akshathar-navada** [comment]
Yes sure @AdityaLahane-2003
