### ISSUE TITLE
Navbar items position. [GSSoC'23]

### ISSUE THREAD

**Issue by AdityaLahane-2003** [OSCode-Community/OSCodeCommunitySite#242]
### Description

Items changing position on different pages.
### Expected Behavior

Navbar items should be same on all pages.
### Screenshots

Home -
![n1](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108022893/88ae9235-5157-4f2c-a201-c692be5f0ee7)

Chapters-
![n2](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108022893/3e614cb9-8291-47b7-a200-211876302445)
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

Please assign this issue to me, I want to contribute as a part of GSSoC'23.

**Comment by akshathar-navada** [comment]
Go aheaad @AdityaLahane-2003 :)
