### ISSUE TITLE
Adding Contact Us Page instead of contact Section [GSSOC 23]

### ISSUE THREAD

**Issue by dhawansolanki** [OSCode-Community/OSCodeCommunitySite#245]
Currently Only a Contact Section is there on Home Page.
So if you go to other page (Eg. Chapters) and then you click on Contact us button in Navbar then it will scroll to footer.
This can be fixed by adding a contact Page. So from whatever page you click on contact Us button it will redirect to contact form.

Please Assign me with this Task under GSSOC 23.
Do let me know for any clarifications.
Thank You.

### Steps to reproduce
Adding Contact-us.html (page)

### Screenshots
Contact Us Button in Navbar
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/91565429/97287151-3c65-4362-b98d-dce0a149eb5c)

when clicked on that button it scrolls to footer section
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/91565429/a7dbe129-3580-4ecf-8d7f-0b090034ba49)

this can be fixed by adding contact form in contact page
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/91565429/e33a8833-b651-42e7-8c7e-143bbd1b4c19)

Desktop -> Macbook Air M1, Chrome

**Comment by akshathar-navada** [comment]
Yes, good idea. Please create a separate page for contact. It would be a  great contibution to our repo:)

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by akshathar-navada** [comment]
Yes sure, go ahead!
