### ISSUE TITLE
College Chapter Page Sub Links Redirect to same Page [GSSOC 23]

### ISSUE THREAD

**Issue by dhawansolanki** [OSCode-Community/OSCodeCommunitySite#247]
in Chapters Page. 
<img width="1436" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/91565429/6b85781a-216b-4394-af34-425992dfcb64">

When you click on Any College Page -> it redirects and open the same page in new tab.

This can be fixed by Redirecting it to the official college website OR Chapter website.

I would like to work on this Task. Please Assign me this under GSSOC 23. Thankyou.

**Comment by dhawansolanki** [comment]
I would like to work on this Task. Please Assign me this under GSSOC 23. Thankyou.

**Comment by akshathar-navada** [comment]
Hey @dhawansolanki , we are currently creating separate pages for each colleges. We will link it soon:)
