### ISSUE TITLE
Scroll Down Button for pages like Events

### ISSUE THREAD

**Issue by anshumanjaiswal** [OSCode-Community/OSCodeCommunitySite#248]
I want to add scroll down button for events pages or in all the pages because if the list is too long like in events section it is not easy for user to scroll down that much.

**Comment by anshumanjaiswal** [comment]
Please assign it to me under GSSOC'23

**Comment by jamalimubashirali** [comment]
I will take care of this issue can you please assign to me under GSSOC'23

**Comment by akshathar-navada** [comment]
Yes @anshumanjaiswal ,pls go ahead and add that to both event page and chapter page:)

**Comment by anshumanjaiswal** [comment]
Ok sure!

**Comment by anshumanjaiswal** [comment]
Why did you close this issue? , I was working on it!
