### ISSUE TITLE
Enhance: Blog page Home  [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [OSCode-Community/OSCodeCommunitySite#254]
I would like to change the Home page inside the blog page of the website. 
![IMG_20230523_121238](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132778037/ca986ade-66da-468c-b358-2af19ef1cdd7)
I would like to change the ui and layout . 
So, please assign this issue to me. 
Thanking  You

**Comment by khushi767** [comment]
i would like to enchance this page and add more features to it can you please assign me this issue
