### ISSUE TITLE
Modify : Newsletter page [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [OSCode-Community/OSCodeCommunitySite#255]
I would like to change ui the Newsletter page.
![IMG_20230523_121230](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132778037/3a865968-962e-47ba-b4aa-a198e727c537)
So, please assign this issue to me. 
Thanking you.

**Comment by akshathar-navada** [comment]
This is mentioned in the previous issue @Pragati-3003 , pls chk

**Comment by Pragati-3003** [comment]
> This is mentioned in the previous issue @Pragati-3003 , pls chk

Ok.
