### ISSUE TITLE
Responsiveness in events section

### ISSUE THREAD

**Issue by Himanshu-Kumatiya** [OSCode-Community/OSCodeCommunitySite#256]
The main content of the event section is overlapping.
Assign me this under GSSOC'23
![Screenshot (93)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/88624005/cc4c8365-e13d-4728-a9a3-f41fdecdacd8)

**Comment by anand346** [comment]
May I solve this issue

**Comment by akshathar-navada** [comment]
Yes @Himanshu-Kumatiya , pls go ahead and resolve this issue

**Comment by Himanshu-Kumatiya** [comment]
Please review the PR. If any changes required please let me know
