### ISSUE TITLE
Email Validator Not Correct

### ISSUE THREAD

**Issue by gmmkmtgk** [OSCode-Community/OSCodeCommunitySite#26]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/51493190/955f3127-2bb2-4c5d-98dd-dce9c7e4c362)

Kindly assign this issue to me

**Comment by Sharad-Pratap** [comment]
Please assign this project to me

**Comment by akshathar-navada** [comment]
> ![image](https://user-images.githubusercontent.com/51493190/239681321-955f3127-2bb2-4c5d-98dd-dce9c7e4c362.png)
> 
> Kindly assign this issue to me

Yes sure, fix the issue @gmmkmtgk

**Comment by gmmkmtgk** [comment]
@akshathar-navada could you please add gssoc 23 label

**Comment by akshathar-navada** [comment]
> @akshathar-navada could you please add gssoc 23 label

Yes sure, open a PR , we will review and add the label soon!
