### ISSUE TITLE
The REACH US section is not in center in Small screen [ GSSoC '23]

### ISSUE THREAD

**Issue by ritik48** [OSCode-Community/OSCodeCommunitySite#260]
### Current Behavior
When the site is viewed on smaller screen , then the reach us section on home page is not aligned properly

### Desired Behavior
I want to center that section so that it looks good on smaller screen

### Screenshots / Mockups

![os code mobile reach issue](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/84488726/4a14b8ea-c429-4d1a-a02e-03c7c15229ac)

Please assign this issue to me.
---

**Comment by peb-peb** [comment]
Sure @ritik48, go ahead and submit a PR

**Comment by ritik48** [comment]
Hey @peb-peb,
Please review my pr #266
