### ISSUE TITLE
Change the Home Page

### ISSUE THREAD

**Issue by Moumita2002** [OSCode-Community/OSCodeCommunitySite#261]
### Description

The Text in the home page is not properly visible and seems to be messy.

![2023-05-23 (3)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/102172188/de1b3aa0-90fc-4004-a541-9de0841b2fa9)

### Expected Behavior

![2023-05-23 (5)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/102172188/a525c98d-6a93-4cd5-9604-53995669d18d)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Hello buddies, thanks for stepping up. As of now this is not required. IF there is any other enhancement, pls go ahead
