### ISSUE TITLE
Pre loader page addition [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [OSCode-Community/OSCodeCommunitySite#267]
### Desired Behavior
want to add a loader to the website to make it attractive and fun.

If this feature is required please to assign it to me under GSSOC 2023. :)

---

**Comment by akshathar-navada** [comment]
Yes sure @ManishaSwain8 , go ahead:)

**Comment by ManishaSwain8** [comment]
Wanted help,
any changes I am doing in Chapter,.html file ,are not reflecting.  :(
