### ISSUE TITLE
Fix the layout of 'WHY CHOOSE US' section 

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#269]
### Current Behavior

![Screenshot (401)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/7a69d3f1-16ee-45f9-b8ba-d782acda3c27)

### Desired Behavior

![Screenshot (405)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/ba5fd0b3-04cc-4ff3-90e5-a949e4164218)

### Points to be noted 

-- Please give the brief desciption of the PR  with required screenshots
-- Pull the repo properly and then make required changes:)
-- We will review it soon and would be very happy to merge your PR 

### Happy coding 🤩
---

**Comment by Git21221** [comment]
@akshathar-navada is it ok?
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/75c022cc-faaf-4c5c-9d1e-f9a589df75ce)

**Comment by SasiVardhan247** [comment]
Can you assign this issue to me @akshathar-navada . I'm in gssoc'23

**Comment by akshathar-navada** [comment]
> @akshathar-navada is it ok? ![image](https://user-images.githubusercontent.com/101005577/240246536-679c66b2-e367-4123-a640-84e5bf946be9.png) I didn't change nav bar intentionally. If I give space in left and right then in small device it doesn't look good.

Okay fine @Git21221 . Can u pls align the divs accordingly, I mean the bullet list div and the content top must be at the same height, as shown in the desired behaviour. Try if u can fix this..

**Comment by akshathar-navada** [comment]
> Can you assign this issue to me @akshathar-navada . I'm in gssoc'23

Yes, even u can try solving this issue @SasiVardhan247

**Comment by ritik48** [comment]
@akshathar-navada ,
I have tried this, if you like I would create a pr.

#### Preview
- lg screen
![os lg](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/84488726/faa36942-955e-430b-832e-d1bd6fa016a7)

- md screen
![os md](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/84488726/dc4ac44d-a8a1-4f30-ab57-8a4d03b3bcf3)

- sm screen
![os sm dektop](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/84488726/0d655468-ceb5-4d0c-90c3-948323f0fa4f)

**Comment by Git21221** [comment]
@akshathar-navada check this out.
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/d654f2f3-a60f-499b-a93e-93fdc952a2c1)
Let me know about the hover color as well, although someone is working on that issue (2nd pinned issue).
