### ISSUE TITLE
Responsiveness review (pixel 5)

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#270]
# Before
<img src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/ea904c0b-beec-4eb4-b3e6-d65ae6475ef6"  height = 300>

## view in pixel 5

<img src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/a022ea42-9a4f-4ecc-b600-12ac44d65289" height=300>

# After

<img src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/455acb71-dc70-48ef-b011-f22a3e837cf5" height = 300>

## view in pixel 5

<img src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/efae8ba5-7613-4047-9ab3-9b63057e937d" height=300>

**Comment by Git21221** [comment]
I already fixed this. Waiting for your response to make a pr. GSSoC'23

**Comment by akshathar-navada** [comment]
Oh great! @Git21221 , thanks for your interest in contributing to our repo . Please open a PR, we will review and merge it soon:)
