### ISSUE TITLE
Change the hovering color of the 'WHY CHOOSE US' bullet list

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#271]
### Current Behavior

![Screenshot (406)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/85b564c9-5283-4847-a3ea-f5ff2e71959e)

### Desired Behavior

--The light purple color is not much satisfying to us when hovered, so pls change the color
--Try to add the color as same as the active color of the bullet list

### Points to be noted
-- Please give the brief desciption of the PR with required screenshots
-- Pull the repo properly and then make required changes:)
-- We will review it soon and would be very happy to merge your PR

### Happy coding 🤩

---

**Comment by radhikakakkar** [comment]
hi, i would like to work on this issue

**Comment by yyuvraj54** [comment]
I would like to work on this ,please assign me this issue under gssoc23

**Comment by crapbagaah** [comment]
Hi, I would like to work on this, please consider me and assign this work to me, I have experience with html, css and javascript, and I'm approaching you through GSSOC'23

**Comment by radhikakakkar** [comment]
hi @akshathar-navada, i have a doubt regarding the issue stated here, should i ask it here?

**Comment by radhikakakkar** [comment]
i hope you can see my pull request, this is the first time i've created one :)

**Comment by akshathar-navada** [comment]
> i hope you can see my pull request, this is the first time i've created one :)

Hey @radhikakakkar your commit has conflicts through which we won't be able to  merge your PR, pls pull the repo properly and then make required changes. Also add required screenshots in the PR, so that it will be easy for us to review:)
