### ISSUE TITLE
[GSSOC'23] -  Issue in the navbar of Events tab

### ISSUE THREAD

**Issue by VyjayantiN** [OSCode-Community/OSCodeCommunitySite#272]
Description
The buttons like Home, About, etc., on the Events page are not functioning correctly and do not navigate to their respective pages.

Expected Behavior
When clicking on the buttons like Home, About, etc., on the Events page, I expect to be redirected to the corresponding pages (e.g., clicking on "Home" should take me to the home page, clicking on "About" should take me to the about page, etc.).

Screenshots
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/106438430/698477f0-5c62-4dd5-8620-bf4a48ff0134)

Environment:
OS: Windows
Browser: Chrome
Version: 93.0.4577.63
Device: Desktop

**Comment by VyjayantiN** [comment]
I would like to work on this issue. Please assign me this issue under GSSOC'23!!

**Comment by akshathar-navada** [comment]
Yes sure @VyjayantiN , go ahead!!

**Comment by VyjayantiN** [comment]
Thank you
