### ISSUE TITLE
[GSSOC'23]  -  Improper working of navbar of events tab

### ISSUE THREAD

**Issue by VyjayantiN** [OSCode-Community/OSCodeCommunitySite#273]
Description
The navigation bar tabs are **incorrectly highlighted** when the user is on the Events page. Specifically, when visiting the Events page, the "Home" tab in the navigation bar is highlighted instead of the "Events" tab.

Expected Behavior
When the user is on the Events page, I expect the "Events" tab in the navigation bar to be highlighted to indicate the current active page.

Screenshots
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/106438430/b4dd501e-1a83-4592-b2f1-f702e2ba3053)

Environment:
OS: Windows
Browser: Chrome
Version: 93.0.4577.63
Device: Desktop

**Comment by VyjayantiN** [comment]
I would like to work on this issue. Please assign me this issue under GSSOC'23!!

**Comment by akshathar-navada** [comment]
Yes @VyjayantiN , go ahead:)

**Comment by VyjayantiN** [comment]
Thank you
