### ISSUE TITLE
[GSSOC'23] - Unnecessary usage of anchor tag in chapters page. 

### ISSUE THREAD

**Issue by VyjayantiN** [OSCode-Community/OSCodeCommunitySite#274]
Description
There is unnecessary usage of anchor tags on the Chapters page. The anchor tags are currently redirecting to the same Chapters page instead of linking to different chapters. If the chapter names are not intended to be clickable links, the anchor tags can be removed to improve the page's usability.

Expected Behavior
On the Chapters page, the chapter names should not be clickable links if they are not intended to navigate to different chapters. Therefore, the anchor tags associated with the chapter names can be safely removed.

Screenshots
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/106438430/e6e2ef98-a3f5-47be-9c52-ab31c012405a)

Environment:
OS: Windows
Browser: Chrome
Version: 98.0.4758.102
Device: Desktop

**Comment by akshathar-navada** [comment]
Hey @VyjayantiN , actually we are working on creating separate pages for each college chapters, once it is done we will be linking it:)
