### ISSUE TITLE
Accessible and Inclusive Design Considerations

### ISSUE THREAD

**Issue by soumizde** [OSCode-Community/OSCodeCommunitySite#275]
### Current Behavior
As an UI/UX designer and a developer, the both the UI/UX of the project seems a bit off.

1. The carousel section or the 'Home' Section looks very cluttered especially with an image in the background.
2. The color scheme also seems to be off.  The choice to use different colors at different places of the project makes it look disjointed and off theme for the most parts.
3. The typing and the hovering animations seems to be too distracting

### Desired Behavior

Plan for the enhancement:

1. Do a proper branding and standardization of the design including typefaces, colour schemes, theme, pictures etc 
4. Design the whole Interface using visual design principles
5. Make animation usage related decisions if and when necessary 
6. Implement the design using code 
7. Make everything look professional and clean increasing accessibility and aesthetics. 

* I would be more than happy to provide figma mockups or even standardization guides as soon as you assign me the issue

### Screenshots / Mockups

I have added the concerns here and it helps to visualize the problem better. Please have a look at this.

 [Issue Visualizer](https://drive.google.com/file/d/1Ty2ywipLXSyHukX7lbZpLaMiutacMV-B/view?usp=sharing)

---

**Comment by akshathar-navada** [comment]
Hey @soumizde , thanks for stepping up!
Yes go ahead and try to improve this issue.
Open a PR with required screenshots, we will very happy to review and merge it:)
