### ISSUE TITLE
Add an on-hover animation to the statistics section.

### ISSUE THREAD

**Issue by abhinav-m22** [OSCode-Community/OSCodeCommunitySite#276]
### Current Behavior
Adding a hover animation on the statistics section components will improve the UI/UX of the web page.

### Desired Behavior
Add some CSS transitions/hover animations just like the other components

### Screenshots / Mockups
<img width="957" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/113239388/7ef24972-fd9f-49f1-aeaa-17cf16e4cd06">

---

I want to work on this feature.
Please assign me the task under GSSoC'23.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @abhinav-m22
