### ISSUE TITLE
Message us button not visible

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#279]
### Message button visibility
Message us button in footer section of webpage is not visible properly. Only border is visible. If we hover visibility changes. 

### Expected Behavior
I will change the font color to OS-Codes theme colour so it suits others

### Screenshots
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85272049/10bca3d6-c86b-4e54-bde4-a18bd0f56a84)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox

I'm a GSSoC-23 Contributor. Please assign me this issue.

**Comment by akshathar-navada** [comment]
Yes sure @engorgedspirit , go ahead!!
