### ISSUE TITLE
Improving events page UI

### ISSUE THREAD

**Issue by babitarit** [OSCode-Community/OSCodeCommunitySite#28]
![Screenshot (86)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/118760765/6bc339c1-708b-4a9c-8c8f-76310745eb6b)

as card width is too big as compare to its height its not looking soo nice i can improve it
please assign this to me

**Comment by akshathar-navada** [comment]
Yes sure!! @babitarit

**Comment by babitarit** [comment]
please assign it to me so that i can start working

**Comment by AMAN-BAGADIYA** [comment]
> Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.😇

**Comment by akshathar-navada** [comment]
> > Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> > I will try to make it as different as possible and exciting also.
> > Please assign it to me. Thank you in advance.😇

Hey @AMAN-BAGADIYA ,thanks for stepping up. As this project is open source, u can open a PR. We will be happy to review and merge the request!!
