### ISSUE TITLE
Pricing panel

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#281]
### Current Behavior
Nowhere in the whole page it is mentioned that joining OS-code is completely free of cost. If you add that information the page itself instead of google form, it will be much more motivating factor to students to go to register.

Im a GSSoC contributor. Please assign me this issue I will resolve it.
---

**Comment by engorgedspirit** [comment]
We can add Join Us link in nav bar, and to the point where it leads we can add there is no fee to pay to join, which is a great usp so that more users will engage with the platform. This also solves the problem of finding join us as it will be highlighted in nav bar instead of searching whole page

**Comment by akshathar-navada** [comment]
I have mentioned this in issue #282 , please check. And in the google form , it is specified that it is FREE!!!!
