### ISSUE TITLE
Join Us navigation

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#282]
Adding join us in top navigation bar would be useful to easily navigate towards that link instead of searching the whole page.
If we just add join us anchor to this navigation bar, viewers can easily navigate towards join us, which is most important for the community and almost each and every one will look for, so this should a high priority.
I'm a GSSoC contributor. Please assign me this issue

---

**Comment by akshathar-navada** [comment]
Sounds good @engorgedspirit . Instead of creating separate link in the navbar, try changing the GET STARTED button to JOIN US and that directing to the google form link directly. 
We would be happy, if you change this:)

**Comment by engorgedspirit** [comment]
I have a different opinion here, get started could give a little different meaning than join us. In a case that I directly want to join community I would be searching for "Join us" or something like that. I felt "Get started" would give more of a get to know us better kind of meaning. And I still feel that "Join Us" should be in navigation bar also in footer "Useful section" to easily accessible from anywhere from the site

**Comment by akshathar-navada** [comment]
> I have a different opinion here, get started could give a little different meaning than join us. In a case that I directly want to join community I would be searching for "Join us" or something like that. I felt "Get started" would give more of a get to know us better kind of meaning. And I still feel that "Join Us" should be in navigation bar also in footer "Useful section" to easily accessible from anywhere from the site

Hey @engorgedspirit , even I told the same. Instead of getstarted ,change that to join us :)
But don't need to link that in navabr, add that in home screen in place of get started. I think u got it!
If there is any queries , pls reach out us
