### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#283]
There are lot of mistakes in privacy policy. Grammatical mistakes and punctuations. 
I'm a GSSoC contributor and I will correct them for you. Assign me  this issue

**Comment by akshathar-navada** [comment]
Hey @engorgedspirit , thanks for stepping up. 
The thing is ,the privacy page content is auto-generated, so let that be as it is for now.
If we require any changes in future, we will surely let uk:)
