### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#284]
Navigation bar UI could be better. Needs more padding and font size is smaller than recommended web specifications. Also could be better with readability.
I'm a GSSoC contributor, please assign me this issue

**Comment by akshathar-navada** [comment]
Yes go ahead @engorgedspirit . Open a PR with required screenshots. We will soon review and merge it!!

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by pjyoti121** [comment]
please assign me this issue
