### ISSUE TITLE
Developing page issue

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#285]
Many links in the page not working or redirecting to home, that is a very big problem for readability, users will be redirected to home page or somewhere else they don't want. 
I'm a GSSoC contributor. Please assign me this issue I will add a popup or a new page saying this site is under development stay with us for further updates.

**Comment by engorgedspirit** [comment]
Services
Our services(footer): Web Design, Web Development, App Development
College chapters 
Last Icon here 
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85272049/09d7aba0-8ac7-4610-a673-e5b0f911e0c9)
There can be some more. All these links can be redirected to a developing page or a popup then redirect to same page so that experience wont be disturbed

**Comment by akshathar-navada** [comment]
> Services Our services(footer): Web Design, Web Development, App Development College chapters Last Icon here ![image](https://user-images.githubusercontent.com/85272049/240366507-09d7aba0-8ac7-4610-a673-e5b0f911e0c9.png) There can be some more. All these links can be redirected to a developing page or a popup then redirect to same page so that experience wont be disturbed

Hey, those services links should be added. Working in progress.
Blog page is created through hashnode, so we can't give access to everyone
Thank you!
