### ISSUE TITLE
SEO and accessibility

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#288]
SEO of the site is poor and when I evaluated this site in web accessibility tools I got the below result
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85272049/0c667f5b-bed6-4c33-a098-f4ee4feb3b6c)
I'm a GSSoC contributor, please assign me this issue. I will improve SEO as well as accessibility of the site as both of them go hand in hand
The following is SEO analysis
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85272049/33daab73-322c-48ee-98f7-6b935c393202)

**Comment by NishitKhamesra** [comment]
I would also like to contribute towards fixing this issue, 
Kindly also assign me this issue along with @engorgedspirit , in order to fix it in an efficient manner.
Kindly assign it under GSSoC'23.
