### ISSUE TITLE
Inconsistent Alignment of Components within Card Elements

### ISSUE THREAD

**Issue by premsaivarmachekuri** [OSCode-Community/OSCodeCommunitySite#29]
Hello, I would like to address an issue regarding the inconsistent alignment of components within card elements. As part of my contribution to GSSOC 23, I am keen to resolve this issue by utilizing CSS.

The problem arises from the unequal positioning of components within the card, resulting in an unbalanced visual presentation. To rectify this, I propose implementing a CSS solution that will ensure equal alignment of components within the card. By employing appropriate CSS properties, such as flexbox or grid, we can achieve consistent and visually pleasing card layouts.

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110842297/8c1c1b11-8287-4156-b904-394dd469194e)

I kindly request you to assign me this issue so that I can proceed with implementing the necessary CSS changes. With my expertise in front-end development and a focus on delivering high-quality user experiences, I am confident in resolving this issue effectively.

Thank you for your attention, and I look forward to your response.

Best regards,
Premsai Varma

**Comment by akshathar-navada** [comment]
Hey buddy thanks for stepping up yea try to fix the issue and as this is a Open source project you can pull a request at any time we would be happy to merge it
Thank you! @premsaivarmachekuri

**Comment by akshathar-navada** [comment]
Hey buddy, the screenshot which is added is not related to the project in which we are working on. 
Thank you for reaching us! @premsaivarmachekuri
