### ISSUE TITLE
Improving the display of website.

### ISSUE THREAD

**Issue by SrishtiSonam** [OSCode-Community/OSCodeCommunitySite#292]
### Description
1. Reducing the opacity of starting-display page background to increase readability.
<img width="498" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/113123593/d02b2182-2a86-4aa1-83ee-f2f6dfcddcab">
2.And some contrast issue.
<img width="474" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/113123593/f09e46b0-1d85-46ed-ba63-dcc1ccedd45a">
3.Message us button not visible.
<img width="141" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/113123593/98fdd562-cc73-4e5c-b5e7-07527a20b031">

### Expected Behavior
These problems can be solved by some changes in CSS.

### Screenshots
If you find me suitable for any other improvement in the website.
Assign this issue to me under Gssoc'23.

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Hey @SrishtiSonam , tahnks for stepping up!
I have already assigned the issue in msg me button, so u can work on the contrast issue:)

**Comment by SrishtiSonam** [comment]
Thank you for your response and providing me this opportunity.

Regards
Srishti

**Comment by pjyoti121** [comment]
please assign me this issue
