### ISSUE TITLE
On Blog Page : Changing the logo image in header part (in browser tab section)

### ISSUE THREAD

**Issue by NishitKhamesra** [OSCode-Community/OSCodeCommunitySite#293]
### Description

In the Blog page's head part (tab section of the browser), currently we are having logo image as square.

### Screenshots

![issue2](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/91678454/8f80170f-9baa-4f83-be5c-154f4f8d034a)

### Fixing Issue
We can change it too circular shape for better visibility and to make it look standard.

------
I would like to worm on this issue.
Kindly assign this issue to me , under GSSoC'23.

**Comment by akshathar-navada** [comment]
Hey @NishitKhamesra , actually we are creating the blog page through hashnode. So we won't be able to give access to everyone. If u want to work on this, pls ping me up!!!
