### ISSUE TITLE
On main page : In Testimonials can make transitions and looks better

### ISSUE THREAD

**Issue by NishitKhamesra** [OSCode-Community/OSCodeCommunitySite#294]
### Description

On main page , In Testimonials transitions are too fast , also before hovering images are popped up and hovering over the images the sink down and it doesn't look cool.

### Expected Behavior

We can make transitions smoother.
Additionally, we can also change the image behavior (under testimonials) , like making it normal before having and then on hovering popping it up.
### Screenshots

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/91678454/ca60bf9e-07e6-413f-8a32-48426b6c3aad

----------------

**Comment by akshathar-navada** [comment]
Yea, sounds good @NishitKhamesra , pls go ahead and resolve the issue!!

**Comment by pjyoti121** [comment]
please assign me this issue
