### ISSUE TITLE
Events Page : Image Responsiveness Issue on Inscpecting the webpage  

### ISSUE THREAD

**Issue by NishitKhamesra** [OSCode-Community/OSCodeCommunitySite#296]
### Description

On Events page, while inspecting, on resizing the inspection window the images are not getting resized in an elegant manner.

### Expected Behavior

The images should smoothly get resized when resizing the inspection window.
### Screenshots

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/91678454/59f393aa-382f-4ce5-8f48-4dc9fc3c282e

------------------
I would like to work on this issue , kindly assign it to me under GSSoC'23.

**Comment by akshathar-navada** [comment]
Yes sure @NishitKhamesra , pls go ahead!!

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
