### ISSUE TITLE
📝 DOCS: add steps for installation in README.md

### ISSUE THREAD

**Issue by peb-peb** [OSCode-Community/OSCodeCommunitySite#3]
[This](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/README.md#%EF%B8%8F-installation) needs to be Updated.

**Comment by ShivendraTrivedi** [comment]
Hey there! I noticed the open issue "DOCS: Add steps for installation in README.md" in the OSCodeCommunitySite repository. I would like to take on this task and add the installation steps to the README.md file. Could you please assign this issue to me? I'm excited to contribute and help improve the project's documentation. Thanks!

**Comment by vinitvijal** [comment]
I would like to work on it under GSSOC

**Comment by utkars3** [comment]
Hey @peb-peb i would like to work on this issue.Could you please assign this issue to me and add the gssoc tag there

**Comment by vinitvijal** [comment]
I have made changes and created a pull request please have a look

**Comment by akshathar-navada** [comment]
@ShivendraTrivedi ,Hey buddy thanks for stepping up yea try to alter it and as this is a Open source project you can pull a request at any time we would be happy to merge it
Thank you!

**Comment by hustler0109** [comment]
I want to contribute to this! #gssoc
