### ISSUE TITLE
Lack of Responsive Design for Elements in the Navbar

### ISSUE THREAD

**Issue by premsaivarmachekuri** [OSCode-Community/OSCodeCommunitySite#30]
The current implementation of the navbar lacks responsive design, resulting in elements not adapting effectively to different screen sizes. This inconsistency compromises the user experience and requires improvement.

To address this issue, I plan to contribute to the project as part of GSSOC23 and implement responsive design for the elements in the navbar using CSS. The goal is to ensure that the navbar adapts seamlessly to various screen sizes, providing a consistent and user-friendly experience across devices.

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110842297/2831f8cc-86fa-421a-9c05-09ac7c65d531)

I kindly request to be assigned this issue in order to work on implementing the responsive design for the navbar elements using CSS.

Thank you for your attention to this matter. I am excited to contribute to the project and enhance the user experience through responsive design for the project.

Best regards,
Premsai Varma

**Comment by akshathar-navada** [comment]
Yes sure, open a PR , we will review it! @premsaivarmachekuri

**Comment by akshathar-navada** [comment]
Hey buddy, the screenshot which is added is not related to the project in which we are working on.
Thank you for reaching us! @premsaivarmachekuri
