### ISSUE TITLE
OS-Code Logo and meta description

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#301]
When i search OS-Code in gogle I get below image
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85272049/81bffc60-bf54-47b9-bdc9-24aeca46e8c8)
Here OS-Code logo should be added instead of default logo 
And meta description could be better(which can be considered for other issue I mentioned in SEO)
I'm a GSSoC contributor and please assign me this issue.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @engorgedspirit

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by akshathar-navada** [comment]
Yeah sure, go ahead @sagnik-p

**Comment by sagnik-p** [comment]
Done!
Please check this PR #692 
Thanks
