### ISSUE TITLE
 Adding a smooth transition effect in hamburger icon of navbar in mobile view

### ISSUE THREAD

**Issue by abhiruchisarswat** [OSCode-Community/OSCodeCommunitySite#303]
### Current Behavior

I want to add a smooth transition effect in the navbar in the mobile view.

### Desired Behaviour :
Sample -->

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/113445604/51fe4350-d92d-4fed-a4d7-88993d28008e

This would improve the UI and user experience of the website. 
Please assign me the task under Gssoc'23.

**Comment by akshathar-navada** [comment]
Ya nice @], go ahead and try to enhance it:)

**Comment by abhi03ruchi** [comment]
Hi @akshathar-navada , I by mistake used my redundant GitHub id for requesting this task, @abhi03ruchi is my official GitHub Id through which I am contributing in Gssoc '23. Please assign this task to me via this id.
Sorry, for the inconvenience.

**Comment by akshathar-navada** [comment]
> Hi @akshathar-navada , I by mistake used my redundant GitHub id for requesting this task, @abhi03ruchi is my official GitHub Id through which I am contributing in Gssoc '23. Please assign this task to me via this id. Sorry, for the inconvenience.

Oh okay, no worries, will add this ID:) @abhi03ruchi

**Comment by abhi03ruchi** [comment]
<img width="658" alt="Screenshot 2023-05-24 at 9 57 54 PM" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/105661636/62ada3a2-2747-4d66-9560-295ddb654c78">

While doing **npm start** to view the site, I am getting this error. Plz, look into the matter.

**Comment by akshathar-navada** [comment]
> <img alt="Screenshot 2023-05-24 at 9 57 54 PM" width="658" src="https://user-images.githubusercontent.com/105661636/240671735-62ada3a2-2747-4d66-9560-295ddb654c78.png">
> While doing **npm start** to view the site, I am getting this error. Plz, look into the matter.

Ohhh. Okay, you better unfork the repo and try forking it again. And instead of running npm start, directly go live (i.e, localhost 5000) . Try by doing this, if u are unable to make changes still, please feel free to reach us:)
