### ISSUE TITLE
Chapters Page: Nav bar

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#305]
Nav bar in chapters page is not working, redirecting in same page.

**Comment by akshathar-navada** [comment]
Yes @engorgedspirit , we want to maintain that to be linked in the same page. Don't need to link everyhting to the main page

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by tripathishipra** [comment]
I am interested in contributing to this project. Can you please assign me this issue?@akshathar-navada

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by akshathar-navada** [comment]
This issue has been resolved , so will be closing this!
