### ISSUE TITLE
[GSSOC'23]  -  Improper working of Navbar of Chapter Tab

### ISSUE THREAD

**Issue by VyjayantiN** [OSCode-Community/OSCodeCommunitySite#311]
Description
The navigation bar tabs are incorrectly highlighted when the user is on the Chapters page. Specifically, when visiting the Chapters page, the "Home" tab in the navigation bar is highlighted instead of the "Chapters" tab.

Expected Behavior
When the user is on the Chapters page, I expect the "Chapters" tab in the navigation bar to be highlighted to indicate the current active page.

Please check out this Screenshot!!
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/106438430/ba9f8b47-637b-4ccc-825c-ca271846829d)

**Comment by VyjayantiN** [comment]
Could you please assign me this issue under GSSOC'23!!

**Comment by Git21221** [comment]
@VyjayantiN In a latest update someone changed it. please pull all recent updates.
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/644378d6-82af-4f30-ba35-ecffa4b2c28f)

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @VyjayantiN

**Comment by VyjayantiN** [comment]
@Git21221 That issue is fixed but the active tab is not being highlighted and the navbar links like home etc. are not redirecting to respective pages. I will fix them.

**Comment by Git21221** [comment]
@VyjayantiN sure bro. That will be a nice work.
