### ISSUE TITLE
[Docs] Improving the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [OSCode-Community/OSCodeCommunitySite#312]
I would like to be assigned for GSSOC'23 for this issue

Suggestions:
+ Restructuring the header for a more visually appealing look
+ formatting text in a better manner
+ adding badges for a cool effect
+ other minor changes

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @the-amazing-atharva

**Comment by the-amazing-atharva** [comment]
Working on it now!
