### ISSUE TITLE
Chapters Page 

### ISSUE THREAD

**Issue by Moumita2002** [OSCode-Community/OSCodeCommunitySite#317]
### Description

Clicking on the college names in the chapters page is opening the same page again in a new tab.

### Expected Behavior

In that case, college names should be made non-clickable. 

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

Please assign me this issue under GSSoC'23.

**Comment by akshathar-navada** [comment]
Yes , go ahead @Moumita2002
