### ISSUE TITLE
[GSSOC'23] - Improper working of Navbar of Event

### ISSUE THREAD

**Issue by jayantajm1** [OSCode-Community/OSCodeCommunitySite#320]
### Description

The navigation bar tabs are incorrectly working when the user is on the Events page. Specifically, when visiting the Event page, the "Home" and "About " tab is not working .

### Expected Behavior
When the user is on the Events page and clicks the "Home" or "About" tab, I expect them to be redirected to the corresponding "Home" or "About" page. Additionally, the tab in the navigation bar should be highlighted to indicate the current active page.

### Screenshots
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/90429653/cc8c860c-a56b-468a-848e-d5141c41262b)

### Enviroment:
 - OS: Mac ,Linux, Windows
 - Browser: Chrome ,Safari, Firefox
 - Version: 
 - Device: Desktop ,Mobile
 please check this @OSCode-Community

**Comment by akshathar-navada** [comment]
Hey @jayantajm1 , thanks for stepping up!
I have already assigned this issue to someone else, if it is not resolved, then I will let uk.
If there is any other issue u would like to work on,pls go ahead
