### ISSUE TITLE
Enhance: Ui of chapters page

### ISSUE THREAD

**Issue by Pragati-3003** [OSCode-Community/OSCodeCommunitySite#321]
I would like to enhance the ui of the chapters page to make it more attractive. 
![IMG_20230524_012956](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132778037/319c09ab-ca75-4d84-b527-69af66e8a7ce)
So, please assign this issue to me under GSOC'23.

**Comment by akshathar-navada** [comment]
Yes sure @Pragati-3003 , Open a PR with required screenshots. We wil review and would be happy to merge it!

**Comment by Pragati-3003** [comment]
> Yes sure @Pragati-3003 , Open a PR with required screenshots. We wil review and would be happy to merge it!

Thanku you assigning this to me.

**Comment by Pragati-3003** [comment]
Please add level number to this issue. 
Thanking you.
