### ISSUE TITLE
Enhance : Ui of Join us section. 

### ISSUE THREAD

**Issue by Pragati-3003** [OSCode-Community/OSCodeCommunitySite#322]
I would like to enhance the ui of Join us section to make it more attractive. 
![IMG_20230524_013044](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132778037/74265fe3-a702-4313-8f52-bc72e4fde56f)
So, please assign this issue to me under GSSOC 23.

**Comment by akshathar-navada** [comment]
Yes sure @Pragati-3003 , Open a PR with required screenshots. We wil review and would be happy to merge it!

**Comment by Pragati-3003** [comment]
> Yes sure @Pragati-3003 , Open a PR with required screenshots. We wil review and would be happy to merge it!

Thanku , will attach the required screenshots.
