### ISSUE TITLE
Enhance : Ui of Why choose us section. 

### ISSUE THREAD

**Issue by Pragati-3003** [OSCode-Community/OSCodeCommunitySite#323]
I would like to enhance the ui of the Why Choose us section. 
![IMG_20230524_013020](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132778037/65ef64f9-217d-4468-9648-27942a1c48b4)
So, please assign this issue to me under GSSOC'23.

**Comment by akshathar-navada** [comment]
Yes sure @Pragati-3003 , Open a PR with required screenshots. We wil review and would be happy to merge it!

**Comment by Pragati-3003** [comment]
> Yes sure @Pragati-3003 , Open a PR with required screenshots. We wil review and would be happy to merge it!

Thanku :)
