### ISSUE TITLE
Enhance: Ui of the Contact Us section

### ISSUE THREAD

**Issue by Pragati-3003** [OSCode-Community/OSCodeCommunitySite#324]
I would like to change the existing ui of the contact us section to make it more attractive. 
![IMG_20230524_013845](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132778037/0afbe27e-712d-4541-be4b-8461621c2af3)
So, please assign this issue to me under GSSOC' 23.

**Comment by akshathar-navada** [comment]
Yes sure @Pragati-3003 , Open a PR with required screenshots. We wil review and would be happy to merge it!
Thanks for your interest in contributing to our repo:)

**Comment by Pragati-3003** [comment]
> Yes sure @Pragati-3003 , Open a PR with required screenshots. We wil review and would be happy to merge it! Thanks for your interest in contributing to our repo:)

Thanku for assigning this to me :)

**Comment by Pragati-3003** [comment]
Please add level no.  to this issue. 
Thanking you.
