### ISSUE TITLE
Fix the layout of 'FOOTER SECTION' in all pages 🔨

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#328]
### Current Behavior

![Screenshot (410)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/9383a37c-384c-48bc-a7d5-47fb186049df)

### Description

-- Reduce the gap between the social media icons.
-- Reduce the gap between the copyright and social media icons.
-- The PR should be responisve also.

### Points to be noted
-- Please give the brief desciption of the PR with required screenshots
-- Pull the repo properly and then make required changes:)
-- We will review it soon and would be very happy to merge your PR

**Comment by SJ-Kumar** [comment]
Hi,
I'm willing to work on this bug. Please assign this to me under GSSOC23.

**Comment by PoulavBhowmick03** [comment]
I can fix this issue. Can I be assigned?
@akshathar-navada

**Comment by akshathar-navada** [comment]
> Hi, I'm willing to work on this bug. Please assign this to me under GSSOC23.

Yes sure @SJ-Kumar ,pls go ahead!

**Comment by Git21221** [comment]
# After
## Large Screen
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/cfb4bea9-bdf2-46b6-85e9-a0603196375c)
## Medium Screen
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/5b709313-a85a-4f48-8641-2e3779b8220f)
## Small Screen
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/51d91af0-0c75-40ee-8346-9fbdb7737a66)
How is the look? @akshathar-navada
