### ISSUE TITLE
Change the background image in events page 

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#329]
### Current Behavior

![Screenshot (411)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/536f76db-d643-47b6-99a8-e3333298392e)

### Desired Behavior

As the present background image is not satisfying, please try to change that.
-- Either add a better background image which suits .
-- Or suggest any specific idea of how to make it look better.

### Points to be noted
-- Please give the brief desciption of the PR with required screenshots
-- Pull the repo properly and then make required changes:)
-- We will review it soon and would be very happy to merge your PR

## Happy coding 🤩

---

**Comment by PoulavBhowmick03** [comment]
I would like to work on this. Can you assign this to me? @akshathar-navada

**Comment by akshathar-navada** [comment]
Yes sure @PoulavBhowmick03 , please go ahead
