### ISSUE TITLE
Navbar not working properly

### ISSUE THREAD

**Issue by trisharaj06** [OSCode-Community/OSCodeCommunitySite#331]
### Description
 After navigating to the event section Home and About menu bar is not working, could you assign this issue to me under gssoc'23.

![Screenshot (725)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/109025651/5a018d5e-6daf-4883-9f4e-167376e4c0b3)

**Comment by akshathar-navada** [comment]
I have already assigned this issue to someone. If there is any other u would like to work on , please let us know
