### ISSUE TITLE
Adding navbar to blog section

### ISSUE THREAD

**Issue by trisharaj06** [OSCode-Community/OSCodeCommunitySite#332]
It would  be better if we add navbar to the blog section too, kindly assign this to me.

![Screenshot (726)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/109025651/fa725eb5-f33b-455c-83f4-69166c998cd5)

**Comment by akshathar-navada** [comment]
We are currently creating the blog page using hashnode, so we won't be ableto give access to everyone!
