### ISSUE TITLE
New Footer Look (just check)

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#337]
# After
## Large Screen
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/cfb4bea9-bdf2-46b6-85e9-a0603196375c)
## Medium Screen
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/5b709313-a85a-4f48-8641-2e3779b8220f)
## Small Screen
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/51d91af0-0c75-40ee-8346-9fbdb7737a66)
How is the look? @akshathar-navada

**Comment by akshathar-navada** [comment]
Awesome @Git21221 , please open a PR, we would be happy to merge it!
