### ISSUE TITLE
Navbar and Landing Page Enhancement ⭐ 

### ISSUE THREAD

**Issue by amanjaiman1** [OSCode-Community/OSCodeCommunitySite#345]
### Current Behavior
this version have not proper fonts , professional UI.

### Desired Behavior
Will change complete navbar with ultimate good looking UI and change fonts family in Landing page

### Screenshots / Mockups
You will check my PR, there you can judge

---

**Comment by akshathar-navada** [comment]
Sure, go ahead @amanjaiman1

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by amanjaiman1** [comment]
I am already doing this please don't overthink

**Comment by pjyoti121** [comment]
please assign me this issue
