### ISSUE TITLE
FAQs New Feature updation

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [OSCode-Community/OSCodeCommunitySite#348]
### Current Behavior

1. In the present FAQ section, there is nothing so much like there is FAQ then questions and solution are there. Not a good UI . 
1. Lack of Extra question (new question if anyone want to ask ??).

### Desired Behavior

We can add a better UI like - Card system where FAQ and Q's parts will have a different cards and if someone has more question which is not present in FAQ section then what?
So, we can make a card system + add a another section along with that where there will be form type where user can ask a question if the question is not present in FAQ.

### Screenshots / Mockups
<img width="960" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/94108574/92043c07-bb16-4c58-b72d-1dec16b4ab1a">

Please assign me this issue under GSSoC '23 as a contributor. 
---

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @Rupantar-Borphukan

**Comment by Rupantar-Borphukan** [comment]
> Yes sure , go ahead @Rupantar-Borphukan

ok
