### ISSUE TITLE
Improve Navbar Links Design to Make it Responsive

### ISSUE THREAD

**Issue by Geeta259** [OSCode-Community/OSCodeCommunitySite#35]
![Screenshot (226)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/75520947/42969f18-c0b9-40fb-ae36-7404c41cbb28)

Want to work on navbar links to make it responsive and improve UI .

Want to contribute this project under GSSoC'23

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I want to improve Navbar Links Design to Make it more Responsive. I want to work on this issue.
![SharedScreenshot](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93476373/a3abca70-451c-4473-b622-ea5e774e972e)
From Blog Page we can't go to the Home Page(Main Page). I will fix this.
![Screenshot 2023-05-20 181724](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93476373/ab5b7298-b744-41f3-ac46-218a8dacbd7a)
This navbar is not looking good.

Please assign me this issue

**Comment by adityavpawar** [comment]
Please assign me this issue to me

**Comment by akshathar-navada** [comment]
> ![Screenshot (226)](https://user-images.githubusercontent.com/75520947/239687436-42969f18-c0b9-40fb-ae36-7404c41cbb28.png)
> 
> Want to work on navbar links to make it responsive and improve UI .
> 
> Want to contribute this project under GSSoC'23

Yes go ahead!! @Geeta259

**Comment by ARGHYADIPROY** [comment]
Please assign me this issue , I want to work on this issue under the GSSoC'23.

**Comment by Geeta259** [comment]
> > ![Screenshot (226)](https://user-images.githubusercontent.com/75520947/239687436-42969f18-c0b9-40fb-ae36-7404c41cbb28.png)
> > Want to work on navbar links to make it responsive and improve UI .
> > Want to contribute this project under GSSoC'23
> 
> Yes go ahead!! @Geeta259

Yes ! I am working on it . Please add GSSOC'23 label too.

**Comment by akshathar-navada** [comment]
Open a PR, we will review it and add the label soon.
Thank you!

**Comment by Geeta259** [comment]
I made a PR  ! check it @akshathar-navada

**Comment by akshathar-navada** [comment]
Yes sure!
