### ISSUE TITLE
responsiveness of buttons in contact us

### ISSUE THREAD

**Issue by avneet-singh843** [OSCode-Community/OSCodeCommunitySite#353]
### Description
Buttons are not responsive. 

### Expected Behavior
Size of buttons should get smaller

### Screenshots
<img width="252" alt="Screenshot 2023-05-24 192602" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96073704/f0827574-b45e-4414-a45c-813b8559cba4">

Assign this Issue to me under GSSOC'23

**Comment by akshathar-navada** [comment]
@avneet-singh843 It is responsive, there might be minor issue tho. You have just minimzed it much. Check properly!
