### ISSUE TITLE
Header Overlaping

### ISSUE THREAD

**Issue by avneet-singh843** [OSCode-Community/OSCodeCommunitySite#354]
### Description
Header and body overlaping

### Screenshots
<img width="253" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96073704/1d5934a9-5979-49ca-8dcb-15dde8c7c0b7">

I'll be happy to help, assign this issue to me under Gssoc'23

**Comment by akshathar-navada** [comment]
@avneet-singh843 It is not overlapping, kindly check

**Comment by avneet-singh843** [comment]
"A community of learners" is missing at Mobile dimensions small and medium, working properly for mobile large
<img width="329" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96073704/60c3e169-142e-47e5-9dc4-db2e271231bb">
