### ISSUE TITLE
Add Readme File 

### ISSUE THREAD

**Issue by swarnade** [OSCode-Community/OSCodeCommunitySite#355]
Want To modify Readme File

**Comment by akshathar-navada** [comment]
Please tell us, how you are actually gonna do that. Like what do you want to modify?

**Comment by swarnade** [comment]
@akshathar-navada  I Want To Include All The Details Of Website Into It

The Navigation Part, Pages And all Stuffs

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @swarnade
