### ISSUE TITLE
EVENT Page enhancement ✨

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#358]
I will make event section the best look. Current look is not matching with other pages in the website. I can't provide any screenshot for now, but I will work on it.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Git21221 . We are waiting for you to enhance it !

**Comment by akshathar-navada** [comment]
Hello buddies, 'EVENT PAGE" is currently under development.

@Git21221 is trying to enhance it ,so currently the event page is under work. If any one wants to join and make this page better by giving some ideas to him are most welcomed!!

Thank you 🙂

**Comment by Git21221** [comment]
Thanks, I will update some changes and everyone can comment if it is looking good or not

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by Git21221** [comment]
Event page is redesigned @akshathar-navada. And now it needs to be responsive so I will again work on it.

**Comment by akshathar-navada** [comment]
> Event page is redesigned @akshathar-navada. And now it needs to be responsive so I will again work on it.

Yes , go ahead @Git21221 🤩

**Comment by Git21221** [comment]
@akshathar-navada now this issue can be closed. Waiting for further improvement of event section.
