### ISSUE TITLE
Heading style is not consistent

### ISSUE THREAD

**Issue by Soyeb01** [OSCode-Community/OSCodeCommunitySite#359]
### Description
Heading and underline are not consistent for the section "Numbers says it all" with all other sections for big screen like computer.
Also, for the small screen like mobile.

### Expected Behavior
It should be aligned center with its underline. It should be consistent for its brand and style.

## Big screen 
![www oscode co in_](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98175646/00ef8a24-fe38-4403-ab93-21631b094333)
## Small screen
![www oscode co in_(iPhone SE)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98175646/01bb4366-496a-4bcb-bd5a-048060801a1a)
![www oscode co in_(iPhone SE) (1)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98175646/3377eb9e-2eeb-43b3-bb3a-af3bef7375b7)

### Enviroment:
 - OS:  Windows
 - Browser: Chrome
 - Device: Desktop Mobile

**Comment by Soyeb01** [comment]
I would like to work on this issue under GSSoC'23, please do assign me.

**Comment by akshathar-navada** [comment]
@Soyeb01 We have put that in a way ,where if the text is aligned to left then from there the line begins, if the text is at center, then the line is also. And it is responsive in small screen also. If there is any other issue, u would like to work on, pls go ahead!
