### ISSUE TITLE
Changing the image at "https://www.oscode.co.in/chapters/chapter.html"

### ISSUE THREAD

**Issue by Sathvik902** [OSCode-Community/OSCodeCommunitySite#36]
I have noticed that the image is kinda blurry as well as the heads are cut off.

@akashgreninja @ng169 @FuryACE007 @rashi2911 @akshathar-navada ,
I would love to contribute to the issue as a part of @GSSOC'23. Please assign it to me.
I am a 3rd year student (6th sem) at BIT. Thank you.

**Comment by akshathar-navada** [comment]
Hey @Sathvik902 !!, thanks for stepping up.  Either fix the current image or try to add a better one.
As this is a Open source project you can pull a request at any time we would be happy to merge it.

**Comment by Sathvik902** [comment]
Sure Thank you!

**Comment by Sathvik902** [comment]
Also, Please add GSSOC label as I am contributing under it. Thanks.

**Comment by akshathar-navada** [comment]
> Also, Please add GSSOC label as I am contributing under it. Thanks.

We will be adding it soon. Please open a PR ,we will review it and merge it soon!

**Comment by Sathvik902** [comment]
Opened a PR. Thanks.
