### ISSUE TITLE
improving the ui of event page

### ISSUE THREAD

**Issue by lakhan06** [OSCode-Community/OSCodeCommunitySite#361]
### Current Behavior

the current ui of event page is not good .the layout of page is not good.

### Desired Behavior

I want to improve the layout which will be done using flexbox and and align the events in a proper order

### Screenshots / Mockups

---

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @lakhan06 . Try to give it a better look!

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by akshathar-navada** [comment]
Event page enhancement is pinned in the issue section, so will be closing this isssue. If there is any improvements u guys would like to make , can discuss in the pinned issue.
Thank you!
