### ISSUE TITLE
Changes in navbar

### ISSUE THREAD

**Issue by AdityaLahane-2003** [OSCode-Community/OSCodeCommunitySite#37]
- On clicking Chapters position of 'Blogs' and 'Chapters' is changing.
- On clicking Events it's disappearing from the navbar when we're on the Events page. 

**Please assign me this issue, I want to contribute to it as a part of GSSoC'23.** 
At Home -
![n1](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108022893/e855d6d1-271e-452d-8db4-58e5433b8bac)
On Chapters Page -
![n2](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108022893/3f704113-3afd-4736-bbba-55b7e71b4cea)
On Events Page - 
![n3](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108022893/644765a4-e7c1-439a-95ce-e3adabacd99f)

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by akshathar-navada** [comment]
> * On clicking Chapters position of 'Blogs' and 'Chapters' is changing.
> * On clicking Events it's disappearing from the navbar when we're on the Events page.
> 
> **Please assign me this issue, I want to contribute to it as a part of GSSoC'23.** At Home - ![n1](https://user-images.githubusercontent.com/108022893/239689040-e855d6d1-271e-452d-8db4-58e5433b8bac.jpg) On Chapters Page - ![n2](https://user-images.githubusercontent.com/108022893/239689047-3f704113-3afd-4736-bbba-55b7e71b4cea.jpg) On Events Page - ![n3](https://user-images.githubusercontent.com/108022893/239689049-644765a4-e7c1-439a-95ce-e3adabacd99f.jpg)

Yes sure, go ahead !!! @AdityaLahane-2003

**Comment by AdityaLahane-2003** [comment]
Thank you ! 
For assigning me this issue ! 
@akshathar-navada

**Comment by Sathvik902** [comment]
Please assign this to me..I would love to contribute to the community under @GSSOC'23 Thanks.
