### ISSUE TITLE
Fix the YOUTUBE icon in the footer section

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#372]
### Description
-- The youtube icon in the footer section is differnt from other social media icons in every page.
-- There is no hovering effect added to youtube icon.

### Expected Behavior

-- Fix the position of it, which should match with other socail media icons beside it.
-- Also add hovering effect similar to other social media icons

### Screenshots

![Screenshot (420)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/4237b071-1702-435a-b167-03abe9da98b9)

### Points to be noted
-- Please give the brief desciption of the PR with required screenshots
-- Pull the repo properly and then make required changes:)
-- We will review it soon and would be very happy to merge your PR

**Comment by akshathar-navada** [comment]
Yes sure @TikuGaelle , go ahead!!

**Comment by Developer-Swati** [comment]
@akshathar-navada  please assign this issue to me. I have knowledge of Html , Css ,  and Js . I am a GSSOC contributor.
Thanks
