### ISSUE TITLE
[NEW]: want to add light mode design 

### ISSUE THREAD

**Issue by Ks103** [OSCode-Community/OSCodeCommunitySite#375]
### Current Behavior
Light mode makes website more attractive.

### Desired Behavior
As a designer I want you to please assign me this task so that I can start working on the design.

### Screenshots / Mockups

![Screenshot 2023-05-25 110821](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/86292101/a5db221b-6656-42fe-9196-9412cca661f2)

---

**Comment by akshathar-navada** [comment]
Yes sure @Ks103 , open a PR with required screenshots, we will soon review it!! and would be happy to merge you PR:)
