### ISSUE TITLE
Chapters page active link

### ISSUE THREAD

**Issue by TikuGaelle** [OSCode-Community/OSCodeCommunitySite#377]
### Description
When on the chapters page, the About link on the navbar is shown to be active, instead of the Chapters link

### Expected Behavior
 The active link should be Chapters on the navbar while on the chapters page

### Screenshots
* Desktop
 <img src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/60433438/b8a805e1-4e4c-4e7a-a042-9e9f408aca43" width="900" height="700"> 

* Mobile
<img src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/60433438/9222c31f-dec8-4f9a-9106-d05329b02a24" width="500" height="700"> 

### Enviroment:
 - OS:   Windows
 - Browser: Chrome  
 - Version: 
 - Device: Desktop  Mobile

**Comment by TikuGaelle** [comment]
Please @akshathar-navada  assign this issue to me

**Comment by akshathar-navada** [comment]
Hey @TikuGaelle , thanks for stepping up!
![Screenshot (44)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/88f3b64c-95f1-4429-9ab6-7b4ef0a62f37)
Please  check this out, the active link is to chapters itself, only the white active link shoul be changed to purple as normal. 
This issue I have raised. If there is any other issue u would like to work on, pls go ahead!
Thank you!!
