### ISSUE TITLE
scaling issue in the event page 

### ISSUE THREAD

**Issue by Meenakshiratnawat** [OSCode-Community/OSCodeCommunitySite#38]
Images on the event page are not properly scaled ,I can fix it ,I am a Gssoc contributor ,kindly assign me the issue

**Comment by shramanpaul** [comment]
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by akshathar-navada** [comment]
> Images on the event page are not properly scaled ,I can fix it ,I am a Gssoc contributor ,kindly assign me the issue

Yes sure, go ahead! @Meenakshiratnawat

**Comment by Meenakshiratnawat** [comment]
thank you  @akshathar-navada  for assigning me this issue

**Comment by akshathar-navada** [comment]
> I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

Hey @shramanpaul , even u can try to resolve this issue:)
