### ISSUE TITLE
make go to top button beautiful

### ISSUE THREAD

**Issue by Abhiramjampani** [OSCode-Community/OSCodeCommunitySite#381]
### Description

in go to top button arrow we the arrow mark is not  in the center of button

### Expected Behavior

in go to top button arrow we the arrow mark should be in the center of button
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Yes , please fix it @Abhiramjampani

**Comment by akshathar-navada** [comment]
I think now it is fixed. SO, would be closing this issue. If there is anything else, u would like to work on, pls go ahead!
