### ISSUE TITLE
rework on bottom of website and faq section

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#382]
# Before
![WhatsApp Image 2023-05-25 at 6 06 59 PM](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/7198ed5a-0fe7-4f05-bec7-2e27df3d4136)
# After
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/28aaadec-5e0e-4de0-9417-679869cd9b6d)

**In my opinion I like first faq section.**
Why I don't Like new faq section?

> 1.  The design doesn't match the theme color of OS-CODE.
> 2.  Expand section is not working.
> 3.  Font size is extraordinarily high.
> 4.  Font-family is not matching with it's own font.

**Comment by akshathar-navada** [comment]
Yes @Git21221 , The + button is also not expandable. Please fix it. Change that to previous one. 
Thank you!

**Comment by Git21221** [comment]
It is reverted now. So can I delete this now?

**Comment by akshathar-navada** [comment]
If there is any other issues that u would like to resolve, please go ahead @Git21221 .
I will be closing this issue!
