### ISSUE TITLE
Make the accomplishment section responsive

### ISSUE THREAD

**Issue by mohammadshaad** [OSCode-Community/OSCodeCommunitySite#383]
### Current Behaviour
The "Our Accomplishment" section doesn't look good in smaller screens. The text and the images are overriding. 

### Desired Behaviour
The text and image should come one below each other

### Screenshots / Mockups
<img width="314" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/89409389/8758d937-32ef-4765-b57b-0975ab1d1555">

## Additional Information
I am a GSSoC'23 contributor so kindly assign me this issue

**Comment by akshathar-navada** [comment]
Hey @mohammadshaad , thanks for stepping up. I don't think this issue exist now. If there is any other thing, which u would like to work on , please go ahead!!

**Comment by mohammadshaad** [comment]
Thanks a lot
