### ISSUE TITLE
"Numbers say it all!" Section Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [OSCode-Community/OSCodeCommunitySite#385]
### Current Behavior
The current design of "Numbers say it all!" section is nice but it can be improved by making some design adjustments. Through making some changes, I can make it even better.

### Screenshots / Mockups

**Current Design**

![oscode (2)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115794049/9aec38ad-c90d-489c-8331-3754cca3f743)

**Expected Updated Design**

![oscode (1)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115794049/f6cad7ba-1e12-4f8b-97c2-3137b0a88280)

**Comment by iamRabia-N** [comment]
I want to work on this issue as a part of GSSOC-23.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @iamRabia-N

**Comment by iamRabia-N** [comment]
@akshathar-navada Kindly add the level in the issue which is mentioned in the merged pull request.
The merged pull request is mentioned below:
Updated Design of "Numbers say it all!" #390

**Comment by akshathar-navada** [comment]
Sorry, didn't see
