### ISSUE TITLE
Improve message me section as it takes up lot of space.Please assign this to me under GSSOC'23

### ISSUE THREAD

**Issue by silwite** [OSCode-Community/OSCodeCommunitySite#39]
Hello , Please assign me this issue as contributor under GSSOC'23 . I would like to work on it.
Tech Stack - MERN stack

**Comment by shreya26-bit** [comment]
I would like to work on this issue , Please assigned this issue to me

**Comment by peb-peb** [comment]
Sure @silwite ! Go ahead with this issue.

**Comment by silwite** [comment]
I have created a pull request . Please have a look at it
