### ISSUE TITLE
footer old vs new

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#391]
# Old
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/08b032f1-63f1-403f-b959-0276346d7948)
# New
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/b358f4c7-fc46-44cd-b051-b7d159cec621)

**Comment by iamvbenz49** [comment]
i would like to work on this issue

**Comment by Git21221** [comment]
@iamvbenz49 which one do you like?

**Comment by iamvbenz49** [comment]
new one with copyright section aligned to the center

**Comment by Git21221** [comment]
yeahh...First I had implement that but someone changed it and now it is not responsive at all. I just send a pr to make it responsive.
