### ISSUE TITLE
"Reach us out through..." Hover Effect Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [OSCode-Community/OSCodeCommunitySite#392]
### Current Behavior
The current hover effect of this section is nice but it can be improved by doing some color adjustments. Through some improvements, it can be made even better.
Check the difference of effect in current and first 2 options of expected updated design. In current design, hover effect is bright and uneven. In expected updated effect, you will feel hover effect more real. I have added a deep pressed button effect in hover effect. 

### Screenshots / Mockups

**Current Hover Effect**
![ss](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115794049/f7884cfb-0793-4a27-8508-ebb6a4d8d372)

**Expected Updated Hover Effect**
![oscode (1)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115794049/ff00a200-a5ed-4143-9573-38eee90ece7e)

**I want to work on this improvement as a part of GSSOC-23.**

**Comment by akshathar-navada** [comment]
Yeah, looks good @iamRabia-N . Pull the repo properly before updating it and then Open a PR with required screenshots . We will soon review and merge it:)

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by iamRabia-N** [comment]
@akshathar-navada Kindly mention the level in the issue that is mentioned in the merged pull request. The merged pull request is mentioned below:
Updated Hover Effect of "Reach us out through..." Section #398
