### ISSUE TITLE
adding home button on blogs and newsletter page to navigate back to the home page

### ISSUE THREAD

**Issue by mridulsaggi** [OSCode-Community/OSCodeCommunitySite#394]
i would like to contribute to the project by adding the home button on the pages to navigate back to the home menu
please assign me this issue as gssoc contribution

**Comment by akshathar-navada** [comment]
Hey @mridulsaggi , thanks for stepping up. We are currently creating the blog page using hashnode, so we won't be able to give access to everyone. If there is any othe rissue which u would like to work on, pls go ahead!
