### ISSUE TITLE
Correct Hyperlink Redirection

### ISSUE THREAD

**Issue by swarnade** [OSCode-Community/OSCodeCommunitySite#399]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78968218/f34bc08f-3571-4eca-b15d-1bf308518b97)

Want To Redirect This Button To Right Link

**Comment by martinyis** [comment]
Hey, I would like to work on that issue, just let me know which button exactly is not working

**Comment by akshathar-navada** [comment]
Can u pls let us know, which button is not working and u want redirect it? @swarnade

**Comment by swarnade** [comment]
I Want To Redirect the "Get Started" To club  joking form link

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @swarnade
