### ISSUE TITLE
📝 DOCS: add badges in README.md

### ISSUE THREAD

**Issue by peb-peb** [OSCode-Community/OSCodeCommunitySite#4]
Discuss here what badges could be added and then send the PR :)

**Comment by Anushka20365** [comment]
Hello @peb-peb  ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.

Skills
HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop |

Can you please assign this issue to me.

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Naincy04** [comment]
Hello, I'm a contributor for GSSoc'23, I want to work on this issue as I'm a beginner, please assign this issue to me.

**Comment by akshathar-navada** [comment]
@Anushka20365 , Hey buddy thanks for stepping up yea add the required badges and as this is a Open source project you can pull a request at any time we would be happy to merge it
Thank you!!
