### ISSUE TITLE
Improving social media icons section .Please assign this to me under GSSOC'23

### ISSUE THREAD

**Issue by silwite** [OSCode-Community/OSCodeCommunitySite#40]
Hello , Please assign me this issue as contributor under GSSOC'23 . I would like to work on it.
Tech Stack - MERN stack

**Comment by adityavpawar** [comment]
Hello, Please assign me this issue

**Comment by akshathar-navada** [comment]
> Hello , Please assign me this issue as contributor under GSSOC'23 . I would like to work on it. Tech Stack - MERN stack

Yes sure , go ahead ! @silwite

**Comment by creator79** [comment]
Hello! I would like to contribute to this project and improve the social media icons section. Is this issue still open or has it been assigned?  under GSSoc23I believe I can make valuable contributions in enhancing the design and functionality of the icons. Thank you!

**Comment by Aahad-1526** [comment]
Hi i would like to change the font of icons but adding individual icon different color and hover effect.
So please assign me this issue

**Comment by silwite** [comment]
> > Hello , Please assign me this issue as contributor under GSSOC'23 . I would like to work on it. Tech Stack - MERN stack
> 
> Yes sure , go ahead ! @silwite

**Comment by silwite** [comment]
I have created the pull request can you check

**Comment by akshathar-navada** [comment]
Yes sure, we will review and merge it soon!
