### ISSUE TITLE
NavBar should be added in the Privacy Policy

### ISSUE THREAD

**Issue by Suhaani07** [OSCode-Community/OSCodeCommunitySite#401]
<img width="1080" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98284331/e942b03d-2f86-4a41-9eb2-0ff6f2160340">
This Navbar should also be added in the Privacy Policy Page to giive a uniform look as well as help to redirect back to the Home Page.
If possible, assign me this under gssoc 2023. Thank You

**Comment by akshathar-navada** [comment]
Hey @Suhaani07 , thanks for stepping up. The policy page is structurized and it is built through standard policy generator. SO, it's not required change anything in that. If there is anything else, u would like  to work on please go ahead!
