### ISSUE TITLE
Discord button not added in footer section

### ISSUE THREAD

**Issue by AlabhyaG** [OSCode-Community/OSCodeCommunitySite#405]
### Description

In the footer section where all social media handles link are there , discord server link is not there
### Expected Behavior

Add the discord button beside the linkdln button.

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Yes,please add @AlabhyaG . Pull the repo properly and then make required changes. Open a PR with required screenshots, we will review and merge it soon!!
