### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#406]
# Before
## All buttons should have same property to look more symmetrical
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/8a9d48ae-703a-4b14-9ca9-d10926e295e1)
# After
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/8bcb7310-5bd5-40ea-b568-c1c68ec0659c)

**Comment by akshathar-navada** [comment]
Yes @Git21221 , please make required changes to enhance the current version of buttons:)
