### ISSUE TITLE
Hovering issues

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#407]
# Before
## While not hovered
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/f35019c4-6721-483e-911c-dd77ad8b9ba2)
## While hovered
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/52095d44-912d-4752-8a20-c3b5e76e9307)
### Hovering effects can be more optimized and soothing

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Git21221 !!
