### ISSUE TITLE
Hamburger icon style

### ISSUE THREAD

**Issue by parasss19** [OSCode-Community/OSCodeCommunitySite#411]
### Description
Hamburger Icon hide

### Expected Behavior
OS-Code is responsive website and everything is working properly but 
At 351px hamburger icon is not hidden 
But below 351 screen size the hamburger icon is disapear 

### Screenshots

# Before 
<img width="960" alt="2023-05-26" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101205226/b3583d4a-9563-4ebc-ab98-039b91232a6d">

#  After

<img width="960" alt="2023-05-26 (1)" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101205226/f65c44b3-2f8e-4291-941e-4b54552c8049">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by parasss19** [comment]
I want to work on this issue please assign me this issue

**Comment by akshathar-navada** [comment]
hey @parasss19 , I don't think most of the people will use below it. So, don't need to change as of now
