### ISSUE TITLE
Dark Mode Button in Blogs Section

### ISSUE THREAD

**Issue by parasss19** [OSCode-Community/OSCodeCommunitySite#413]
### Current Behavior
The current UI of dark mode button is very basic 

### Desired Behavior
I want to make it more better than before 

### Screenshots / Mockups

# Before

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101205226/cd7d50aa-fac8-4301-810c-98d5aa0080af

# I will make this type of button in blog section and also make the ball transparnent

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101205226/e7fd8c47-cad1-48d1-b36f-b0b4e3dac7f9

### I want to work on this Please assign me this issue

---

**Comment by akshathar-navada** [comment]
Hey @parasss19 , thanks for stepping up. Actually we are creating blog page using hashnode, so we won't be able to give access to everyone. If there is any thing else , u would like to work on, please go ahead!
