### ISSUE TITLE
Testimonials section

### ISSUE THREAD

**Issue by yogita-github** [OSCode-Community/OSCodeCommunitySite#415]
Cards doesn't hover properly .

Expected Behavior
Hovering after moving cursor on cards

Screenshots
![hover](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/103029645/ac71a8f6-14ce-4ebd-8e31-9b544e8d9de5)

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @yogita-github . Pull the rep properly and then make required changes. Open a PR with required screenshots, we will review and merge it soon!!
