### ISSUE TITLE
There is no events Landing Page

### ISSUE THREAD

**Issue by Kalivarapubindusree** [OSCode-Community/OSCodeCommunitySite#419]
### Current Behavior

when we click on the events button it shows nothing.

### Desired Behavior

When we click on the events button it has to show some past or future events but here it does not show any events.

### Screenshots / Mockups

![WhatsApp Image 2023-05-26 at 5 18 28 PM](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114821855/952b37fe-28ee-4cd9-8a06-b5ed7ef48ef9)

---

**Comment by peb-peb** [comment]
@Git21221 is working on it. It would be available once it's complete.

Would close this issue after the events page is available.

**Comment by Git21221** [comment]
@Kalivarapubindusree If you have any design regarding this then please share that.

**Comment by Kalivarapubindusree** [comment]
I am interested to work on this issue GSSoC'23, so please assign me this task.

**Comment by peb-peb** [comment]
Sure, go ahead and make a PR. We'll review it.

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I can do the events page. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by ssm0212** [comment]
I am a GSSoC'23 contributor. I can make the events pages. Please assign me this issue.

**Comment by akshathar-navada** [comment]
Hello buddies, Event page enhancement is pinned in the issue section, so will be closing this isssue. If there is any improvements u guys would like to make , can discuss in the pinned issue.
Thank you!
