### ISSUE TITLE
I want to add sitemap to this website.

### ISSUE THREAD

**Issue by mayank123op** [OSCode-Community/OSCodeCommunitySite#421]
### Current Behavior
 I need to be able to increase efiiciency of this website.

### Desired Behavior
A sitemap guides the website visitors to where they want to go.

### Screenshots / Mockups

---

**Comment by akshathar-navada** [comment]
Hey @mayank123op, sitemap.txt is already there in the repo. Did u mean the same of adding all links in 1 place which would be helpful, OR anything else? Please let us know...

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I can add sitemap to this website. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by akshathar-navada** [comment]
Yes sure,pls go ahead @ARGHYADIPROY
