### ISSUE TITLE
'CONTACT SECTION' form is not secure 👽

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#424]
### Current Behavior 

-- Pop up msg which shows form is not secure
![Screenshot (430)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/520103b0-ac42-4ca8-9e62-d6acc1725cc0)

-- There is no Email Validator 
![Screenshot (412)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/0952c9d2-18f8-47f8-b4c0-c79f6e5b984e)

-- When submitted
![Screenshot (413)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/f08cf4ac-3d4c-4350-951d-fabfd62d4b66)

### Description

-- Fix the email validation: Add proper validation for entering correct format of email
-- Though autocomplete option is given in the code, for some reason it is not enabled. Please try to fix this.
-- Becos, of these issues when submitted it is showing the above warning message!!
-- If there is any other way to resolve this issue, pls suggest:)

### Points to be noted
-- Please give the brief desciption of the PR with required screenshots
-- Pull the repo properly and then make required changes:)
-- We will review it soon and would be very happy to merge your PR

## Happy coding 🤩

**Comment by Git21221** [comment]
I think I have solved it. But in order to check I need to make a pr. When I run through live server, the following error is not occuring.

**Comment by akshathar-navada** [comment]
> I think I have solved it. But in order to check I need to make a pr. When I run through live server, the following error is not occuring.

Yes, when run through live server it doesn't show any error. But when hosted it will show like the above screenshots!

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by akshathar-navada** [comment]
Yes go ahead @Gun2902

**Comment by Geeta259** [comment]
@akshathar-navada I wanna try to resolve this issue !!
Assign this to me!

**Comment by akshathar-navada** [comment]
Sure go ahead @Geeta259 :)

**Comment by Git21221** [comment]
@akshathar-navada the form is still not secure? Is it fixed?
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/235c2d0a-41b3-48e6-b355-abfd4e0885c3)

**Comment by akshathar-navada** [comment]
Yes , it is still not fixed @Git21221 . Idk why when hosted it is showing like this. Should fix this soon!!

**Comment by Git21221** [comment]
I don't think it can be fixed. It's a security feature of google.
