### ISSUE TITLE
reach out us section

### ISSUE THREAD

**Issue by leesha19** [OSCode-Community/OSCodeCommunitySite#426]
### Description

the row of social links are divided in 3 columns which is not looking good
### Expected Behavior

it should be divided in 4 columns to cover the whole page 
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Hey @leesha19 , thanks for stepping up!
Yea it would be nice if it was divided into 4 columns, but what should we add so that it covers the space. I think these many social media's are enough. If there is anything else u would like to work on, pls go ahead!

**Comment by leesha19** [comment]
> Hey @leesha19 , thanks for stepping up! Yea it would be nice if it was divided into 4 columns, but what should we add so that it covers the space. I think these many social media's are enough. If there is anything else u would like to work on, pls go ahead!

OKAY !! SO WHAT WE CAN DO HERE IS : we can add space between them or center them so it would look good and hence it will cover up the space
