### ISSUE TITLE
[Addition] I want to add my blogs

### ISSUE THREAD

**Issue by Anshika-Jain02** [OSCode-Community/OSCodeCommunitySite#428]
*As, the blog section of the web page has no blogs for now and it is giving an empty appearance to the web page. I want to add some of my technical blogs to it like- A comparison between hosting websites (Hostinger and Hostgator), etc*

**Please assign this issue to me under Gssoc'23 @harshsingh32**
![oscode](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/104912087/f2786855-f404-4d5e-8001-55d837992751)

**Comment by akshathar-navada** [comment]
Hey @Anshika-Jain02 , thanks for stepping up!
Actually we are creating the blog page, through hashnode, so we won't be able to give access to everyone. If there is anything else , u would like to work on pls go ahead!
