### ISSUE TITLE
[Enhancement] New blog addition

### ISSUE THREAD

**Issue by DivyanshiNarang** [OSCode-Community/OSCodeCommunitySite#429]
No blogs are present in the Blog section. I can add my technical blogs.

<img width="871" alt="Screenshot 2023-05-26 232341" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/74779601/8d745137-cd73-4e69-bd4a-2ba9020b440d">

*Please assign this issue to me under GSSoC'23* @harshsingh32

**Comment by akshathar-navada** [comment]
Hey @DivyanshiNarang  , thanks for stepping up!
Actually we are creating the blog page, through hashnode, so we won't be able to give access to everyone. If there is anything else , u would like to work on pls go ahead!
