### ISSUE TITLE
Improve Our Sponsors and partners Section

### ISSUE THREAD

**Issue by shreya26-bit** [OSCode-Community/OSCodeCommunitySite#43]
Arrow cursor does not change to a hand cursor, when clicking on sponsors. I wants to solve this issue .please assigned this issue to me

**Comment by shramanpaul** [comment]
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by peb-peb** [comment]
Go ahead and submit a pull request, we would be happy to merge it! @shreya26-bit
