### ISSUE TITLE
[Feature] Addition of links in CHAPTER section

### ISSUE THREAD

**Issue by DivyanshiNarang** [OSCode-Community/OSCodeCommunitySite#431]
We can add links of colleges in the CHAPTER section.

<img width="484" alt="Screenshot 2023-05-26 234212" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/74779601/2474e190-0c4f-4d3f-9f04-47d90a190a71">

*Please assign this to me under GSSoC'23* @harshsingh32

**Comment by akshathar-navada** [comment]
Hey @DivyanshiNarang , thanks for stepping up!
Actually we are creating separate pages for each colleges, we will be linking that,so don't need add this. After that is linked u can make changes in those individual pages , if required:)
