### ISSUE TITLE
Want to improve UI of Blog's section

### ISSUE THREAD

**Issue by shubhisingh184** [OSCode-Community/OSCodeCommunitySite#433]
### Current Behavior

As of now, the UI of blog's section doesn't look appealing in comparison to home page and other sections.
### Desired Behavior

By improving the UI ( which includes the header and adjusting icons size ), it  will look more appealing to the user and similar with the website's whole theme and it will surely give good user experience. I would like to add an extra blog in the blog's section.

**Comment by Kapileswar-Moharana** [comment]
Assign this to me under GSSoC'23

**Comment by akshathar-navada** [comment]
Hello  buddies , thanks for stepping up!
Actually we are creating the blog page, through hashnode, so we won't be able to give access to everyone. If there is anything else , u would like to work on pls go ahead!
