### ISSUE TITLE
[Gssoc'23] Add social media icons in contact us section for users to contact conveniently.

### ISSUE THREAD

**Issue by prathanab** [OSCode-Community/OSCodeCommunitySite#434]
### Current Behavior

social media icons are in corner in small size.

### Desired Behavior

[Gssoc'23] Add social media icons in contact us section for users to contact conveniently.

### Screenshots / Mockups

![WhatsApp Image 2023-05-26 at 10 36 24 PM](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121685069/a5661df9-bbd2-47fc-a957-344d715e8099)

---

**Comment by prathanab** [comment]
assign this to me @harshsingh32

**Comment by akshathar-navada** [comment]
Hey @prathanab ,thanks for stepping up!
As we have included the social media icons in JOIN US section, I don't think we have to include again that in ocntact section. 
If there is anything else, u would like to work on , pls go ahead
