### ISSUE TITLE
adding college name section in contact

### ISSUE THREAD

**Issue by Sushilverma002** [OSCode-Community/OSCodeCommunitySite#435]
### Current Behavior
there is no section for student college section

### Desired Behavior
it will help you for reaching the student more accurately.

### Screenshots / Mockups

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114687502/5392254a-9d32-4795-9e35-96ad8749adc0)

---

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Sushilverma002 . Try to keep the layout properly!
