### ISSUE TITLE
Adding Home Sign in OSCode's blog page

### ISSUE THREAD

**Issue by ARGHYADIPROY** [OSCode-Community/OSCodeCommunitySite#436]
### Current Behavior
There is no way to go to the home page of OS CODE from OSCode's blog page.

### Desired Behavior
Give a home sign in OSCode's blog page.

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I can add home page in OSCode's blog page. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by akshathar-navada** [comment]
Hello , thanks for stepping up!
Actually we are creating the blog page, through hashnode, so we won't be able to give access to everyone. If there is anything else , u would like to work on pls go ahead!
