### ISSUE TITLE
No Navbar in OSCode's Blog page.

### ISSUE THREAD

**Issue by Sarora2127** [OSCode-Community/OSCodeCommunitySite#437]
**Current Behavior**
There is no navbar in OSCode's Blog page. If I want to go back to Home Page/ Chapter Page there is no option for the same. 

**Desired Behavior**
There can be a navbar with accordance to the navbar in other pages which makes travelling through the OSCode's Blog Page easier.

**Screenshots / Mockups**
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119870703/e8c59ff0-b89f-4e83-a7b8-91c2579ccbbe)

Please assign me this issue under **GSSoC 2023**

---

**Comment by akshathar-navada** [comment]
Hello buddies , thanks for stepping up!
Actually we are creating the blog page, through hashnode, so we won't be able to give access to everyone. If there is anything else , u would like to work on pls go ahead!
