### ISSUE TITLE
Enhancing UI of OSCode's Blog Page

### ISSUE THREAD

**Issue by Sarora2127** [OSCode-Community/OSCodeCommunitySite#438]
**Current Behavior**
There is no hover effect for social icons in OSCode's Blog page. 

**Desired Behavior**
There can be beautiful hover effect for social icon and a scrolling bar complementing the page's design would be a better page to visit.

**Screenshots / Mockups**
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119870703/a333e5bb-5b23-4797-99bd-9a4b6514d4b3)

I have the required knowledge solve this issue.
Kindly assign this to me under **GSSoC 2023**

---

**Comment by Sarora2127** [comment]
I'm a contributor in GSSoC 2023 . I have all the skills which this issue requires. Kindly assign this issue to me.

**Comment by akshathar-navada** [comment]
Hello buddies , thanks for stepping up!
Actually we are creating the blog page, through hashnode, so we won't be able to give access to everyone. If there is anything else , u would like to work on pls go ahead!
