### ISSUE TITLE
Testimonial needs to be updated

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#439]
As a override in carousel causing testimonial not to be working as expected.
# Before
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/960abcaf-ab7d-497c-b862-0a34e0ea901b)
# After
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/a10d9218-95d3-4bc6-a102-4e80302fc81f)

**Comment by akshathar-navada** [comment]
Yes, Please fix the layout of it proper @Git21221
