### ISSUE TITLE
Improving Contact us issue

### ISSUE THREAD

**Issue by shreya26-bit** [OSCode-Community/OSCodeCommunitySite#44]
To reduce the big gap between the contact section and the frequently asked questions section and improve the overall appearance.
I wants to work on this issue, please assigned it to me.

**Comment by peb-peb** [comment]
Go ahead and submit a pull request, we would be happy to merge it! @shreya26-bit

**Comment by PatilHarshh** [comment]
Hello ,
I'm harsh. I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | node js mongodb | Php, mysql | MERN | Responsive Design 

Can you please assign this issue to me.
@peb-peb

**Comment by Aahad-1526** [comment]
Hi there,
I would like to work on this issue
