### ISSUE TITLE
About section improvement

### ISSUE THREAD

**Issue by engorgedspirit** [OSCode-Community/OSCodeCommunitySite#441]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85272049/6c5475eb-7d0e-4e84-9799-2e975b559ae9)
There is no information about site in about section of github. A short description would be better here. Im a GSSoc cntributor, please assign me this issue, I will resolve it

**Comment by akshathar-navada** [comment]
As we mentioned that in readme, we don't have to repeat the same here.
