### ISSUE TITLE
The top section of event page is not responsive [GSSoC'23]

### ISSUE THREAD

**Issue by ritik48** [OSCode-Community/OSCodeCommunitySite#442]
### Current Behavior
When the event page is viewed on smaller screen then top section of the page do not adjust with change in screen size.
![os responsive issue in events](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/84488726/1eaee535-8688-47ea-ba7f-1ff1ca552f80)

### Desired Behavior
 I want to solve this issue, please assign this to me under GSSoC'23.

**Comment by vishnubansal001** [comment]
i Want to work on this issue please allow me to work on this issue please allow me to work on this issue @Avinash905 @curiousyuvi @harshsingh32 @Ghat0tkach

**Comment by akshathar-navada** [comment]
Hello buddies , thanks for stepping up!
Event section is under work, and @Git21221 is making it responsive. If u want to join and help him, please go ahead!

**Comment by vishnubansal001** [comment]
Yes i want to join can i join him

**Comment by Git21221** [comment]
@vishnubansal001 I have just made a basic event section. If you want to design more better make sure to raise a issue with proper screenshot that describes the changes.

**Comment by vishnubansal001** [comment]
Ohk i am raising the issue please @akshathar-navada assign that to me
