### ISSUE TITLE
Several UI/UX Improvements Needed on Home Page

### ISSUE THREAD

**Issue by manaver** [OSCode-Community/OSCodeCommunitySite#445]
When viewing the home page, the navbar links lack sufficient margin in the X axis, resulting in a cramped appearance. This affects the overall aesthetics and usability of the navigation bar. The links need to have proper spacing between them to enhance the visual appeal and improve user navigation.

### Description
In the "Numbers say it all!" section of the home page, there are cards that display information. Currently, when hovering over these cards, there is no scaling effect, and the transition feels abrupt. It would be great to have a slow scaling effect applied to the cards when hovering, creating a smoother and more visually pleasing interaction.

### Description
The scrollbar used for scrolling through content does not align well with the website's theme. It should be improved to match the overall aesthetic and provide a consistent user experience.

### Description
The animation in the "Why choose us?" section appears to be too fast. To enhance the user experience, it would be beneficial to slow down the animation, allowing users to better perceive the transitions and absorb the information presented.

**Comment by manaver** [comment]
Please assign this issue to me as I am GSSOC'23 contributor

**Comment by akshathar-navada** [comment]
Yes sure, pls go ahead @manaver
