### ISSUE TITLE
Improve visual structure of Navbar to make it more appealing

### ISSUE THREAD

**Issue by sanketsaurav2411** [OSCode-Community/OSCodeCommunitySite#45]
I would like to improve visual structure of Navbar to make it more appealing.
Please assign me this issue under GSSOC'23.

**Comment by karthik2004315** [comment]
I am willing to work on this. please assign it to me

**Comment by peb-peb** [comment]
Could you please show a proposed UI for the Navbar? 

Also, what features do you want to add to it?

**Comment by karthik2004315** [comment]
ok first I want navbar to be fixed
1. logo to its end 
2. font change 
and there are more ill provide you with ui tommorow

**Comment by shramanpaul** [comment]
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by sanketsaurav2411** [comment]
Hello @peb-peb,
First, I would like to add Glassmorphic Effect to Navbar it will look more appealing.
Then, hover effect on navbar options and Contact Us button can be improved.

**Comment by peb-peb** [comment]
Go ahead and submit a pull request, we would be happy to merge it! @sanketsaurav2411
