### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#450]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/7d16f2a1-ef41-40c0-92f6-a9e2430c1be1)
1) Top navbar (logo) is not vertically center.
2) In medium screen right webp picture is shrinking.
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/8a4e051e-0cce-448e-bddf-8a5c14e63d8d)

**Comment by soorjya** [comment]
i can help with the privacy policy issue so please assignee me this issue under GSSOC'23

**Comment by akshathar-navada** [comment]
Hello buddies, I would rather suggest to delete the logo, becos it is kind of odd in that page.
And moreover the privacy policy page is built through standard template! and ig redirection back to homepage is not required through the logo itslef. We have also added(linking to main page)  in the copyright section at the end :)
