### ISSUE TITLE
feature request: Enhancment in contact section - SS sample

### ISSUE THREAD

**Issue by rohanmittal1163** [OSCode-Community/OSCodeCommunitySite#451]
### Current Behavior
the current contact section does not seem to be more appealing to eyes.

### Desired Behavior
a better type of contact section in which map links and form are at a correct place

### Screenshots / Mockups
i can make like this
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97821844/b94f03cb-fdf6-4f77-a1b7-7788937940b4)

pls assign me this issue under GSSOC'23
---

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @rohanmittal1163
