### ISSUE TITLE
[GSSOC'23] Navbar logo alignment and height issues

### ISSUE THREAD

**Issue by rohanmittal1163** [OSCode-Community/OSCodeCommunitySite#452]
### Description
hi  @Divesh2003 recently i came across your website.  The navbar height was too large than the normal ones we see in other websites . I am well versed in html css. i can fix this

### Expected Behavior
1. alignment of logo and name is not correct
2. height of navbar increases
3. contact button should be a part of the navbar

### Screenshots
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97821844/8e1f670f-de4e-42dc-a40e-36a6a1a85ebd)

### Enviroment:
 - OS: Windows
 - Browser: brave
 - Device: Desktop ,Mobile

## pls assign this issue as a GSSOC'23 contributor to contribute in this repo
thank you in advance

**Comment by Divesh2003** [comment]
Share screenshots when your work is done @rohanmittal1163

**Comment by rohanmittal1163** [comment]
Ok

**Comment by rohanmittal1163** [comment]
hi @Divesh2003 
i recently sees the issue has been resolved
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97821844/2a89b8ab-4264-4163-9f23-dc0debfb4332)

can i contribute in button styling 
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97821844/c76688d1-52c5-41d4-8799-0c4d8227ea0f)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97821844/75289566-1651-406c-aaf6-ce8fb93c8669)

**Comment by akshathar-navada** [comment]
Yes sure,go ahead @rohanmittal1163 . Open a PR with required screenshots, we will review it soon!

**Comment by rohanmittal1163** [comment]
@akshathar-navada ok i will do it soon
thank you
