### ISSUE TITLE
[Bug/issue] Service Link not working

### ISSUE THREAD

**Issue by iamvbenz49** [OSCode-Community/OSCodeCommunitySite#455]
### Description
the service button in home page and footer section is taking us to the home page

### Expected Behavior
when we click on the service link , it should lead us to service pagw

### S
![Screenshot from 2023-05-28 02-41-23](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93785572/11ecf491-f9dd-40bc-b585-b47ab43abf78)
creenshot
![Screenshot from 2023-05-28 02-41-31](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93785572/26437b4f-c175-41c8-8f75-48d2d7faa08e)
s

### Enviroment:
 - OS: Fedora Linux 
 - Browser: Firefox
 - Device: Desktop

**Comment by iamvbenz49** [comment]
i would like to work in this issue

**Comment by akshathar-navada** [comment]
Hey @iamvbenz49 , Thanks for stepping up!
We are currently working on servicec page, so it is not linked yet. We will be linking it soon!
If there is anyhting else u would like to work on, pls go ahead:)
