### ISSUE TITLE
Improve the contact us section

### ISSUE THREAD

**Issue by sanketsaurav2411** [OSCode-Community/OSCodeCommunitySite#46]
I would like to improve the contact us section and add some features to it.
Please assign me this issue under GSSOC'23.

**Comment by peb-peb** [comment]
Could you please show a proposed UI for the Contact Section? 
Also, what features do you want to add to this?

**Comment by sanketsaurav2411** [comment]
Hey @akshathar-navada @peb-peb, I would like to work on this issue. Could you please assign me this issue under GSSOC'23.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @sanketsaurav2411

**Comment by sanketsaurav2411** [comment]
> Yes sure, go ahead @sanketsaurav2411

Hey @akshathar-navada kindly checkout PR #114
