### ISSUE TITLE
Small issues in event section

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#460]
1) Scroll link is not working.
2) Contact us button is not designed as others
3) for small screen scroll becomes in the top.
# 3
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/85320282-ccda-449e-a365-767d9dab905c)
# 2
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/8bd401d5-8c8b-4812-b648-79f8c7557685)

## New scrollbar hover color.
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/94ca2ae5-d4d8-4404-aec5-9164ca9549ad)
After hover color will be dark.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Git21221 😃
