### ISSUE TITLE
Add a scroll functionality in the Scroll text in the Events Page

### ISSUE THREAD

**Issue by sabeenaviklar** [OSCode-Community/OSCodeCommunitySite#463]
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Hey @sabeenaviklar , it's already there. Are you specifying the same or anything else?
Can u tell us more about the issue?

**Comment by sabeenaviklar** [comment]
![gscoc](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/122459291/9661d349-6c25-49f6-a146-f84948fd0b08)
When you see the scroll text on the event page, You have to scroll by yourself. But instead of that it should scroll down automatically when you click on that text.

**Comment by akshathar-navada** [comment]
When we click on scroll text, it will scroll to the next section automatically. Please check this...
