### ISSUE TITLE
Creating a Better UI for Contact Us Section.

### ISSUE THREAD

**Issue by sabeenaviklar** [OSCode-Community/OSCodeCommunitySite#464]
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @sabeenaviklar . Open a PR with required screenshots. And pull the repo properly before making any changes. We will review soon!

**Comment by Arman-ali1** [comment]
Yes sure, go ahead @sabeenaviklar . Open a PR with required screenshots. And pull the repo properly before making any changes. We will review soon!

**Comment by Arman-ali1** [comment]
please assign me

**Comment by akshathar-navada** [comment]
Yes sure, u can also work on it @Arman-ali1

**Comment by sabeenaviklar** [comment]
Hello, @akshathar-navada  @Arman-ali1 , I am already working on the issue

**Comment by akshathar-navada** [comment]
> Hello, @akshathar-navada @Arman-ali1 , I am already working on the issue

Ok fine, open a PR with required screenshots. We will review it soon!

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by mubasharaKhan** [comment]
Assign me this issue under GSSoC'23 label

**Comment by Arman-ali1** [comment]
> Assign me this issue under GSSoC'23 label

Yes sure, u can also work on it

**Comment by YashKoli02** [comment]
please assign me
