### ISSUE TITLE
Fix the contact us section (open to  all to fix this issue) 

### ISSUE THREAD

**Issue by akashgreninja** [OSCode-Community/OSCodeCommunitySite#465]
### Description
The phone numbers must redirect the user to their phone app in the contact us section

### Expected Behavior
The phone numbers must redirect the user to their phone app 

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Git21221** [comment]
What's wrong with `call us` section? It is working perfectly

**Comment by akashgreninja** [comment]
It should redirect us to the contact app when we press the specific number not the icon above it there are 2 numbers there

**Comment by akashgreninja** [comment]
same with the email id as well

**Comment by Git21221** [comment]
Ok Ok got it.

**Comment by omlondhe** [comment]
May I work on this issue?
I am GSSoC 2023 contributor.
