### ISSUE TITLE
Adding target attribute  in footer socials

### ISSUE THREAD

**Issue by Dimple-Choudhary** [OSCode-Community/OSCodeCommunitySite#469]
### Description
When we click on the social icons in the footer they open in the same tab. 

### Expected Behavior
Opening a social website in a new tab provides a better user experience because it allows you to multitask, easily navigate between different pages, browse faster, stay organized, and be more productive.
### Screenshots
![Screenshot (59)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96401557/761aaf4d-84b2-41ed-ab94-c33e4b9cb7f6)

Can you assign me this issue under GSSoC'23 @akshathar-navada

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @Dimple-Choudhary

**Comment by Dimple-Choudhary** [comment]
Hey, can you add a label/tag of GSSoC'23?

**Comment by Divesh2003** [comment]
Hello @Dimple-Choudhary 👋

I added a gssoc and level label in your Merged PR #520 of this issue

**Comment by Dimple-Choudhary** [comment]
Okay,  Thank you :)
