### ISSUE TITLE
new redesigned in accomplishment

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#472]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/730340b0-49ce-49fd-af19-39396a59f1b3)
These three part should be at the same height and identical.

**Comment by real-coder007Ravi** [comment]
I want to work on this issue

**Comment by Git21221** [comment]
# New updated look
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/c9fd1b53-b5e3-46cd-92bc-36555966a854)
