### ISSUE TITLE
Adding articles in blogs page

### ISSUE THREAD

**Issue by Shr-reny** [OSCode-Community/OSCodeCommunitySite#479]
We can add a few sensational articles in the blogs page which is currently empty. Articles can be on simple queries like which domain to choose for better future or how to deal with DSA.

**Comment by akshathar-navada** [comment]
Yes agree with this @Shr-reny , thanks for stepping up!
Actually we are creating the blog page, through hashnode, so we won't be able to give access to everyone. If there is anything else , u would like to work on pls go ahead!
