### ISSUE TITLE
Change in blog section -drop down [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [OSCode-Community/OSCodeCommunitySite#48]
As the drop down for navigation bar for the blog section looks too simple compare to others section would like to work upon it add some visually attractive changes like adding hover effect, etc.
Do assign this issue to me under GSSOC 2023,changes will be done in no time !

**Comment by peb-peb** [comment]
The blog section is hosted with Hashnode. So, I guess it would be difficult to edit those properties. PING me if you find any good solution.
