### ISSUE TITLE
Home button of Footer not working

### ISSUE THREAD

**Issue by trisharaj06** [OSCode-Community/OSCodeCommunitySite#480]
### Description
on event tab by clicking on this home button it opens 404 not found page, could you assign this to me under gssoc'23

![Screenshot (730)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/109025651/29894d58-0055-4fd0-8833-f83fd05a922e)

**Comment by akshathar-navada** [comment]
Yes @trisharaj06 , pls go ahead and fix this!
