### ISSUE TITLE
Improving hover effect of event page

### ISSUE THREAD

**Issue by trisharaj06** [OSCode-Community/OSCodeCommunitySite#481]
I want to improve UI and hover effect of these cards, could you assign this to me

![Screenshot (729)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/109025651/4da2c3d3-bbfa-41a1-bf26-673666ab30ab)

**Comment by Abhinavcode13** [comment]
No update on this , please assign it to me now @akshathar-navada

**Comment by akshathar-navada** [comment]
Okay!, go ahead @Abhinavcode13

**Comment by Gautam-10137** [comment]
@akshathar-navada  Please assign me this issue under GSSOC'23
