### ISSUE TITLE
Services button not working and alignment of join us icons ,working of footer 

### ISSUE THREAD

**Issue by KanchandeepK** [OSCode-Community/OSCodeCommunitySite#483]
1)The services button is not working. I want to direct on clicking the button to the page including all the past services along with number of people engaged with website through different services. The increase in the number of sample testimonials .
2)Responsiveness in the Join Us icons
3)Clicking on address in bottom should open map to direct to the exact location, working of each option in the footer

#Please assign this issue to me

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @KanchandeepK . Open a PR with required screenshots. We willr eview it soon!
