### ISSUE TITLE
"Join Us" Section Text Alignment Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [OSCode-Community/OSCodeCommunitySite#484]
### Current Behavior
Alignment of all the content of "Join Us" Section towards left.

### Desired Behavior
Changing the alignment of all the content of "Join Us" Section to center will enhance the overall design of the website and it will make the website look even better.

### Screenshots / Mockups
**Current Design**
![oscode issue3 ss (2)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115794049/90c6ef30-f873-4136-8e77-ea86b81b5937)

**Updated Design**
![oscode issue3 ss (1)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115794049/071cab99-1949-4dd3-8cd3-74a8b38ee7f7)

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @iamRabia-N. Wrap the content below 'how to join us?' , don't stretch it to full length. Open a PR with required screenshot . We will review it soon!
