### ISSUE TITLE
[Docs]: Improve ReadME file

### ISSUE THREAD

**Issue by its-me-abhishek** [OSCode-Community/OSCodeCommunitySite#485]
### Current State:
Currently, the ReadME file has a lot of punctuation errors that can be fixed.

### Desired State:
We can also add alignment to our various tech stacks, etc. , provided and the file and in turn, make it more appealing. 
---

Please assign this issue to me under GSSoC 2023

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @its-me-abhishek
