### ISSUE TITLE
Change in FAQS 

### ISSUE THREAD

**Issue by Enhancer18** [OSCode-Community/OSCodeCommunitySite#494]
### Current Behavior

When the drop down beside a FAQ is pressed we need to be able to see the question but the question is almost invisible .

### Desired Behavior

We need to be able to see the question for more accessibility for users.

### Screenshots / Mockups

![Screenshot_2023-05-30-07-48-29-89_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/102911149/11c8329e-1a6d-4e7f-9905-9a7bbcbd8b35)

This one is when drop down is not clicked. 

![Screenshot_2023-05-30-07-48-35-22_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/102911149/44dafb0d-4856-4f0c-9109-e03174fb9136)

This one when drop down is clicked.
Here making the question visible is needed.

---

**Comment by akshathar-navada** [comment]
Yes, pls resolve the issue @Enhancer18
