### ISSUE TITLE
New Contact us section glitches (Open to all)

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#495]
# 1) While opening `oscode.co.in` it redirects to the contact us section.
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/79d088d7-699c-4a5d-863e-ab301210e947)

# 2) The map is showing world map not the oscode office.
# 3) The contact form is not getting submitted.
@Divesh2003 kindly look into the matter

**Comment by akshathar-navada** [comment]
Yes @Git21221 , please resolve this.
-- And also instead of 'Last name" option ,change that "College " 
-- also try to shorten the length of that section a bit!, even in width, it is stretched too much
-- The backgronud color blue and purple is not matching, try to enhance that in a way matching to the existing theme

**Comment by Git21221** [comment]
I have my exam from 1st june so Now I can't contribute :(.

**Comment by akshathar-navada** [comment]
> I have my exam from 1st june so Now I can't contribute :(. @akshathar-navada Make it open for all. anyone can fix this.

Oh ok ok

**Comment by shruuti321** [comment]
Can I take up any of these issues?

**Comment by Git21221** [comment]
Sure you can. Try to remember all points that akshatha said.

**Comment by akshathar-navada** [comment]
> Can I take up any of these issues?

Yes sure, go ahead @shruuti321

**Comment by Hardik-2311** [comment]
can i take this issue as i have raised an issue regarding this that it takes only 1 number in mobile number that should be 10

**Comment by akshathar-navada** [comment]
Will be closing this issue, as there were many conflicts. Will soon open a new issue regarding enhancement of contact section.
Thank you!
