### ISSUE TITLE
Adding more testimonials

### ISSUE THREAD

**Issue by shruuti321** [OSCode-Community/OSCodeCommunitySite#496]
only one testimonial is featured in the website. I believe there should be atleast three testimonials required to assure the customer about the authenticity of the website. Also the heading is mentioning 'testimonials' ,so a single testimonial wont do the justice.
Therefore I request you to assign me the task of adding few more testimonials so that the right-left scroll feature also works or else remove the scroll featuring.
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114770273/e9981db7-fbbb-41ed-bf8c-bcc0dcf33148)

**Comment by akshathar-navada** [comment]
Hey @shruuti321 ,thansk for stepping up!
We will add those testimonials shortly
