### ISSUE TITLE
[Enhancement]: Navbar UI changes and color changes on scrolling it .

### ISSUE THREAD

**Issue by HarshSharma0801** [OSCode-Community/OSCodeCommunitySite#498]
I would like work on Enhancement of navbar and its UI changes on Scrolling
@Divesh2003  Sir , please assign it to me

**Comment by akshathar-navada** [comment]
Yes sure @HarshSharma0801 ,go ahead. Open a PR with required screenshots. We will review it soon!

**Comment by HarshSharma0801** [comment]
@Divesh2003 thanks sir

**Comment by HarshSharma0801** [comment]
@akshathar-navada thanks sir

**Comment by HarshSharma0801** [comment]
@akshathar-navada  and @Divesh2003  Can you review it please.
