### ISSUE TITLE
📝 DOCS: add social media handles for OSCodeCommunity in README.md

### ISSUE THREAD

**Issue by peb-peb** [OSCode-Community/OSCodeCommunitySite#5]

**Comment by peb-peb** [comment]
Yeah Sure!! @SK-ILLish-GIT

**Comment by SK-ILLish-GIT** [comment]
@peb-peb actually there is 1 more PR already in pending ("Fix the responsiveness of the Navbar #16").

**Comment by peb-peb** [comment]
You can send more than 1 PR at a time :)

**Comment by akshathar-navada** [comment]
Added all the required social media handles 🙂
