### ISSUE TITLE
Sponsors images are not scaled properly

### ISSUE THREAD

**Issue by shramanpaul** [OSCode-Community/OSCodeCommunitySite#50]
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me. The images of the sponsoring companies are blurred, I can fix this issue.

**Comment by peb-peb** [comment]
Please submit a pull request for the following. We would be happy to merge it :)

**Comment by AMAN-BAGADIYA** [comment]
> Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.😇

**Comment by VC6378** [comment]
Hello, I am a contributor to GGSoC'23, and I would like to contribute to this issue, I have a good hold on front end development and have done projects earlier as well, please assign me this issue.

**Comment by shramanpaul** [comment]
> 

I have submitted the pull request. You can review and merge it.
