### ISSUE TITLE
To set Google Map link of OS-CODE headquarter in Footer Section

### ISSUE THREAD

**Issue by ombhojane** [OSCode-Community/OSCodeCommunitySite#506]
Hey, I've tried to find the location of OS-CODE headquarter, but when I clicked on the text, it does not redirected me to desired location.
This is happened because, there is not link set for location of OS-CODE headquarter in Footer section yet.

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/82753658/764e8484-f664-4d36-98f8-7a06f202abad)

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/82753658/0ca92e59-2ae4-4270-949f-49c75dc3ca1c)

I can fix this issue, results user can navigate to OS-CODE headquarter's Google Map Location!
Can you please assign this issue to me..
GSSOC 2023 :)

**Comment by Bharath-KumarReddy** [comment]
I can fix this issue , When you click on the text of address of os code in the footer section then that will open in   google maps..
and it will be clearly visible as a link 


like this ..


![Screenshot 2023-05-30 223458](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127650446/7be16413-270c-4548-b814-832342f9e283)


after clicking ---


![Screenshot 2023-05-30 223536](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127650446/acc89685-8c43-48a3-993c-02aba39a703e)


please  consider this under GSS0C_23   [ contributor ]    : )

**Comment by ombhojane** [comment]
Thank you for assigning me on this issue!
