### ISSUE TITLE
improve the search bar design for the chapters page

### ISSUE THREAD

**Issue by An525ish** [OSCode-Community/OSCodeCommunitySite#51]
I want to make it look more appealing to users so kindly assign me this issue

**Comment by peb-peb** [comment]
Could you please show a proposed UI for the Search Bar? We can move forward from there.

**Comment by An525ish** [comment]
suree......something like that...

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93612051/22215d2d-4016-4f48-936c-88427be5af73

**Comment by peb-peb** [comment]
Nice @An525ish !

Go ahead and submit a pull request, we would be happy to merge it!

**Comment by RahulRana701** [comment]
hi @peb-peb I would like to work on this issue , please assign it to me........under GSSOC tag
