### ISSUE TITLE
Hover Effect missing on discord icon in footer

### ISSUE THREAD

**Issue by shwetazade27** [OSCode-Community/OSCodeCommunitySite#514]

**Comment by Bharath-KumarReddy** [comment]
i can fix this issue 

before 

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127650446/41911767-81f2-4164-babc-731013622648)



after  -----



![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127650446/da68ea93-99e6-40ed-808b-ebf9b747d176)

Please assign  this  under  GSSOC _23    : )

**Comment by Bharath-KumarReddy** [comment]
@OSCode-Community   once Look into this  : )
