### ISSUE TITLE
Improving the user interaction with home page

### ISSUE THREAD

**Issue by Anamika-Ratna** [OSCode-Community/OSCodeCommunitySite#515]
Current Behavior
Hello, I came across your website and found that when we hover over the names of the colleges on the home page ,the arrow cursor changes to hand cursor which might give the user an illusion that it is clickable .

 Desired Behavior
On hovering over the names of the colleges either the cursor should not change or the text should be clickable . I can add direct links of the websites of the respective colleges. This would improve the user experience and accessibility.  

Screenshots / Mockups
link for the screenshot of website : https://drive.google.com/file/d/1JqQWjFcfziORaxYpdW6d-HA_fuSbGyde/view?usp=drivesdk

Therefore I kindly request you to allow me to work on this issue so that I can solve it under GSSoC-23

**Comment by akshathar-navada** [comment]
Hey @Anamika-Ratna , direct those to the respective college websites

**Comment by Anamika-Ratna** [comment]
@akshathar-navada I have done the proposed changes . Will you please review and kindly merge this pull request.
https://github.com/OSCode-Community/OSCodeCommunitySite/pull/590
