### ISSUE TITLE
Copyright Section Not in Middle on Home page

### ISSUE THREAD

**Issue by BikramNarayan** [OSCode-Community/OSCodeCommunitySite#517]
Currently, the copyright section is not in the middle of the web page as expected. This misalignment affects the overall visual appeal and user experience of the website.

 If we fix it and put the copyright section in the middle, the website will follow the right design rules and provide a better user experience.

Before
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119877120/ad6d08b1-4132-41f3-a606-e3f8424d64db)

After
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119877120/48926f90-3b22-4d7b-8b1e-5d1edf71a0ad)

 @akshathar-navada , @Divesh2003  please assign this issue to me. I would like to work on it.

**Comment by akshathar-navada** [comment]
Hey @BikramNarayan , we prefer the exisiting one. If there is anything u would like work on, pls go ahead!
