### ISSUE TITLE
Home navigation in Events page footer not working

### ISSUE THREAD

**Issue by PoulavBhowmick03** [OSCode-Community/OSCodeCommunitySite#518]
### Description
The link to Home page in Events site doesn't work. Shows 404 error 
### Expected Behavior
It should bring the user to the home page of OSCodeCommunitySite
### Screenshots

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/133862694/da8a620f-003d-4067-b4ff-506e30454509)

go to https://www.oscode.co.in/events/events.html#
go to the footer and click on Home

### Enviroment:
 - OS: Mac Windows
 - Browser: Chrome  - Version: 
 - Device: Desktop

**Comment by SALegend** [comment]
I would like to work on this issue, can you assign it to me :)

**Comment by akshathar-navada** [comment]
Yes , please fix it @PoulavBhowmick03
