### ISSUE TITLE
Slider in Sponsors and Accomplishments section

### ISSUE THREAD

**Issue by amisha-shrivastava** [OSCode-Community/OSCodeCommunitySite#521]
### Current Behavior

Sliding is taking place on the basis of time intervals, which is time-consuming and not attractive to the users willing to see the sponsors and accomplishments. 

### Desired Behavior

Sliders should be present in the above sections making it easy to navigate.

### Screenshots / Mockups

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/90697383/54b79aae-ba0a-4530-adda-df30580df851)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/90697383/4a7bde20-8c78-4514-a892-9684e8954766)

I would like to contribute to this issue under GSSoc'23. Please assign me this issue.

**Comment by akshathar-navada** [comment]
Hey @amisha-shrivastava , can u pls tell how u r going to make the layout or what kind of slider u would like to add.
May be with a draft image would be better!

**Comment by amisha-shrivastava** [comment]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/90697383/983f7a72-bc27-4579-bfe1-4243b2e9af89)

Something like this for both sponsors and testimonials so that users could easily navigate by clicking on the arrows instead of waiting for 100ms to automatically navigate.

**Comment by akshathar-navada** [comment]
Yea okay!  Add it only to the accomplishment section. Anyhow we are not linking the sponsors/partners to any other page ,ig adding that would be extra :)
