### ISSUE TITLE
Icon missing and adding glow effect on hover

### ISSUE THREAD

**Issue by AdyaVerma03** [OSCode-Community/OSCodeCommunitySite#522]
### **Before:**

![Screenshot (348)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97099538/4acf5ec2-87ae-4bf6-bb00-410105b1a0a3)

### **After:**

![Screenshot (350)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97099538/5d5377ca-de73-4c14-b58e-f7aba8f187fa)

**Comment by AdyaVerma03** [comment]
Please assign this to me under GSSoC'23.

**Comment by akshathar-navada** [comment]
hey @AdyaVerma03 , the icon of that institute is there. Kindly check!
