### ISSUE TITLE
About link on Chapters Page is not working

### ISSUE THREAD

**Issue by ishita80** [OSCode-Community/OSCodeCommunitySite#523]
### Description
When the user goes to the chapters and then goes to about. The link doesn't take the user anywhere. Therefore, the user cannot access the about page from there.

### Expected Behavior
When user is on chapters page, and then decides to go to About. He/She should be able to go to About.

### Enviroment:
 - OS: Windows
 - Browser: Chrome
 - Version: 
 - Device: Desktop

@akshathar-navada Please assign me this issue.

**Comment by akshathar-navada** [comment]
hey @ishita80 , the link of about in the navbar is working fine. The link in footer 'About Us' has to redirect to the home page about  section ,pls resolve this!

**Comment by ishita80** [comment]
Okay, I will do that.
But the issue is talked about occurs only when we are on the Chapters Page. Please go to Chapters and then click about.

**Comment by akshathar-navada** [comment]
The about in chapter page is directing me to the home page about section itself. Kindly check!

**Comment by ishita80** [comment]
Ok
