### ISSUE TITLE
404 Error page 

### ISSUE THREAD

**Issue by PatilHarshh** [OSCode-Community/OSCodeCommunitySite#526]
This seems that this website not contain 404 error page @harshsingh32 please assign this to me @Divesh2003

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @PatilHarshh

**Comment by PatilHarshh** [comment]
@akshathar-navada  this issue was under gssoc 23 please put lable

**Comment by akshathar-navada** [comment]
I think I have already added while merging, pls check
