### ISSUE TITLE
[Docs]: Add Dynamic Logo 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [OSCode-Community/OSCodeCommunitySite#530]
### Current State:
- The logo of this repository is in black so that the logo is not properly visible in Github Dark mode, actually over `85%` users using Github in dark mode only

![Screenshot 2023-05-31 at 20-05-58 OSCode-Community_OSCodeCommunitySite](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/7376931a-4946-4d26-b988-992f75a768be)

### Desired State:
- So i want to add light version logo and want to implement `picture` tag in the readme file with `media`  query so that the logo will change Dark/White according to the user's theme

### Code of Conduct

- [X] I have checked the existing issues
- [X] I agree to follow this project's Code of Conduct
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

---

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @0xabdulkhalid
