### ISSUE TITLE
Positioning the footer

### ISSUE THREAD

**Issue by Google-Ka-Dinosaur** [OSCode-Community/OSCodeCommunitySite#532]
### Description

![Screenshot (200)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98577878/29470557-f57c-48d7-b4c7-0de89a0752ba)

### Expected Behavior

There is a whitespace below the footer. I don't know if that's a part of the design but it looks a bit unpleasant to me and hence I would like to position it appropriately. Kindly assign me the issue.
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Hey @Google-Ka-Dinosaur , i don't think the white space exist. Kindly check..

**Comment by Google-Ka-Dinosaur** [comment]
Well, it's still showing on my device.
![Uploading Screenshot (204).png…]()

**Comment by akshathar-navada** [comment]
Ohh..ok, please resolve this! @Google-Ka-Dinosaur

**Comment by Google-Ka-Dinosaur** [comment]
Okay
