### ISSUE TITLE
colllge links in chapter section not directing to anywhere

### ISSUE THREAD

**Issue by shruuti321** [OSCode-Community/OSCodeCommunitySite#534]
Aren't the college links mentioned in the chapter page supposed to direct us to the specific college sites?
But these links are not generating any response.
I can address this issue if assigned under GSSOC'23.

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114770273/862700d0-f956-47af-8eb2-21f1e7ff1622)

**Comment by akshathar-navada** [comment]
We will soon be linking it, so don't need to link to their website
