### ISSUE TITLE
Add depandabot

### ISSUE THREAD

**Issue by k-deepak04** [OSCode-Community/OSCodeCommunitySite#539]
### Current Behavior
Can cause dependency issue as someone might use old libraries while coding

### Desired Behavior
"Integrating Dependabot into our open-source project will automate dependency updates, ensuring we stay up-to-date with the latest security patches and feature enhancements."
"By leveraging Dependabot's automated pull requests for dependency updates, we can reduce the burden on maintainers and foster a more secure and stable codebase."
"Adding Dependabot as a dependency management tool will demonstrate our commitment to maintaining a healthy ecosystem, allowing contributors to focus on higher-value tasks while keeping our project dependencies secure and reliable."

### Screenshots / Mockups
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96341431/8258d512-cd5c-4688-9a5b-6dd7f3916086)

---

**Comment by k-deepak04** [comment]
Assign it to me under GSSOC'23 :)

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @k-deepak04
