### ISSUE TITLE
Change in hover effect in **Why Choose Us?** section [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [OSCode-Community/OSCodeCommunitySite#54]
#
![WhatsApp Image 2023-05-20 at 9 03 26 PM](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96622693/85494211-d162-4c7f-89a0-e4459ee05a57)
 
the hover effect (rectangle becomes circular after hovering) in **Why Choose Us?** section at left side looks pretty weird ....I like to add some visually attractive hover effect to it.
Do assign it to me under GSSOC 2023 !

**Comment by Aditi323** [comment]
Please assign this to me as a GSSOC contributor.

**Comment by peb-peb** [comment]
@ManishaSwain8 Go ahead and submit a pull request, we would be happy to merge it!

**Comment by PatilHarshh** [comment]
Please @ManishaSwain8 assign it to me

**Comment by ManishaSwain8** [comment]
> @ManishaSwain8 Go ahead and submit a pull request, we would be happy to merge it!

opened pull req. please do check it out !
