### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by kalashvasaniya** [OSCode-Community/OSCodeCommunitySite#545]
### Description
Navbar opacity is so light I want to increase that!

### Expected Behavior
Looking cool

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Parijatkumar** [comment]
Hi @kalashvasaniya I would Like to Work on this issue

**Comment by Snigdha2712** [comment]
I would likw to work on this project. Please assign it to me.

**Comment by yash8917** [comment]
I have read the issue, and understand it nicely, I would like to work in it please assign me this issue, I have done my work within a couple of days.
