### ISSUE TITLE
UI/UX of Event.html

### ISSUE THREAD

**Issue by BadshahYadav** [OSCode-Community/OSCodeCommunitySite#548]
### Description
Colour combination ...
It's colour combination does not look like professional..
 
### Expected Behavior
I will change the colour combo... which will looks more attractive.
 would you please assign me to this task..
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Visbhavesh** [comment]
Please assign me this task under GSSOC 23

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @BadshahYadav . Open a PR with required screenshots, we will review it soon!

**Comment by akshathar-navada** [comment]
I have raised a issue regarding this, further conversations can be continued there!
