### ISSUE TITLE
All bugs

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#554]
# 1
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/3a7e3a2f-1c2e-4a34-b3ed-d77bcb885359)
## redirects should be site url itself not index.html.
# 2
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/39f3ec92-17e0-4c7e-bad4-17d48a792bf3)
## whole section
# 3
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/8d96084f-b54b-4339-86d5-71fb259a4617)
## should be at center properly
# 4
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/725b335d-fdb6-47ea-b710-2d8bf7387c6b)

## shouldn't be overlapped

**Comment by akshathar-navada** [comment]
hey @Git21221 , please resolve these!
