### ISSUE TITLE
Buttons under Why choose us is not responsive for smartphones.

### ISSUE THREAD

**Issue by sushant010** [OSCode-Community/OSCodeCommunitySite#556]
### Description
Buttons under why choose us is not responsive for small screen/smartphones It's Coming great for Mobile with L screen but not coming perfectly with smaller screens.

### Expected Behavior
Change In Buttons structure and make it responsive

### Screenshots
![Screenshot 2023-06-01 200931](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115036214/dbfc9f6e-e3cf-4605-a318-6b61e927be1a)
![Screenshot 2023-06-01 200907](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115036214/fe8dacff-046e-4789-a1ee-f94f7f8886ff)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
For all the screens, it is working properly!
