### ISSUE TITLE
Enhancement of CSS of Chapter Page

### ISSUE THREAD

**Issue by Sarora2127** [OSCode-Community/OSCodeCommunitySite#557]
**Current Behavior**
The Page is not attractive. unordered list and ordered lists are both used.

**Desired Behavior**
I would like to have a card display with picture of each college and name under it or any other style which would look good according to page. When user click on it, it will redirect it to a new tab opening the website of that college/university.

**Screenshots / Mockups**
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119870703/1e1a384a-a5ed-4060-87e3-0fcaf6eaafe9)

---
Kindly assign this to me under GSSoC 2023. I possess all the qualities to make this a better website.

**Comment by sshiwangi** [comment]
Hey @akshathar-navada, If it's not done yet, Can i work on this issue under GSSOC'23?

**Comment by akshathar-navada** [comment]
Hey @Sarora2127 , if there is any doublt u can reach out me, or u can also comment here. 
U can check out service page. It should b attractive like that. Else u can also improve the current state of chapters page. If u have any idea of designing or regarding layout, feel free to reach out me!

Let me know whether u are intersted in this issue or not, else I will assign this to other person!
Thank you

**Comment by Sarora2127** [comment]
hello @akshathar-navada .. Sorry I got late .. I'm stuck in between college exams . I have completed it 75% according to what I thought this page to look like. May I create a pull request for this much progress and if you like it, you may merge it and some other can enhance it further?
Thank you.

**Comment by akshathar-navada** [comment]
Yeah sure, no worries! Open a PR with required screenshots, will review it soon!

**Comment by Sarora2127** [comment]
hey @akshathar-navada .. I'm encountering an error and I'm not able to give it the required time to solve it so kindly assign this issue to someone who can devote the required time. I would like to contribute to it in future if i feel my imagination about the page is better than the then chapter page. thankyou for giving me the chance.
