### ISSUE TITLE
Overlapping of text in why choose us and contact us ,working of numbers say it all

### ISSUE THREAD

**Issue by KanchandeepK** [OSCode-Community/OSCodeCommunitySite#558]
### Current Behavior
1)When checking the responsiveness, the text in the why choose us and contact us section overlaps.
2)Overlapping of text of email and call
3)The our services in the footer not working
4)Number say it all is not working when we try to click on numbers

### Desired Behavior
1)Use of media to create the responsiveness of the website
2)The our services having 3 features should point to services page with the particular heading of web development etc.
3)As one click on the numbers in the events ,institutes one should be directed to the events ,chapters respectively.
4)Reviews should be been highlighted of the students who have either participated as well the seminars attended by students and the person delivering it.

**Comment by akshathar-navada** [comment]
Just resolve the issue 1 and 2 mentioned in your current behaviour issue! @KanchandeepK
