### ISSUE TITLE
[Docs]: ADD LIGHT/DARK LOGO [RETRY]

### ISSUE THREAD

**Issue by 0xabdulkhalid** [OSCode-Community/OSCodeCommunitySite#559]
| CURRENT STATE IN DARK THEME | DESIRED STATE IN DARK THEME |
|  :-----:   | :-----:  |
| ![](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/7376931a-4946-4d26-b988-992f75a768be)| ![](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/dfa35981-37b6-4449-835f-08656b3a43a7) 

### Retry
- This Issue is about to retry to old enhancement in readme
- Old Issue: #530 

### Additional Context
- I would like to retry this issue, so that i can ensure the proper image load next time
- Please assign this issue to me under `gssoc23`

**Comment by akshathar-navada** [comment]
Open a PR @0xabdulkhalid , we will review it soon!
