### ISSUE TITLE
Contents Under Upskill Students are not properly aligned

### ISSUE THREAD

**Issue by sushant010** [OSCode-Community/OSCodeCommunitySite#562]
### Description
Content under Upskill students are nit properly aligned.

### Expected Behavior
There should be content aligned as justify not left.

### Screenshots
![Screenshot 2023-06-01 210251](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115036214/399f1082-8b0e-4cd5-8104-2d513176eab6)

Assign me Under GSSoc @23

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Yes sure, go ahead! @sushant010
