### ISSUE TITLE
Remodifying responsiveness

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#566]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/05e81b45-69a3-4080-8081-8725dc6e3c39)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/2c7587e4-fd11-4720-9dca-e4393169fa11)
## check navbar are not properly spaced
will try to make something good

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Git21221 :)
