### ISSUE TITLE
Validation field misssing from Contact Form

### ISSUE THREAD

**Issue by sushant010** [OSCode-Community/OSCodeCommunitySite#567]
### Description
Validation  missing from contact form If user directly click on send button then also it's ,ailing to OS Community mail.

### Expected Behavior
Validation required

### Screenshots
![Screenshot 2023-06-02 001302](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115036214/be74be63-8807-4f43-8362-e2ef88f32e5f)

Assign me under GSSOC 23
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Please fix this asap @sushant010
