### ISSUE TITLE
Our Sponsors and Partners Section: The logo of the middle sponsor will pop up

### ISSUE THREAD

**Issue by vaibhav-devkate** [OSCode-Community/OSCodeCommunitySite#569]
### Current Behavior

sponsors logo colored  when hovering 

### Desired Behavior

it automatically pops up and color when comes in the middle 

---

**Comment by akshathar-navada** [comment]
As of now, this is not needed. Because it looks odd, when only 1 of it will be coloured. We prefer this hovering effect itself.
If there is anything else, u would like to work on, pls go ahead @vaibhav-devkate
