### ISSUE TITLE
changing the font- color and font style 

### ISSUE THREAD

**Issue by bhaskarkumar1** [OSCode-Community/OSCodeCommunitySite#57]
Please assign me the task for 
changing the font color of  "Transforming EDUCATION with TECHNOLOGY" to white and changing font-style to something better readable code .
![Screenshot from 2023-05-20 21-38-57](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/84345649/8b767a93-473e-43fc-a427-553af52b6924)

**Comment by AMAN-BAGADIYA** [comment]
> Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.😇
i have good knowledge of colour and combinations so please assign me

**Comment by Aahad-1526** [comment]
Hi, i would like to work on this issue of changing the fonts size and color.
I would be adding different individuals colour to different social media icon with the hover effect.
I really love working on design, so assigning me this issue will really help

**Comment by akashgreninja** [comment]
@bhaskarkumar1 and @AMAN-BAGADIYA  I will assign this to you at the moment Thank you for contributing to our repository

**Comment by AMAN-BAGADIYA** [comment]
Thank you for assigning it to me! I will start working on it.

**Comment by bhaskarkumar1** [comment]
Thank you for assigning it to us @akashgreninja .

@AMAN-BAGADIYA  can we connect somewhere and do the collaboration?
like linkedin

**Comment by AMAN-BAGADIYA** [comment]
> Thank you for assigning it to us @akashgreninja .
> 
> @AMAN-BAGADIYA  can we connect somewhere and do the collaboration?
> like linkedin

Yaa sure my LinkedIn - https://www.linkedin.com/in/aman-jain-bagadiya

**Comment by bhaskarkumar1** [comment]
@akashgreninja Please check I sent you a pull request 

https://github.com/OSCode-Community/OSCodeCommunitySite/pull/125
