### ISSUE TITLE
Menu bar

### ISSUE THREAD

**Issue by anilkoduru** [OSCode-Community/OSCodeCommunitySite#573]
While I am using this website in mobile and ipad view there is a gap after the **`menu bar icon`**.

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/88759473/2605670f-00b9-418f-9ed0-0b9039179a22)

So, I would love to solve this issue under GSSoC tag.

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Visbhavesh** [comment]
please assign it to me
