### ISSUE TITLE
Rectifying Css for Chapters

### ISSUE THREAD

**Issue by I-shika** [OSCode-Community/OSCodeCommunitySite#580]
Description
The css for Chapters is not eye catching needs some correction to be done.

Screenshot:
![Screenshot (35)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/100770197/1abfe3fb-e899-4aa6-9130-0b81b2240d33)

Please assign me this under GSSOC 2023

**Comment by akshathar-navada** [comment]
Hey @I-shika , can u pls check this once again. 

![Screenshot (57)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/95130a31-b69c-4de1-9314-c06642ec2eac)

**Comment by I-shika** [comment]
yes, I recloned the repository right now but the chapter tab is same as my screenshot which I have send earlier

**Comment by akshathar-navada** [comment]
Yea, those bullet list are there, but I have already assigned this issue to others, if there is anything else u would like to work on, pls go ahead!
