### ISSUE TITLE
Dynamic Styling in Cards with Numbers

### ISSUE THREAD

**Issue by Harshu467** [OSCode-Community/OSCodeCommunitySite#581]
### Current Behavior

When Developing anything its important to keep in mind that it must be user friendly UI. In Numbers Says it all section there are cards with numbers , I think those style could be dynamic means. For particular time when web is loaded those numbers will be seen as adding up from 0 to that particular number. It is standard and user friendly UI which attracts users. Experienced this with old projects

### Screenshots / Mockups

---

**Comment by akshathar-navada** [comment]
Hey @Harshu467 , in our project too, those numbers will be counted from 0 to particular no. Please check once, and did u meant the same?

**Comment by Harshu467** [comment]
@akshathar-navada I did not meant that , I can add animation in which when user come to that section those number will be animated  from  0 to that particular number for particular amount of time , Lets say when user come to that section from 0 to 20 numbers will be shown animatedly for lets say 6 seconds of time

**Comment by akshathar-navada** [comment]
This is not required. If there is anything else, u would like to work on, pls go ahead @Harshu467
