### ISSUE TITLE
Dynamic Styling of numbers in cards

### ISSUE THREAD

**Issue by Harshu467** [OSCode-Community/OSCodeCommunitySite#582]
### Current Behavior

Currently in Numbers says it all section the cards having numbers are static and as a user it is not attractive. As a developer it is important to develop with user mind. It is not good standard method which could be updated for betterment.

### Desired Behavior
![Screenshot from 2023-06-03 16-55-57](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/89975347/ff3ea776-d806-4c94-85cb-d30922b06d79)

It could be change to dynamic styling where those numbers could be dynamic and updated when website is loaded, for a particular time it cloud see as from 0 to that particular number. It looks more user friendly and attractive to user as seen from past projects.

**Comment by akshathar-navada** [comment]
I will be closing this issue, as it was already mentioned in the previous one
