### ISSUE TITLE
Improve footer section

### ISSUE THREAD

**Issue by utkarshgupta04092003** [OSCode-Community/OSCodeCommunitySite#583]
### Description
There are some extra spaces after the footer, that is not looking good.

### Expected Behavior
There would not be any extra spaces after footer content.
### Screenshots
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/63789702/fbf6a90a-908e-495f-86e1-c85c12bdc131)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Snigdha2712** [comment]
I would like to work on this project. Please assign it to me

**Comment by utkarshgupta04092003** [comment]
@akshathar-navada I resolve this issue and created a pull request, Please check it and give your feedback.

**Comment by utkarshgupta04092003** [comment]
@akshathar-navada I resolved this issue and created a pull request, Please check it and give your feedback.
