### ISSUE TITLE
Hover effect on logo [GSSOC'23]

### ISSUE THREAD

**Issue by riyaVerma1726** [OSCode-Community/OSCodeCommunitySite#584]
### Current Behavior
The current logo is very simple and static, we can give it a dynamic look by adding a hover effect making it more realistic and attractive.

Before -
![Screenshot 2023-06-03 194942](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114503561/802f0a08-3fd9-42d2-b350-ce8539b1b98d)

After -
![Screenshot 2023-06-03 195350](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114503561/1d8daf56-72d8-4559-8ce6-513430e5fab2)

I want to work on this issue. Kindly assign me this under Gssoc'23
@HarshSharma0801

**Comment by HarshSharma0801** [comment]
@riyaVerma1726 hello, I'm also a contributor in this project please contact the project admin

**Comment by riyaVerma1726** [comment]
Oo really sorry for that.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @riyaVerma1726 and add this effect only when hovered

**Comment by riyaVerma1726** [comment]
Sure,
Thankyou @akshathar-navada
