### ISSUE TITLE
Making UI and homepage more intractive and catchy 

### ISSUE THREAD

**Issue by AMAN-BAGADIYA** [OSCode-Community/OSCodeCommunitySite#59]
<img width="750" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108401538/3155faf4-02a1-4a61-8e14-461bc13d633e">
> Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.😇
i can make it look more catchy and attractive by choosing correct font and colours

**Comment by akshathar-navada** [comment]
There is 1 existing issue #47  addressing this problem. Let's continue the discussion there. Closing this.

If you have any other questions, feel free to open this up :)
