### ISSUE TITLE
Enhancement of - CONTACT US - button on top [GSSOC'23]

### ISSUE THREAD

**Issue by riyaVerma1726** [OSCode-Community/OSCodeCommunitySite#592]
Current Behavior -
I notices that the contact us button on the top is very sober and its position is also not so apt from user's point of view. I would like to change its position, behavior and hover effect of this contact button.

Earlier 
    - Before hovering
    
![Screenshot 2023-06-04 131534](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114503561/2b49b3f3-fbd2-4a05-9eee-cf21c5823bdb)

    - After hovering
    
![Screenshot 2023-06-04 131543](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114503561/dbda9005-75b2-4e8d-909a-2710a38e834b)

    
Later 
    - Before hovering
    
![Screenshot 2023-06-04 130819](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114503561/2debabd5-7a73-4797-b7e6-b5caffbb2a56)

    - After hovering 
    
![Screenshot 2023-06-04 130856](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114503561/a3f86906-0740-42c2-886e-0ffb19022aa4)

If you like this change kindly assign me this issue under gssoc'23.
@akshathar-navada 
Thankyou

**Comment by akshathar-navada** [comment]
Yes sure , go ahead @riyaVerma1726
