### ISSUE TITLE
Image in the "WHO WE ARE" section is not fully responsive

### ISSUE THREAD

**Issue by shrutigolwalk0109** [OSCode-Community/OSCodeCommunitySite#596]
Please Assign me this issue ,I would like to work on this with the label {GSSOC}  make the image responsive.
![Screenshot 2023-06-04 164741](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132553685/4bfdb143-12c6-4796-9fc1-e1a0ff7e5937)

**Comment by akshathar-navada** [comment]
Yes sure, go ahead and open a PR with required screenshots ,we will review it soon!
