### ISSUE TITLE
linking email and contact number in contact-us section

### ISSUE THREAD

**Issue by BhumicaPG** [OSCode-Community/OSCodeCommunitySite#60]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/95531637/02ea99b7-72e6-4e5e-b8fc-00bf21ee5464)
### The email and contact in the contact-us section do not link to the email id and phone number. 
**Please assign me this issue - I want to contribute as a part of GSSoC'23.**
I have solved this issue.

**Comment by akshathar-navada** [comment]
@BhumicaPG  We will review it, and merge it soon.
Thank you!!
