### ISSUE TITLE
Improve ReadMe.md 

### ISSUE THREAD

**Issue by VSatwika** [OSCode-Community/OSCodeCommunitySite#602]
### Current State:
<img width="960" alt="badge1" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/112561024/15db3873-eece-40e6-95c9-97af5564724f">

### Desired State:
<img width="625" alt="badges" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/112561024/57fccd50-9c58-4b08-b050-651247a7deae">

 - I would like to improve the badges in ReadMe.md and some more badges.
 - Could this be assigned to me under GSSoC'23?
---

**Comment by akshathar-navada** [comment]
Yes sure, pls go ahead @VSatwika
