### ISSUE TITLE
Why choose us nav pills overflows in small devices.

### ISSUE THREAD

**Issue by Devil1205** [OSCode-Community/OSCodeCommunitySite#605]
### Description
The nav pills in why choose us section overflows from the screen in small width devices.

### Expected Behavior
It is a width issue. I would like to fix that. Kindly assign.

### Screenshots
![127 0 0 1_5502_index html](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/103431946/6c736a50-c80e-455f-b042-8f5d5f9ee04a)

### Enviroment:
 - OS: Windows
 - Browser: Chrome
 - Version: Latest
 - Device: Desktop

**Comment by akshathar-navada** [comment]
Hey @Devil1205 , I don't think this issue exist, it is only when u check it through the responsive scroll thingy, but when u choose particular , it doesn't. And when u lower the width still more, it will obviously be cut, but that much small width will not be used mostly
