### ISSUE TITLE
Hover Effect missing on Message column unlike other input fields

### ISSUE THREAD

**Issue by JAYESHBATRA** [OSCode-Community/OSCodeCommunitySite#609]
### Description
No effect is observed on hovering on the message input field. But all other input fields show a hover effect. I will add the same hover effect on the message input field also

### Screenshots
<img width="400" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/112322302/24ad7a83-e43f-43ee-8e9c-474aff00454d">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Shatakshi127** [comment]
Please assign me this. I will design and implement an intuitive and visually appealing hover effect specifically for the Message column. This effect will provide visual feedback to users, indicating interactivity and responsiveness, thus enhancing the overall user experience. The hover effect will be carefully crafted to align with the project's branding and design principles, ensuring seamless integration into the existing interface.

**Comment by akshathar-navada** [comment]
Yes sure, pls add it @JAYESHBATRA
