### ISSUE TITLE
Footer Section Not identical in home page and Chapter Page on Mobile Devices

### ISSUE THREAD

**Issue by JAYESHBATRA** [OSCode-Community/OSCodeCommunitySite#611]
### Description
Footer Section is Not identical in home page and Chapter Page on Mobile Devices. Please assign me this issue. I will fix this issue.

### Screenshots
Home Page Footer:
<img width="292" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/112322302/3cd2969b-d8fb-42e3-9384-9f508c8acb03">

Chapter Section Footer:
<img width="297" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/112322302/ba991b34-5e77-44c8-ab17-17c96b74bf52">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Please fix this @JAYESHBATRA

**Comment by swayamshreenanda20** [comment]
Hi,
I would like to work on this issue under gssoc'23,
Can you assign it to me?

**Comment by JAYESHBATRA** [comment]
I am already working on this.
