### ISSUE TITLE
Contact page form is not responding properly and showing the connection is not secure

### ISSUE THREAD

**Issue by VGandhi27** [OSCode-Community/OSCodeCommunitySite#614]
### Description
The contact page form part is not responding properly . Please assign this to me . I'll help you fix this issue

### Screenshots
contact page form
![Screenshot (48)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93124166/d4343a32-8b99-4308-bf83-d3d628381290)

After Submission

![Screenshot (47)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93124166/9dba3d2d-0185-4bc8-b660-fc372d7b87f7)

### Environment:

 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by VGandhi27** [comment]
Hello, I am Vidushi Gandhi, a proud contributor to GSSoc' 23.

I would like to work on this project, by removing this issue on the contact page.
As already mention above I genuinely like to solve this issue
If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by akshathar-navada** [comment]
Fine! No worries @VGandhi27
