### ISSUE TITLE
Contact page form part mobile response need to change

### ISSUE THREAD

**Issue by VGandhi27** [OSCode-Community/OSCodeCommunitySite#615]
### Description
The contact page form email text field size needs to change according to the mobile device

### Screenshots

Mobile Device response of Contact page form part
![Screenshot (50)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93124166/cfe6fe8c-fb24-4b90-bdb0-64dc44357149)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by VGandhi27** [comment]
Thank you so much, also as currently, my exams are going on I would be working from the next week of June is that okay??

**Comment by akshathar-navada** [comment]
No problem! @VGandhi27

**Comment by swayamshreenanda20** [comment]
Hi,
I would like to work on this issue under gssoc'23,
Can you assign it to me?
