### ISSUE TITLE
IMPROVING THE UI OF EVENTS PAGE

### ISSUE THREAD

**Issue by kharshita590** [OSCode-Community/OSCodeCommunitySite#616]
### Current Behavior
THE UI IS NOT LOOKING GOOD , I CAN MAKE IT MORE EFFECTIVE

### Screenshots / Mockups

---

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @kharshita590 . Open a PR with required screenshot, we will review it soon!

**Comment by akshathar-navada** [comment]
I have raised a issue regarding this, further conversations can be continued there!
