### ISSUE TITLE
Changing the styling of the Contact us section

### ISSUE THREAD

**Issue by Unnati2310** [OSCode-Community/OSCodeCommunitySite#623]
### Current Behavior
The contact us section seems a bit tacky, and not professional at all.
<img width="960" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101443031/3b738ae2-27cb-41a2-98cc-6895ac974196">

### Desired Behavior
I want to make one horizontal line of round buttons containing all the media platforms. the Contact Us section is taking up a larger space than required.
something of this sort in the same UI

### Screenshots / Mockups
<img width="952" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101443031/72c82837-0336-4d67-8064-3a9944b2dd38">

**Comment by akshathar-navada** [comment]
Yes  sure , go ahead @Unnati2310

**Comment by akshathar-navada** [comment]
We prefer the existing one!
