### ISSUE TITLE
[bug]: Errors and warnings on browser's console

### ISSUE THREAD

**Issue by harmeetsingh11** [OSCode-Community/OSCodeCommunitySite#627]
### Description
There are some errors and warnings on the browser's console when index page/website is loaded. We need to fix it.

### Screenshots
![Capture](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/130365071/7dae1650-7445-4364-a165-36f6424d73eb)

### Enviroment:
 - OS: Windows
 - Browser: Chrome 

### Record
- [x] I agree to follow [Code of conduct](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I am a GSSoC'23 contributor
- [x] I want to work on this issue

Please assign me this issue under GSSoC'23.
Thanks

**Comment by akshathar-navada** [comment]
Yep! please fix it @harmeetsingh11
