### ISSUE TITLE
I want to improve UI of Contact us Section

### ISSUE THREAD

**Issue by shubhanshurav** [OSCode-Community/OSCodeCommunitySite#630]
### Description
I want to improve the UI of Contact Us section. so please assign me this issue. 

### Screenshots

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/87806305/5530118f-0dc8-4ef1-8644-7ba2e10175a7)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @shubhanshurav

**Comment by shubhanshurav** [comment]
Thank you @akshathar-navada.
