### ISSUE TITLE
Add new issue labels

### ISSUE THREAD

**Issue by Abhinavcode13** [OSCode-Community/OSCodeCommunitySite#633]
### Current Behavior
To add issue labels

### Desired Behavior
Issue Forms
Issue forms can be more user-friendly than Markdown templates, especially for contributors who may not be familiar with Markdown syntax. With issue forms, contributors can simply fill out the fields and provide the requested information.

Issue forms can help standardize the information that contributors provide when creating issues. This can help to ensure that all relevant information is provided, reducing the need for follow-up questions and clarifications.

With issue forms, you can ensure that all issues are created in a consistent format, with the same fields and information requested every time. This makes it easier for maintainers to review and respond to issues quickly.

---

**Comment by Abhinavcode13** [comment]
@akashgreninja please assign me this issue

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Abhinavcode13
