### ISSUE TITLE
Fix the contact us section responsiveness 

### ISSUE THREAD

**Issue by iamparas0** [OSCode-Community/OSCodeCommunitySite#634]
I would like to fix the responsiveness of the contact us section 
![Screenshot_2023-06-07-14-34-20-48_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/45733116/3ca616c0-c788-4199-8248-1554f068762f)

Please assign the issue to me.

**Comment by akshathar-navada** [comment]
Yes sure, pls fix it @iamparas0

**Comment by swayamshreenanda20** [comment]
Hi,
I would like to work on this issue under gssoc'23,
Can you assign it to me?
