### ISSUE TITLE
Adding appealing and readable hover effect in social links

### ISSUE THREAD

**Issue by Dimple-01** [OSCode-Community/OSCodeCommunitySite#635]
Current Behavior

![current social links](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114878264/1b7248ab-3f6f-477a-92d5-c9da402300d9)

Desired Behavior

![new social link](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114878264/4e3c2364-874c-4f22-95c5-95961f604b21)

I want to work on this issue.
Please assign this work to me.

**Comment by akshathar-navada** [comment]
We prefer the existing one, if there is anything else, u would like to work on, pls go ahead
