### ISSUE TITLE
Improve the design of OSCode's blog page

### ISSUE THREAD

**Issue by smritimangal26** [OSCode-Community/OSCodeCommunitySite#637]
The page for the blogs is not attractive to read.
I would like to improve the design of this page.
Currently, the page looks like

![Screenshot (35)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/129358356/12236c91-d7f5-4c44-8777-e1a33e19e685)
 I want to improve the design and make it more readable.
**Kindly assign me this issue under GSSOC'23.**

**Comment by akshathar-navada** [comment]
Hey @smritimangal26 the blog page is created through hashnode , so we won't be able to give permission to everyone. If there is anyhting else, u would like to work on, pls go ahead!
