### ISSUE TITLE
Sponsers

### ISSUE THREAD

**Issue by Harshu467** [OSCode-Community/OSCodeCommunitySite#638]
### Current Behavior

Currently in Our Sponsors and Partners section when hover on sponsers it looks good but can be better if we add links of their official sites when click on them to get on new tab

### Desired Behavior

Add Sponsers web link and cursor to sponsers

### Screenshots / Mockups

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/89975347/88ca678a-f46f-4609-8ec8-352b74113863)

---

**Comment by akshathar-navada** [comment]
We don't want those to be linked. It is just to know that, OS-Code is partnered with those
