### ISSUE TITLE
College Chapters

### ISSUE THREAD

**Issue by Harshu467** [OSCode-Community/OSCodeCommunitySite#639]
### Description

As of now list of colleges are mentioned and it does not look good. It can be better and It could be shown to user in user friendly interferance.

### Expected Behavior

As a user , website must be user friendly and as of now it looks good but in College chapter section  it is just list and not proper design and un standard manner

### Screenshots

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/89975347/8133dd2d-ed13-4896-8c7d-19562503dafa)

**Comment by akshathar-navada** [comment]
Please improve this section @Harshu467
