### ISSUE TITLE
Add JS validation on Contact US Form

### ISSUE THREAD

**Issue by Geeta259** [OSCode-Community/OSCodeCommunitySite#643]

**Comment by akshathar-navada** [comment]
Actually the thing is, even though u validate it, it is only getting fixed in localhost and not when  host. I also checked when I merged your PR, it didn't show up! @Geeta259

**Comment by Geeta259** [comment]
@akshathar-navada  But I shown in the site after you merged my PR it's works fine . Anyway please let me know ,  If I can do anything to contribute in this site !!
