### ISSUE TITLE
Adding hovering effect on the points of 'College Chapter' section.

### ISSUE THREAD

**Issue by aasthagracy** [OSCode-Community/OSCodeCommunitySite#645]
### Current Behavior
There is no hovering effect present on the points of the 'College Chapter' section of the page to attract users.

### Desired Behavior
There can be a hovering effect on the points to make the page more responsive.

I request you to please assign this task to me.

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/108082021/61ec0c66-c0c2-4f8a-9ad6-18bc70960e87

**Comment by akshathar-navada** [comment]
Can u pls reomve the points @aasthagracy , instead of adding hovering effect!
