### ISSUE TITLE
No link to go back to home page from blog page

### ISSUE THREAD

**Issue by dwivedishrey** [OSCode-Community/OSCodeCommunitySite#646]
### Current Behavior

As no link is available on blog page to go back to main home page.

### Desired Behavior
Want to add a navbar for adding this feature
Please assign this to me.

### Screenshots / Mockups

---

**Comment by akshathar-navada** [comment]
Hey @dwivedishrey , we creating the blog page through hashnode, so we won't be able to give access to everyone. If there is anything else, u would like to work on pls, go ahead!
