### ISSUE TITLE
rectify events page css

### ISSUE THREAD

**Issue by I-shika** [OSCode-Community/OSCodeCommunitySite#647]
### Description
I want to rectify events page css 

### Expected Behavior
There is no proper css in events page.

### Screenshots

![Screenshot (39)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/100770197/1c36c29d-d74d-4e74-b81f-7582ca1f9165)
### Enviroment:
 - OS:  Windows
 - Browser: Chrome ,Edge
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Hey @I-shika , can u pls check the actual website once more, event page is fine with required CSS
