### ISSUE TITLE
Improving the 'events section'

### ISSUE THREAD

**Issue by Ashna56** [OSCode-Community/OSCodeCommunitySite#65]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/79899788/970702b3-fc56-4547-a906-243d9f33bb04)

Problems:
- The images used in the event section are stretched out.
- The cards for various events are a bit too large 

My solutions/suggestions:
- We can size down the cards and fix the image size of the various events.
- Instead of having the event cards one below the other we can make a 2*3 or 3*3 grid cards, this would look more audience appealing.
- Improve the background of the events page.

I would like to work on this issue under GSSOC'23.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead!! @Ashna56

**Comment by AnishHazra** [comment]
Hey, I know how to fix this problem could you assign work to me.

**Comment by akshathar-navada** [comment]
Yes go ahead @AnishHazra , open a PR, we will review it soon

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by akshathar-navada** [comment]
Event page enhancement is pinned in the issue section, so will be closing this isssue. If there is any improvements u guys would like to make , can discuss in the pinned issue.
Thank you!
