### ISSUE TITLE
To enchane the ui of contact form 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [OSCode-Community/OSCodeCommunitySite#651]
### Current Behavior
Currently the contact form's UI is very simple

### Desired Behavior
To make it look good with the help of HTML, CSS and JS

### Screenshots / Mockups
N/A

---

**Comment by DhairyaMajmudar** [comment]
Please assign this issue to me under GSSoC'23 I improve the UI of the contact form with the help of HTML, CSS and JS

**Comment by akshathar-navada** [comment]
Sure @DhairyaMajmudar , pls add required screenshots when opening a PR

**Comment by DhairyaMajmudar** [comment]
Thank You @akshathar-navada for assigning me this issue I will follow up the same.
