### ISSUE TITLE
Missing Telegram icon

### ISSUE THREAD

**Issue by Shreyans2004** [OSCode-Community/OSCodeCommunitySite#656]
### Description

The telegram icon can be seen in the join us section but it is not present in the footer of the front-page
### Expected Behavior

I can add the telegram icon in the footer of the front-page, along with its link.Can you assign this task to me?
### Screenshots

![WhatsApp Image 2023-06-08 at 22 47 53](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/128773151/ccc2cbca-052c-4eb3-b479-86726d5cb93d)
![WhatsApp Image 2023-06-08 at 22 48 35](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/128773151/9d44d5fb-9db2-4843-8a48-a2292dbafba1)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Already the layout of those icons are fixed , it would be good if it is streched still more!
