### ISSUE TITLE
Why choose us buttons need improvement, our accomplishments cards can be more designed, reach out can be rearranged in a better way The event page should be reorganised , its UI can be improved and box shadows can be made more consistent with the colour scheme of the website

### ISSUE THREAD

**Issue by TeeWrath** [OSCode-Community/OSCodeCommunitySite#66]
Following Issues Can be seen:
[ ] Why choose us ? : buttons need improvement in UI and functionality
[ ] Our accomplishments : the cards can be designed more to look beautiful and consistent with the theme of the website
[ ] Reach out us through : this as a whole needs improvements
[ ] The event page : UI can be improved, box shadows can be more experimented with to look fitting with the other elements of the page.

Kindly assign me this issue so I can work for the betterment of this amazing project :)

**Comment by akshathar-navada** [comment]
There are many existing issues ( #54 #65)  addressing this problem. Let's continue the discussion there. Closing this.

If you have any other questions, feel free to open this up :)
