### ISSUE TITLE
Add Box Shadow on "Why Choose us" Section

### ISSUE THREAD

**Issue by shubhanshurav** [OSCode-Community/OSCodeCommunitySite#662]
**Description**

- Hi @akshathar-navada , I want to change the UI of "why choose us" section by adding box shadow. so please assign me.

### Current Behavior

 -Before

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/87806305/8b3e6cee-c5af-426b-afd6-7979a7bcf681)

### Desired Behavior

-After

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/87806305/85037e21-ea48-457b-bceb-2e14126f6e4b)

---

**Comment by ritik2358** [comment]
Hey @shubhanshurav , I want to work on this issue and make my first contribution to open source.
So, can you please assign me this issue.

**Comment by akshathar-navada** [comment]
Hey @shubhanshurav , it looks great.  
Before opening a PR, can u pls try adding a screenshot where the color of those will b kind of purplish,instead of current blue. U comment here itself, I will choose in that which would b better. Only thing is , as in other sections we have purple, so just wanted to keep like that:)

**Comment by shubhanshurav** [comment]
Thank you @akshathar-navada for assigning me this issue. I stared work on it. I will change the color and add the screenshot here before raising PR.

**Comment by shubhanshurav** [comment]
Hey @**akshathar-navada**, I have successfully added purple color hover, so please tell me which one is better. so that we can send the PR.

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/87806305/0aa7cb5a-f2e7-4bde-9752-e68a4a2b7891)

**Comment by akshathar-navada** [comment]
Okay , actually I wanted to change the existing one to some gradient color, so changed that.
U can use that gradient color and add box shadow:)

**Comment by shubhanshurav** [comment]
## Gradient Color with box shadow:


https://github.com/OSCode-Community/OSCodeCommunitySite/assets/87806305/d401be03-e9c6-4d79-a852-be8870d1e6ec

Hey @akshathar-navada, Now I have put gradient color, now check whether it is correct or not.

**Comment by akshathar-navada** [comment]
Yep! go ahead. Pull the repo properly and then open a PR @shubhanshurav
