### ISSUE TITLE
Enhancing the view of the images in "why choose us " section

### ISSUE THREAD

**Issue by smritimangal26** [OSCode-Community/OSCodeCommunitySite#665]
### Current Behavior
Just now the images in this section are looking very dull, I would like to add some CSS styling to these images which will make them look more attractive

### Desired Behavior
I will add hovering effect and border to the images

### Screenshots / Mockups
![Screenshot (41)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/129358356/04074f33-4735-4ca8-af61-30215fa671c2)

**Kindly assign me this issue under GSSOC'23**

---

**Comment by smritimangal26** [comment]
Kindly assign me this issue under GSSOC'23

**Comment by akshathar-navada** [comment]
Sure, go ahead @smritimangal26

**Comment by smritimangal26** [comment]
Thanks for assigning
