### ISSUE TITLE
Alignment of the "who we are" section

### ISSUE THREAD

**Issue by smritimangal26** [OSCode-Community/OSCodeCommunitySite#666]
### Current Behavior
Currently, the heading is left aligned while the rest of the headings are centrally aligned

### Desired Behavior
I would like to make it centered aligned

### Screenshots / Mockups
![Screenshot (42)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/129358356/99bccd27-7988-4bfc-ad65-01b7d6283bae)

**kindly assign me this issue under GSSOC'23**

---

**Comment by smritimangal26** [comment]
please assign me this issue under gssoc'23

**Comment by akshathar-navada** [comment]
Okay! Let the WHO WE ARE? thing be in the center and the content in that & image should be of same height, like in the same layout. Try doing like this!

**Comment by smritimangal26** [comment]
Thanks for assigning, I will work on it
