### ISSUE TITLE
Creation of a New Logo

### ISSUE THREAD

**Issue by soumizde** [OSCode-Community/OSCodeCommunitySite#667]
### Current Behavior
Currently OS-CODE has a logo that (in my opinion) does not do justice to the community and the website

### Desired Behavior
I want to create a new logo as a UI/UX Designer while simultaneously creating a Design.md for the repo so that new/ future contributors can understand the guidelines as soon as they join in.

### Plan
As soon as I am assigned the issue I would be creating the Design.md folder where I would be adding the logo and why the logo was chosen to represent the brand. If everyone agrees, we can then change it into an asset and use it instead of the current logo

---

**Comment by akshathar-navada** [comment]
Okay! , go ahead. As of now, we don't have plans to change the logo, let's see. If there is better logo and if it is satisfied by the team, we will surely consider. 
By the way, thanks for coming up with this idea. Insightful!!! @soumizde

**Comment by soumizde** [comment]
Okay. Thanks. Let me start right away
