### ISSUE TITLE
Adding navbar to blog page

### ISSUE THREAD

**Issue by anushkaMohan** [OSCode-Community/OSCodeCommunitySite#668]
### Current Behavior
All the pages be it home, about,chapter,events have navbar except blogs page.This makes navigation from blog page a bit complicated.

### Desired Behavior
I want to add navbar to the blogs page just like other pages

### Screenshots / Mockups

---

**Comment by akshathar-navada** [comment]
Hey @anushkaMohan , actually we are craeting the blog page through hashnode,  so we won't be able to give access to everyone. If there is anyting else uwould like to work on, pls go ahead!
