### ISSUE TITLE
Fix About link in chapters, show 'events' link in Events and correcting Blogs position in Chapters 

### ISSUE THREAD

**Issue by ishita80** [OSCode-Community/OSCodeCommunitySite#67]
I have already fixed the above issues. Please assign me the issue so that I can make the pull request.

**Comment by akshathar-navada** [comment]
There is 1 existing issue addressing this problem. Let's continue the discussion there. Closing this.

If you have any other questions, feel free to open this up :)

**Comment by ishita80** [comment]
Sorry to disturb you. But I can't find who fixed the 'About' link in Chapters and also corrected the blogs position.
