### ISSUE TITLE
Error on clicking services button on homepage

### ISSUE THREAD

**Issue by sumitkr2000** [OSCode-Community/OSCodeCommunitySite#670]
### Description

When I click on the services button it doesn't redirects me to the services page install giving error 404. Please assign me this issue so that I can fix it. Thank you!

### Expected Behavior

On clicking the service button it should redirect the user to its respective page.

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
The Service page is under work, we will soon link it!
