### ISSUE TITLE
Rectify The CSS Color Of The Button OS Code Community Form

### ISSUE THREAD

**Issue by swarnade** [OSCode-Community/OSCodeCommunitySite#672]
Normally Color of Button is Violet ,Rather than The CSS Design Color
"Os Code Community Student Form"

![Screenshot (1040)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78968218/1ee0711c-7466-4c5c-87a3-3f76dd8f5db1)
![Screenshot (1041)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78968218/f423ddaf-5349-4d9f-bae0-47753c5a4a7a)

So I Want Rectify The Color Combination Of The Code

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Sure , go ahead @swarnade
