### ISSUE TITLE
Add arrows to work it as slideshow

### ISSUE THREAD

**Issue by I-shika** [OSCode-Community/OSCodeCommunitySite#673]
### Current Behavior
the images are being moved after a fixed interval of time.

### Desired Behavior
For Better user experience I want to add two arrows for an additional functionality of slideshow on the images in home. I want to add this additional functionality for Sponsors component and accomplishments component.

### Screenshots / Mockups

![Screenshot (43)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/100770197/29e7d93c-4fc3-4f89-845a-a59e70cee57b)

please assign this issue to me under GSSOC'23.

**Comment by akshathar-navada** [comment]
@I-shika Don't need for sponsers sections, pls add it to accomplishments section !
