### ISSUE TITLE
Want to add Color themes in the website

### ISSUE THREAD

**Issue by lakhan06** [OSCode-Community/OSCodeCommunitySite#674]
### Current Behavior
Currently there is one color theme in the website.so i want to add more.

### Desired Behavior
I want that their should be a option so that user can select color theme of the website according to his/her choice and get a better user experience .

### Screenshots / Mockups

I will add a themes option on the right side of each page and will change the color according to user choice by using JavaScript.
I will uses root elements to change the color according to user choice.
I will also stored the data of color theme that user choose and when user again come on website then he will se the color theme according to his/her choice.

**Comment by akshathar-navada** [comment]
Sure, sounds great @lakhan06 . Please add required screenshots, while opening a PR OR If u want any suggestion/ anything, u can reach us out!

**Comment by lakhan06** [comment]
> Sure, sounds great @lakhan06 . Please add required screenshots, while opening a PR OR If u want any suggestion/ anything, u can reach us out!

ok 
Thankyou for assigning
