### ISSUE TITLE
Enhancement in the hover effect on the nav bar

### ISSUE THREAD

**Issue by Aditi323** [OSCode-Community/OSCodeCommunitySite#680]
They hovering effect in the navbar is not so attractive as well the space between the nav items 
The nav items are too close 
Can you please assign me under GSSOC'23 Contributor
![Screenshot (66)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114893448/f2227634-b107-4bd1-a333-08eaff2032c6)

**Comment by akshathar-navada** [comment]
Open a PR with required screenshots, we will review it soon! @Aditi323
