### ISSUE TITLE
Transfer the website to React

### ISSUE THREAD

**Issue by Palakkgoyal** [OSCode-Community/OSCodeCommunitySite#681]
### Current Behavior
Currently, the website is made with just HTML and CSS

### Desired Behavior
I can transfer the whole code to React with maintain readability and cleanliness. It would be more efficient in its working.

### Screenshots / Mockups

---
Please assign this issue to me under GSSOC

**Comment by akshathar-navada** [comment]
Hey @Palakkgoyal , thanks for stepping up!
Actually this was done in some PR, we will get back to u ,if we are going to shift to it.
