### ISSUE TITLE
Make a project showcase page

### ISSUE THREAD

**Issue by Palakkgoyal** [OSCode-Community/OSCodeCommunitySite#682]
### Current Behavior
Currently, the project do not have any page to showcase the users projects.

### Desired Behavior
A new page where user can add their project. By this user will be able to collaborate with other and it will lead more networking and engagment.

### Screenshots / Mockups

---

**Comment by Palakkgoyal** [comment]
Please assign this issue to me under GSSOC'23

**Comment by akshathar-navada** [comment]
Hey @Palakkgoyal , can u please provide us more info about how u r going to do it? , where the page must be linked?

**Comment by Palakkgoyal** [comment]
@akshathar-navada I will create a new folder for Project showcase page. On the page the project is shown as in a card like structure. In the project card their will be an image for the project, its GitHub repo link and some intro about the project. 
The user can come to GitHub and add their project by a PR. 
I will provide them a template in which they just have to change the content. 
For example: 
```html
<div>
            <img 
                src="/assets/projectImg/[Your_image_name.png]" 
                alt="[Add alt here]">
            <p>
                [Write a short intro about your website in this p tag]
            </p>
            <div>
                <ul>
                    <li>[techStacks]</li>
                    <li>[CSS]</li>
                    <li>[React]</li>
                    <li>[Tailwind]</li>
                </ul>
            </div>            
            <button id="">
                <a href="https://github.com/[Link to the source code on GitHub]">
                    View Project
                </a>
            </button>
        </div>
/>
```

**Comment by akshathar-navada** [comment]
But we don't think, this is required for our project! If there is anything else u would like to work on, pls go ahead !
