### ISSUE TITLE
Fix the white space  in events & chapters page

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#685]
### Description

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/d11c0eed-1f5b-452a-9640-f5136b562c1d)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/005e97f6-936e-4a19-86bf-bee12359fa43)

### Expected Behavior

The white space which is currently present must be removed!

**Comment by Dimple-01** [comment]
I want to work on this issue.
Please assign this to me .

**Comment by Abhinavcode13** [comment]
please asign me this @akshathar-navada

**Comment by akshathar-navada** [comment]
> I want to work on this issue. Please assign this to me .

Yes sure, go ahead @Dimple-01

**Comment by Git21221** [comment]
@Dimple-01 any update of this issue?
