### ISSUE TITLE
Change the layout of home section in EVENTS page

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#686]
### Current Behavior

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/010f4f55-c0c1-46b0-8417-bb30029e69a5)

### Desired Behavior

Try to change the layout of this, as this is not looking so good. May be adding some design or dividing the content into half and on other side adding some image...any other ideas also can be suggested . Make it look great! 
Overall improve the UI of it!!

---

**Comment by Abhinavcode13** [comment]
I will take up this @akshathar-navada

**Comment by akshathar-navada** [comment]
> I will take up this @akshathar-navada

Yes sure, go ahead @Abhinavcode13
