### ISSUE TITLE
Add login And signup page

### ISSUE THREAD

**Issue by sumitkr2000** [OSCode-Community/OSCodeCommunitySite#691]
### Desired Behavior
I want toa dd the login and signup page to the website.

### Screenshots / Mockups

---

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @sumitkr2000

**Comment by Gauravkr1286** [comment]
@sumitkr2000 i'am interested to contribue with you for the login and signup page to the website. If you are happy to allow me!

My purpose of this report is to outline the steps required to implement user authentication and registration functionality for our EdTech website. User authentication is essential to provide personalized experiences, protect user data, and enable secure access to restricted content. By implementing these features, we aim to enhance the user experience and ensure data privacy.

 **Objectives**

- Allow users to create accounts and securely register on the EdTech website.
- Authenticate users during login to ensure access to personalized content and features.
- Safeguard user data and privacy by implementing secure authentication mechanisms.
- Enable access control for restricted content or features based on user authentication status.

**Comment by sumitkr2000** [comment]
okay cool bro np @Gauravkr1286 !

**Comment by Gauravkr1286** [comment]
@sumitkr2000 Great work buddy!
