### ISSUE TITLE
The Contact Form Of Footer Overlaps With The Phone Number Option ,When Clicked On The Button

### ISSUE THREAD

**Issue by swarnade** [OSCode-Community/OSCodeCommunitySite#694]
The Contact Form Of Footer Overlaps With The Phone Number Option ,When Clicked On The Phone Number
![Uploading Screenshot_2023-06-11-20-02-05-662_com.brave.browser.jpg…]()

**Comment by akshathar-navada** [comment]
This issue has already been assigned!
