### ISSUE TITLE
The About Us Footer Button Of Chapter Does Not Redirect To About us Section

### ISSUE THREAD

**Issue by swarnade** [OSCode-Community/OSCodeCommunitySite#697]
The About Us Footer Button Of Chapter Does Not Redirect To About us Section

It redirect To Wrong #CLASS 

![Screenshot (1046)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78968218/f3b9cf6a-a8a3-48c1-bba2-e95cfe9efe37)

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. In the chapters page About Us, Benefits, and Accomplishments footer is not taking to the respective page. Ii can fix this. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by akshathar-navada** [comment]
Hey @swarnade , please correct all the links of community section in the footer of chapters page

**Comment by swayamshreenanda20** [comment]
Hi,
I would like to work on this issue under gssoc'23,
Can you assign it to me?
