### ISSUE TITLE
navbar (large screen)

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#698]
# For Large Before
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/9be86afe-3124-49ed-9f0a-f39a6eb85534)
# For Large After
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/e225cd1e-c78e-47a0-88fa-4572274ec012)

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I can make the navbar large. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by swayamshreenanda20** [comment]
Hi,
I would like to work on this issue under gssoc'23,
Can you assign it to me?
