### ISSUE TITLE
✨ Make a NEWSLETTER section/page

### ISSUE THREAD

**Issue by peb-peb** [OSCode-Community/OSCodeCommunitySite#7]
Discussions regarding the issues can be put down 👇

**Comment by Anushka20365** [comment]
Hello ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop |

Can you please assign this issue to me.

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by akshathar-navada** [comment]
> Hello , I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.
> 
> Skills HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop |
> 
> Can you please assign this issue to me.

@Anushka20365 , as 1 issue is already assigned to you, please finish it first , we will review and merge it soon 🙂

**Comment by akshathar-navada** [comment]
> I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

Yes sure @lalitkumawat1m , go ahead!!

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by akshathar-navada** [comment]
> Please assign me this issue so that I can resolve it under GSSOC-23

Yes sure , u can go ahead! @manoranjanonline

**Comment by soorjya** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me so that i can help resolve this issue with the best of my abilities

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @soorjya

**Comment by manoranjanonline** [comment]
you assign me or not please clarify

> Yes sure, go ahead @soorjya

**Comment by akshathar-navada** [comment]
> you assign me or not please clarify
> 
> > Yes sure, go ahead @soorjya

This issue is open for all. Anybody can work on it!!

**Comment by Vyomrana02** [comment]
@akshathar-navada can u assign me this issue under GSSOC '23.

**Comment by akshathar-navada** [comment]
> @akshathar-navada can u assign me this issue under GSSOC '23.

This issue is open to all, u can go and open a PR, we will review soon!
