### ISSUE TITLE
accomplishment part uneven sizes

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#70]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/bf1d3f4d-853b-48b1-97ad-b6caeb024ef1)
all boxes needed to be same to look more better. GSSoC'23

**Comment by akshathar-navada** [comment]
Go ahead and fix the issue @Git21221 . Open a PR , we will be happy to merge the request
Thank you!

**Comment by Git21221** [comment]
I am very happy to work on this. Thanks
