### ISSUE TITLE
Adding Navbar to the Blog section

### ISSUE THREAD

**Issue by ayushsachan123** [OSCode-Community/OSCodeCommunitySite#701]
Adding Navbar in the blog section to switch again to the main page and other page.

![OScode](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97084090/e7cc6aed-d4fe-44ad-8888-33c44cda5b82)

Please assign me this Issue under GSSOC'23.

**Comment by akshathar-navada** [comment]
Hey @ayushsachan123 , thanks for stepping up!
We are creating blog page through hashnode, so we won't be able to give access to everyone. If there is anything u would like to work on, pls go ahead!
