### ISSUE TITLE
Fixing the Social Link Section In Footer From bit.html page

### ISSUE THREAD

**Issue by Rhishikesh12** [OSCode-Community/OSCodeCommunitySite#702]
### Description
In the **bit.html** page, there is a **social link section** in the footer that contains various social media icons. Currently, when a **user hovers over these icons, their color remains black**. To enhance the user experience and improve the visual aesthetics, we want to change the color of these icons to white when the user hovers over them.

### Expected Behavior
When a user hovers over the social link icons in the footer of the bit.html page, the color of the icons should transition from black to white. This change in color will provide a visually pleasing effect and make it clear to the user that they are interacting with the icons. The white color will stand out against the background, ensuring better visibility and improving the overall user experience.

### Screenshots

Before:

![Untitled video - Made with Clipchamp](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/72931748/6a967019-2cba-4620-a4dd-5aab625387b6)

After Fix:

![Untitled video - Made with Clipchamp (1)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/72931748/0be52e3b-57ae-4440-a939-53ee2c0b5b7c)

### Enviroment:
 - OS: Windows 11
 - Browser: Chrome
 - Version: 
 - Device: Desktop

**Comment by shellyverma** [comment]
Hey, I would like to Fixing the Social Link Section In Footer From and I can resolve this issue.
 I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23 .

**Comment by Rhishikesh12** [comment]
Its already resolved.

**Comment by akshathar-navada** [comment]
Hey @Rhishikesh12 , go ahead!
And also when u hover on social icons in home page, ucan observe that their size increases. Can u pls change that too

**Comment by Rhishikesh12** [comment]
> Hey @Rhishikesh12 , go ahead!
> And also when u hover on social icons in home page, ucan observe that their size increases. Can u pls change that too

Okay I'll fix it
