### ISSUE TITLE
Page Error

### ISSUE THREAD

**Issue by swarnade** [OSCode-Community/OSCodeCommunitySite#704]
The Services page is Being Missing From The Site
![Screenshot (1047)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78968218/7e6fceed-60dd-4a2c-be36-4da644aaf1e3)
I Could Temporarily Change the Button The Services Button To Chapter Button "Out Of two Button
"Get-Started "And " Chapter"
instead Of 
 "Get-Started "And " Started"

**Comment by akshathar-navada** [comment]
Hey @swarnade , actually we are working on it! We will link it soon
