### ISSUE TITLE
Want To Create a Separate Page For About Us

### ISSUE THREAD

**Issue by swarnade** [OSCode-Community/OSCodeCommunitySite#706]
Want To Create a Separate Page For About Us

**Comment by akshathar-navada** [comment]
Hey @swarnade , that is not required. If u r interested, u can create a proper contact page 😀

**Comment by swarnade** [comment]
Ya Suree I Would Like To Create. A Proper Contact Page For Suree

**Comment by swarnade** [comment]
@akshathar-navada  Can I Start Working On Contact Page ?

And If Yes,Plz Could U Plz Assigned It To Me...
