### ISSUE TITLE
Enhancement of Blog Navbar 

### ISSUE THREAD

**Issue by Ankita3503** [OSCode-Community/OSCodeCommunitySite#707]
Hi ,
I want to make an attractive navbar of the blog page to make it user attractive and more readability.

**Comment by akshathar-navada** [comment]
Hey @Ankita3503 , thanks for stepping up! Actually we are creating the blog page through hashnode, so we won't be able to give access to everyone. If there is anything else, u would like to work on, pls go ahead!
