### ISSUE TITLE
Font family issues

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#71]
in some part the font family is not proper.
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/59236303-f5be-45a0-bb98-36c9451aa1aa)
I want to contribute in this part -> GSSoC'23.

**Comment by akshathar-navada** [comment]
It has different font to make it different from the content. Thanks for stepping up ,u can contribute on other issues. 
Thank you!!
