### ISSUE TITLE
[Enhancement]: Improve Frequently Asked Questions Visibility

### ISSUE THREAD

**Issue by NarendraKoya999** [OSCode-Community/OSCodeCommunitySite#710]
### Current Behavior

> Improve the Visibility of Frequently Asked Questions Section .

- Because of, In this FAQ , Questions List Font Weight has Low Vision. Main Cause of happens  this Visibility , We have 2 Scenarios.

  **Scenario-1:**
- Background Image Effect

    **Scenario-2:**
- Font Weight Of Multiple Questions List 

 

### Desired Behavior

> Follow Above Two Scenarios, The below behaviors happen .

- If Background Image Removes and Add Plain Background Color Like Milk White. Then Font Weight does not change anything.
- If Background Image Continues and Modify Font Weight of Questions List. Then See FAQ Section looks More Attractive. 

### Screenshots / Mockups

<img width="949" alt="oscode-1" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/84512164/754d8ee4-3bea-4023-85c4-6c42e3d47633">

---

**Comment by akshathar-navada** [comment]
Hey @NarendraKoya999 , change the font weight , that would be better!

**Comment by NarendraKoya999** [comment]
Thanks for Merged and Closed My Issue and Pull requests

**Comment by NarendraKoya999** [comment]
Hi @akshathar-navada .Please add Suitable Labels to This PR. I am working Under GSSOC'23

**Comment by NarendraKoya999** [comment]
What Happened @akshathar-navada . Still, You are not Look up My Comments.
