### ISSUE TITLE
Enhance the Privacy Policy Website according to the home page

### ISSUE THREAD

**Issue by PoulavBhowmick03** [OSCode-Community/OSCodeCommunitySite#711]
### Current Behavior
Currently the privacy policy page looks out of place, with no navbar and a minimal footer, also the design of the page looks odd

### Desired Behavior
Make the website design according to the home page with some additions to it

### Screenshots / Mockups

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/133862694/2ae8a714-a1b2-423a-b3df-2c23456d2cb7)
---

**Comment by PoulavBhowmick03** [comment]
@akshathar-navada

**Comment by akshathar-navada** [comment]
Hey @PoulavBhowmick03 , the privacy page is built through standard template, so it's not required to change anything in that. If there is anything else, u would like to work on, pls go ahead!!
