### ISSUE TITLE
Want to add more feature in event section. will add some closing and opening animation. 

### ISSUE THREAD

**Issue by rani620** [OSCode-Community/OSCodeCommunitySite#713]
### Current Behavior
 Event section looks very dull it is quite simple. There is no difference in opening and closing of event 

### Desired Behavior
 I  Want to add more feature in the event section . I will add some opening and closing animation and more design on card section, and some background effect. 

### Screenshots / Mockups
![Screenshot (546)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96174308/10d6481c-6718-411e-b472-f7151f9c3d7e)

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @rani620

**Comment by rani620** [comment]
Thankyou @akshathar-navada  sir
