### ISSUE TITLE
navbar bar in chapter page

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#721]
# Before
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/3ec89157-023f-468b-be7c-3a75dd1d7c20)
# After
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/c9b69581-c0e9-4409-a932-5315afe47960)

**Comment by akshathar-navada** [comment]
Yes sure! Can u pls add that even too events page... @Git21221
