### ISSUE TITLE
Enhance the font in "Our Accomplishments" section.

### ISSUE THREAD

**Issue by shrutigolwalk0109** [OSCode-Community/OSCodeCommunitySite#723]
**Please assign me this issue . I can fix this.**
The font size of the text in the "Our Accomplishments" section must be smaller and we can also change the font style to enhance the User interface.

### Screenshots / Mockups

![Screenshot 2023-06-13 223342](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/132553685/c5a7925f-6951-403d-ae3b-d8154ed71b91)

**Comment by akshathar-navada** [comment]
Sure go ahead @shrutigolwalk0109 , please add required screenshots when opening a PR
