### ISSUE TITLE
[GSSOC23]:Improving UI of Contact Us Section

### ISSUE THREAD

**Issue by vaibhavi-d18** [OSCode-Community/OSCodeCommunitySite#729]
### Current Behavior
There is no vertical translation effect given to input field(Your Email, Name, College,etc).

### Desired Behavior
 Want to give a vertical translation effect to move the elements (Your Email , Your Name, College, etc) upward. In other words I want create a floating label effect where the label moves up when the input field is in focus or contains a value.

### Screenshots / Mockups
Here is the sample . We can see vertical translation effect for Name field where name(Vaibhavi) is written

---
![Sample](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/118369877/29d3ac16-8a1d-4037-af1a-211321f8072d)

@akshathar-navada Could you please assign this issue to me under GSSOC23

**Comment by akshathar-navada** [comment]
Sure, go ahead @vaibhavi-d18

**Comment by vaibhavi-d18** [comment]
@akshathar-navada can you please add GSSoC'23 label to this issue
