### ISSUE TITLE
Accomplishment section, Reach out to us section and Testimonial Section can be improved

### ISSUE THREAD

**Issue by TeeWrath** [OSCode-Community/OSCodeCommunitySite#73]
![acc](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/117584718/78233772-e4cf-4c00-a7ce-551fb70d0263)
In this accomplishments section: 
 1) The cards can be improved in styling to look more appealing to the eyes. 
2) The colors used in various texts can be changed to fit the scheme of the website and cards color can be altered to look more in tone with the website scheme.

![reach](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/117584718/c1150ffb-2bb5-4555-aa07-e48117c1fbcc)
The links provided in reach out section look a bit different from what usually links are made like in websites which can be changed to occupy less space with better hover effects to make it user friendly and attractive, with a few changes in the color scheme, this will be a sweet cake.

![test](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/117584718/2d020b48-474b-4ab1-860d-c86c1d8c3335)
in the testimonial section: 
1) The arrows are both in one side, if they are arranged properly, left arrow on left of the container, right one on right then it would look perfect. 
2) The container of testimonials can be made into a card like thingy with shadows and floating effects which would make it look beautiful.

Please assign me this issue  @akshathar-navada , I would love to work on it as a part of GSSOC 23 !

**Comment by Aditi323** [comment]
Can you please assign this to me as a GSSOC Contributor.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @TeeWrath. But one thing the arrows as of now is not in the same side, it is as left and right arrows, please pull the repo properly and then make required changes. Open a PR , we will be happy to merge it
