### ISSUE TITLE
Page analysis using google

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#732]
# Desktop
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/b6dd1290-a399-45b5-850a-a9e21452bad1)
# Mobile
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/b9ae31fd-4693-4cba-8b21-3bd8193638fd)

# I will try to work on it and I need some more time.

**Comment by akshathar-navada** [comment]
Yea okay, no problem!! @Git21221
