### ISSUE TITLE
Footer Services Button Does Nor Redirect To Services Page Of Home Home

### ISSUE THREAD

**Issue by swarnade** [OSCode-Community/OSCodeCommunitySite#739]
Footer Services Button Does Nor Redirect To Services Page

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78968218/55909a57-5c5f-4c72-8905-afb9035d8997)

**Comment by akshathar-navada** [comment]
It is not linked yet, so no worries!
