### ISSUE TITLE
Animation of Numbers say it all section

### ISSUE THREAD

**Issue by khushigupta123** [OSCode-Community/OSCodeCommunitySite#747]
### Current Behavior

Currently, numbers are static whenever the section is approached.

### Desired Behavior

I want to add animation to numbers such that they increase from 0 to max value whenever section comes into view for the first time.

I am a GSSOC'23 contributor, kindly assign this issue to me.
---

**Comment by akshathar-navada** [comment]
Actually this effect of counting is there when viewed first.
