### ISSUE TITLE
Dark Mode for Home Page

### ISSUE THREAD

**Issue by EmberTSeal** [OSCode-Community/OSCodeCommunitySite#754]
### Current Behavior
By default, the home page has some light and some dark sections. That is good for viewing site in light mode, but in dark mode the whites don't look so good.

### Desired Behavior
I want to add an option for dark mode, which will change the following sections (which are by default white) to dark:
- About

- Sponsors
- FAQ
- Contact Us

### Screenshots / Mockups

These sections could use a dark mode:

![Screenshot from 2023-06-15 20-22-05](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/116507582/4b03e309-2aa0-4c84-9260-6f2ff9605dab)
-----
![Screenshot from 2023-06-15 20-22-20](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/116507582/00663c41-356b-4f56-ae05-620beb0bdff7)
------
![Screenshot from 2023-06-15 20-22-32](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/116507582/7915848c-3504-4b29-a70b-cc49b9cf17b9)
-------
![Screenshot from 2023-06-15 20-22-44](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/116507582/b99300b3-f5a2-440d-b4fe-9cd49fbb91d3)

**Comment by Git21221** [comment]
> Can I work on this issue as part of GSSOC 23?

I am working on it bro.

**Comment by EmberTSeal** [comment]
Okay.
