### ISSUE TITLE
Updating The Frequently Asked Questions Section

### ISSUE THREAD

**Issue by Keyuri-19** [OSCode-Community/OSCodeCommunitySite#756]
### Current Behavior

Currently the frequently asked questions section is not having the proper visual appearance. And also have very minimal hover effect 

### Desired Behavior

I would add effective css style which will solve these issue.

### Screenshots / Mockups

---
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115471178/8dca25fc-fd05-4c24-9952-7b920799b4a5)

**Comment by Keyuri-19** [comment]
@akshathar-navada please assign these issue to me

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Keyuri-19 . Please add required screenshots before opening a PR
