### ISSUE TITLE
Broken link in navbar of Members page

### ISSUE THREAD

**Issue by kanikakaur27** [OSCode-Community/OSCodeCommunitySite#76]
@akshathar-navada Hi, I would like to fix this. Kindly allow me to work on this issue.

![Screenshot 2023-05-20 at 11 26 56 PM](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78797208/dee16297-189f-407b-a66d-931a38489cec)
<img width="1439" alt="Screenshot 2023-05-20 at 11 27 16 PM" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/78797208/18d793aa-00af-4b61-9426-ee4d56f3b4b4">

**Comment by akshathar-navada** [comment]
Hi @kanikakaur27 , actually we are creating blog page in hashnode. So, we won't be able to give you access there. If u have any specific ideas for blog page, please let us know.
Thank you! Keep going:)
