### ISSUE TITLE
TESTIMONIAL section must be deleted from the home page!

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#764]
### Description

The existing testimonial section must be deleted and this shouldn't affect other sections in the page.

### Note 
Add required screenshots, of the page when that section is deleted while opening a PR!

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Git21221** [comment]
I want to work on it.
