### ISSUE TITLE
Navbar and header

### ISSUE THREAD

**Issue by Gauravkr1286** [OSCode-Community/OSCodeCommunitySite#767]
### Description

I noticed that the time it takes to switch from one item to another in the navbar list on the Oscode website is longer than expected.
### Expected Behavior

I expect the transition between navbar items (such as switching from "About" to "Contact" and "Events") to be smooth and quick, with minimal delay.
### Additional Information

I have noticed that the delay in transitioning between navbar items occurs consistently across different browsers and operating systems. It affects both desktop and mobile devices. This delay makes the navigation feel sluggish and could potentially impact the overall user experience of the website.
### Possible Solution

One possible solution could be to review the code responsible for handling the navbar transitions and optimize it for faster rendering or utilize more efficient animation techniques. Additionally, considering any potential network-related delays or server-side processing times that may affect the navbar's responsiveness could be beneficial.
### Enviroment:
 - OS:  Windows
 - Browser: Chrome 
 - Version: 11
 - Device: Desktop

**Comment by Gauravkr1286** [comment]
Sure, Thanks

**Comment by Diya1418** [comment]
I would like to work on this issue. Please assign it to me.
