### ISSUE TITLE
I want to Change the Background of FAQ Section

### ISSUE THREAD

**Issue by shubhanshurav** [OSCode-Community/OSCodeCommunitySite#768]
### **Description**

Hey @akshathar-navada, I want to change the Background of FAQ section, so please assign me this issue under the SSOC'23.

### Current Behavior

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/87806305/bd0d6aeb-644b-4c4d-97d7-03a4bdaef7d7)

### Desired Behavior

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/87806305/552cec59-0271-41af-8e5f-7e111634e677)

---

**Comment by akshathar-navada** [comment]
Let the existing one be. If there is anything else u would like to work on,pls go ahead
