### ISSUE TITLE
Navbar is not responsive on Mobile Screen

### ISSUE THREAD

**Issue by Ahtaxam** [OSCode-Community/OSCodeCommunitySite#77]
Navbar is not shown on small screen like mobile 
below is screenshots, how it looks on mobile phone.

**Note:**: I would like to work on this issue under GSSOC'23.

![Screenshot from 2023-05-20 23-00-11](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/64573767/ec514ef8-5df8-4e45-b42a-d74056521558)

**Comment by akshathar-navada** [comment]
Yes sure, please fix the issue!! @Ahtaxam

**Comment by green-veggies** [comment]
I am interested in fixing this issue under GSSoC'23

**Comment by Ahtaxam** [comment]
@akshathar-navada Navbar is working Now properly. you can close issue. i don't know why is not working tomorrow when i was trying.

**Comment by akshathar-navada** [comment]
> @akshathar-navada Navbar is working Now properly. you can close issue. i don't know why is not working tomorrow when i was trying.

Yes, it was actually fixed. Thanks for stepping up @Ahtaxam
