### ISSUE TITLE
Improve the events page

### ISSUE THREAD

**Issue by Uma-95** [OSCode-Community/OSCodeCommunitySite#770]
### Current Behavior
The present images on the events page have irregular spacing and sizing.

### Desired Behavior
The spacing and sizing of these image boxes can be improved thereby enhancing the UI of the page.

**Comment by Uma-95** [comment]
@akshathar-navada could you please assign this issue to me under GSSOC'23.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Uma-95
