### ISSUE TITLE
Alignment of images on the "Events" Page is not proper.

### ISSUE THREAD

**Issue by himanshuy21** [OSCode-Community/OSCodeCommunitySite#778]
### Description
The Images on the Events Page are not aligned correctly I want to change that to enhance the UI. Please assign me this issue, I would like to work on it.

### Screenshots

![Screenshot 2023-06-17 172837](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93994213/44e4dc6f-2ddb-44ce-95b8-f4398cf9eee3)

![Screenshot 2023-06-17 180911](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93994213/6086faac-c7ff-42af-aca5-f3c00969a33b)

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @himanshuy21

**Comment by Diya1418** [comment]
I would like to work on this issue. Please assign it to me.
