### ISSUE TITLE
New navbar and footer

### ISSUE THREAD

**Issue by Git21221** [OSCode-Community/OSCodeCommunitySite#783]
# Before
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/065058bc-8a7d-4834-88e5-b4ef1c912751)
# After
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/bdf2126a-756f-44f4-9f00-cd6e15be9230)

## Changed parts :
1. font family of navbar texts
2.  Font color of nav text
3. background color of navbar
4. signin / signup new logo added
5. new hover color
6. new font family in footer OS-CODE text.
7. color of address changed in footer.

**Comment by akshathar-navada** [comment]
@Git21221 Go ahead and open a PR
