### ISSUE TITLE
Enhance the navbar 

### ISSUE THREAD

**Issue by dwivedishrey** [OSCode-Community/OSCodeCommunitySite#786]
### Current Behavior
The navbar present on service.html page is not sticky so i want to fix this issue by making the navbar sticky.
![Screenshot (552)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97790062/473fcc89-8f9c-466a-9b69-3184cbdc093f)

**Comment by aakashmaity** [comment]
I AM VERY EXCITED TO CONTRIBUTE ON THIS ISSUE,PLEASE MENTORS ASSIGN THIS ISSUE TO ME.
