### ISSUE TITLE
GSSoC'23: Adding Logo to Footer

### ISSUE THREAD

**Issue by ShreyaDhiman24** [OSCode-Community/OSCodeCommunitySite#791]
### Current Behavior
no logo

### Screenshots / Mockups
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/2ec77533-b37d-467b-be60-2792de51535d)

I want to work on this issue under GSSoC'23.

**Comment by akshathar-navada** [comment]
It's not required as of now. If there is anything else, u would like to work on, pls go ahead!
