### ISSUE TITLE
Service page is not responsive!!!!!!!!!

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#792]
### Description

Service page is newly added to the website and is not responsive.
Please fix this issue!

### Screenshots

<img src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/62bb031a-cee9-4f2e-9c27-d4a311fa862e" height="800" width="400">

<img src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/1920ad67-e9ff-457c-8686-60461a73a3ac" height="800" width="400">

### Note
Kindly add required screenshots while opening a PR

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Git21221** [comment]
I will work on it.

**Comment by Git21221** [comment]
@akshathar-navada I have some changes in service page and tried to make it responsive. Here are some glimpse.
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/e43d168f-6b0e-453c-9fa9-0a12b007b181)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/44f5bab6-9160-44cf-bab6-0e49eb5282df)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/539ae4c7-fff9-451c-9f28-178c66361988)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/a6b24b53-e453-4a03-9c70-d4abcdd87c94)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/f7ba9bed-c987-4d3a-b1f1-7d8da0ea6710)

**Comment by akshathar-navada** [comment]
Hey @Git21221 , responsive in the sense I meant in mobile view, just check out that. 
May be the current navbar is strechted a bit ,it is not placed properly. DOn't need to alter the navbar links and all. And the other design be as it is, the hovering effect of that ui must be fixed!

**Comment by Git21221** [comment]
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101005577/fdb5aa2b-5638-4cce-964a-82b8f21e2ea8)
Check it once @akshathar-navada

**Comment by ShreyaDhiman24** [comment]
> Hey @Git21221 , responsive in the sense I meant in mobile view, just check out that. May be the current navbar is strechted a bit ,it is not placed properly. DOn't need to alter the navbar links and all. And the other design be as it is, the hovering effect of that ui must be fixed!

I wish to raise issue regarding the responsiveness . Can I @akshathar-navada ?

**Comment by ShreyaDhiman24** [comment]
> Hey @Git21221 , responsive in the sense I meant in mobile view, just check out that. May be the current navbar is strechted a bit ,it is not placed properly. DOn't need to alter the navbar links and all. And the other design be as it is, the hovering effect of that ui must be fixed!

I wish to raise issue regarding the responsiveness . Can I @akshathar-navada ?

**Comment by akshathar-navada** [comment]
> > Hey @Git21221 , responsive in the sense I meant in mobile view, just check out that. May be the current navbar is strechted a bit ,it is not placed properly. DOn't need to alter the navbar links and all. And the other design be as it is, the hovering effect of that ui must be fixed!
> 
> I wish to raise issue regarding the responsiveness . Can I @akshathar-navada ?

Yes, go ahead @ShreyaDhiman24

**Comment by akshathar-navada** [comment]
> ![image](https://user-images.githubusercontent.com/101005577/247568627-fdb5aa2b-5638-4cce-964a-82b8f21e2ea8.png) Check it once @akshathar-navada

Is this changed only in this view or completely. If so can u pls share the complete screenshots, or may be link!
