### ISSUE TITLE
About image is not placed properly in mobile view

### ISSUE THREAD

**Issue by akshathar-navada** [OSCode-Community/OSCodeCommunitySite#793]
### Description

The current image in ABout section is not looking so good and also not responsive. Pleaase enhance this issue

### Note
Kindly add required screenshots while opening a PR

### Screenshots

<img src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/110705457/5795440d-f855-43ff-8850-f6a0753bd5ee" height="800" width="400">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by Git21221** [comment]
I will fix it

**Comment by smritimangal26** [comment]
While the image is now properly placed in the mobile view but in the laptop view the spacing and the padding which I applied during my PR are now removed
**@akshathar-navada you told me to give the padding in my PR but now it is not visible** 

![Screenshot (49)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/129358356/7752bbc5-ecb3-4063-86d3-2884e9a164b5)

Kindly allow me to fix this

**Comment by akshathar-navada** [comment]
Okay sure, pls fix it @smritimangal26 I didn't notice that! 
I will be closing this issue, has it is fixed in mobile view, u can go ahead and open a PR regarding about image in large view!
