### ISSUE TITLE
Problem in UI of  event page 

### ISSUE THREAD

**Issue by Suniti-0020** [OSCode-Community/OSCodeCommunitySite#799]
Want to change the UI  bug in event page under GSSOC 
there is random size of the boxes and it does not look good and also the background does not match the images
![Screenshot (66)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119940275/ae92fcba-9631-4e4c-851b-8e691663ce25)

**Comment by Suniti-0020** [comment]
Thank you for assigning it to me . I will try to fix it soon .

**Comment by Suniti-0020** [comment]
Please add the GSSOC tag to it . As I will be contributing under It

**Comment by akshathar-navada** [comment]
ONce the PR is merged ,will add the labels @Suniti-0020

**Comment by Suniti-0020** [comment]
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119940275/3806d925-2410-4026-bd92-eaf2b7a403e9

This is updated one please suggest changes
