### ISSUE TITLE
Updating footer section

### ISSUE THREAD

**Issue by aysal04** [OSCode-Community/OSCodeCommunitySite#80]
The styling of the footer section can be still improved to make it look more attractive by increasing the space between horizontal columns and changing the styling of icons and links over there. Please let me if I can work on it.

**Comment by akshathar-navada** [comment]
Yes sure, go ahead! @aysal04

**Comment by SasiVardhan247** [comment]
can i work on this issue @akshathar-navada already it's 3 days from issue allocation

**Comment by aysal04** [comment]
I have almost done it. Will send the pr by tonight

**Comment by akshathar-navada** [comment]
> can i work on this issue @akshathar-navada already it's 3 days from issue allocation

Yes @SasiVardhan247 , u can also work on it!!
