### ISSUE TITLE
New Contact page under GSSoC 

### ISSUE THREAD

**Issue by Sarita-021** [OSCode-Community/OSCodeCommunitySite#800]
The UI of the contact me page does not fit the features and UI of the rest of the page . do assign it to me under GSSOC

![Screenshot (67)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121181405/b63d042c-14bb-4ab2-ab11-4f7b15b702cd)

**Comment by akshathar-navada** [comment]
SUre, go ahead @Sarita-021 . Please add required screenshots while opening a PR

**Comment by Sarita-021** [comment]
Thank you for assigning

**Comment by Sarita-021** [comment]
please assign it under GSSoC 2023

**Comment by Sarita-021** [comment]
I have modified it according to me.
Suggest me changes if any
![Screenshot (68)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121181405/28c5c6ea-b76f-4f28-88cc-867e24ccafef)

**Comment by Sarita-021** [comment]
Yes sure, but if you can tell me you any demand or I can do it according to me.
Can please mark GSSoC tag to it and it's level as well.

**Comment by akshathar-navada** [comment]
May be u can try creating a proper contact us page, like the design of it can be altered too. This page will be linked to home page.
In the screenshot which u ve added , it's not uniform!
We will add thew labels, once the PR is merged!!

**Comment by Sarita-021** [comment]
If I am taking it correct you want me to design completely new page which will be linked with home page but will not be present on home page.

**Comment by akshathar-navada** [comment]
Yep!

**Comment by Sarita-021** [comment]
I have completed that part and shared the video in the discord channel with user name Sarita | Contributor | CA

**Comment by Sarita-021** [comment]
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121181405/46966cef-e39f-49c7-8e10-2013a7bc8413
