### ISSUE TITLE
Gallery Slider in home page

### ISSUE THREAD

**Issue by Shr-reny** [OSCode-Community/OSCodeCommunitySite#805]
### Current Behavior

We can add a gallery slider displaying images from community workshops etc.
---
### Desired Behavior

The slider will swiftly switch images . It will be built using html, css and js only.
---
### Screenshots / Mockups

![Screenshot (76)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/125943681/d992f77a-76b8-44b5-add7-7a6dc3d9bb85)
![Screenshot (77)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/125943681/fcba977e-3c88-42d3-a878-3d5a8292f661)

---

**Comment by Shr-reny** [comment]
We can add it in the "Our Accomplishments" section, just below it.

**Comment by Diya1418** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by akshathar-navada** [comment]
> We can add it in the "Our Accomplishments" section, just below it.

Okay, go ahead @Shr-reny

**Comment by Shr-reny** [comment]
I've added the gallery in home page, Do you want me to add anything else @akshathar-navada ?
![Screenshot (80)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/125943681/0110a5c6-5df0-4a48-9d33-e219d29fa0e4)
![Screenshot (81)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/125943681/dd585b02-26d9-4040-ae6f-75760e75cc87)

**Comment by Shr-reny** [comment]
Thanks for merging, plz add the GSSOC'23 labels too @Vaishnavi-Patil2211 !
