### ISSUE TITLE
background not looking attractive

### ISSUE THREAD

**Issue by Shreyans2004** [OSCode-Community/OSCodeCommunitySite#809]
### Current Behavior

The background of the chapter page is not looking attractive.
### Desired Behavior

I can change the background page so that it looks better .Can you assign this task to me?
### Screenshots / Mockups

![WhatsApp Image 2023-06-20 at 17 29 36](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/128773151/94f60678-79a1-46f2-bbaf-2a92da5b4590)

---

**Comment by shreya01-bit** [comment]
Hey @akshathar-navada I m interested in working on this issue!.
If u could assign it to me.
