### ISSUE TITLE
adding article layout for sample blogs

### ISSUE THREAD

**Issue by aysal04** [OSCode-Community/OSCodeCommunitySite#81]
As of now there are no blogs in the blogs section of the website. But what if we wanna add an article to it. so let us define the layout in prior. But as it is connected to an external link how shall we make changes in it. Could you please include the externaI source code here. I am willing to work on it

**Comment by akshathar-navada** [comment]
Hi @aysal04 , actually we are creating the blog in hashnode. So, we won't be able to give access to everyone. If u have any specific ideas, then feel free to reach us.
Thank you!!
