### ISSUE TITLE
[BUG] A the white space below the footer

### ISSUE THREAD

**Issue by ManishaSwain8** [OSCode-Community/OSCodeCommunitySite#814]
### Description
A black space is visible below the footer if scroll down,due to one of the tags/section  that have been added below it which is making it look weird .
If changes req. do assign it to me under GSSOC 2023.
changes will be done in no time.  : |)

### Screenshots

![Screenshot (76)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96622693/68475439-5921-4378-9d48-8cb34cfb12e9)

![Screenshot (75)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96622693/38a5a72c-0627-4597-9cc7-3140bc60a3a2)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
This issue might be occuring in some PC's, please check once. If the issue exist, pls fix it!

**Comment by ManishaSwain8** [comment]
Yup , actually you can see this issue when you click on  the deployed link i.e. given in the Github repo, locally there is no such issue. 👍 You can close this issue.
@akshathar-navada

**Comment by akshathar-navada** [comment]
Oh, For me, in the actual link also, there is no white space
