### ISSUE TITLE
Alignment of "why choose us Image" is not correct

### ISSUE THREAD

**Issue by smritimangal26** [OSCode-Community/OSCodeCommunitySite#820]
### Current Behavior
Right now the image is not properly placed it is more towards the right 

### Desired Behavior
<I would like to adjust the spacing to make it equally spaced>

### Screenshots / Mockups

![Screenshot (58)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/129358356/2c4cc40b-b31a-4e9b-a55e-6d5a5d273ae8)

kindly assign me this under gssoc'23

---

**Comment by Diya1418** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by akshathar-navada** [comment]
Okay! Share the scrrenshot when opening a PR. And can u resolve those unwanted spacings betwn words of that content @smritimangal26

**Comment by smritimangal26** [comment]
thanks for assigning I will work on it
