### ISSUE TITLE
Navbar of Services is not Working

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [OSCode-Community/OSCodeCommunitySite#827]
Hello Project Admin,
There is a major issue in  `navbar` in the Services section.
## Issue Video - 
[Screencast from 21-06-23 05:06:36 PM IST.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121503426/b2fde6ee-0309-491a-be7e-0185ae40857f)

**Comment by akshathar-navada** [comment]
Yeah, pls fix it @SyedImtiyaz-1

**Comment by SyedImtiyaz-1** [comment]
Thank You for assigning @akshathar-navada I'm working on this.
Soon will raise a `PR` 👍🏻

**Comment by SyedImtiyaz-1** [comment]
Hello @akshathar-navada ,
The Navbar alignment bug is fixed.

## Video -
[Screencast from 22-06-23 02:57:31 AM IST.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121503426/101c249b-3ad2-4bb8-a412-06758780411c)

One more notice by my side - The OS-Code website is proper but when it's comes to the Services section it becomes very slow while working on this issue it's kinda headache to me because I have to refresh the website every single time whenever I save code in my VS-Code and after refresh it takes 3-4 minutes to load so I have a recommendation **Minify** the CSS and JavaScript to make the website faster & robust. 
If you want to make website faster then I can do it you. 💯 

### By the way above issue is ready to `Merge` 👍🏻
