### ISSUE TITLE
GSSoC'23: Improving "College Chapters" Heading 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [OSCode-Community/OSCodeCommunitySite#829]
### Current Behavior
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/31ce19f1-7b65-44ca-849c-af5c8f90c665)

### Desired
[Screencast from 21-06-23 06:18:49 PM IST.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/ae415f73-ce5d-4ac7-b869-8eb4743250da)

OR

[Screencast from 21-06-23 06:34:13 PM IST.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/82120cca-d88e-453f-adcc-39a35ec3ad26)

**Comment by akshathar-navada** [comment]
The 2nd one @ShreyaDhiman24
