### ISSUE TITLE
Centre align 'Join us' Section for better UI

### ISSUE THREAD

**Issue by Suhaani07** [OSCode-Community/OSCodeCommunitySite#83]
Centre Aligning all the components in the join us section as it gives a better look.
Before : 
<img width="1080" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98284331/e69d806d-777f-4111-a5c0-314bb41547be">

After :
<img width="1080" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98284331/2bff35aa-6aa7-484b-bdc3-e19a01d37c5e">

Please assign me this issue under GSSOC 2023

**Comment by akshathar-navada** [comment]
Hi @Suhaani07 , thanks for your sugesstion. As of now let the existing layout be. If u have any other ideas to enhance the project, please reach out us :)
