### ISSUE TITLE
GSSoC'23: Adding image cards instead of the bulleted institute name in chapters section.

### ISSUE THREAD

**Issue by ShreyaDhiman24** [OSCode-Community/OSCodeCommunitySite#831]
### Current Behavior
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/ea1148b8-d289-4574-94e6-b2cd72712aba)

### Desired Behavior
Adding image cards instead of the bulleted institute name in chapters section.

Example template:

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/22f359e6-9965-4d25-b155-cdf538111ee8)

**Comment by akshathar-navada** [comment]
Okay, the image must be suited to the college, like what image will u add to each college?

**Comment by ShreyaDhiman24** [comment]
> Okay, the image must be suited to the college, like what image will u will add to each college?

I am thinking to add the image which is alredy added as we move to each institute. eg. the image aside in the ss

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/8ec44919-2fd0-430e-a1ba-a35816e60116)

**Comment by akshathar-navada** [comment]
Okay, but the image for other colleges u would have to search in google as the page is not linked

**Comment by ShreyaDhiman24** [comment]
> Okay, but the image for other colleges u would have to search in google as the page is not linked

okay
