### ISSUE TITLE
"Services" page is not Responsive for many screen sizes.

### ISSUE THREAD

**Issue by himanshuy21** [OSCode-Community/OSCodeCommunitySite#837]
**Kindly Assign this issue to me. I want to work on it with the label of GSSoC.**

The whole services page is not correctly responsive and it has not proper UI. 

### Screenshots/ Video 

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93994213/f621ae0a-b978-4bb2-8843-50dfee121e6d

### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by akshathar-navada** [comment]
Yes, go ahead @himanshuy21
