### ISSUE TITLE
Enhance the UI of Home section of "EVENT" page.

### ISSUE THREAD

**Issue by himanshuy21** [OSCode-Community/OSCodeCommunitySite#840]
**Please Assign me this issue with the Label [GSSoC].**
### Current Behavior
The Home section of the Event page is not more appealing. Can I try to change the background and also change the font style to enhance the User interface of that page?

### Screenshots / Mockups

![Screenshot 2023-06-21 223754](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93994213/c193dd35-2af8-4478-b60c-40c73a7c2761)

**Comment by akshathar-navada** [comment]
Sure, if there is any other layout for this page ,may be not just a few sentence ,like adding image or anything... u can also think of it!
