### ISSUE TITLE
Redirecting link of Events page in navbar in chapters is not working [GSSoC'23]

### ISSUE THREAD

**Issue by AdityaLahane-2003** [OSCode-Community/OSCodeCommunitySite#855]
### Description
Redirecting link of Events page in navbar in chapters is not working.

### Expected Behavior
The link should redirect to the events page

### Enviroment:

- OS: Mac Linux Windows
- Browser: Chrome Safari Firefox
- Version:
- Device: Desktop Mobile

**Comment by Pallavi-star2002** [comment]
I would like to work on this issue. Please assign it to me.
