### ISSUE TITLE
Adding animation to the background of EVENT section. [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [OSCode-Community/OSCodeCommunitySite#87]
The background image is being repeated and it does not match to the websites color code.

I would like to add some animation to the background keeping the color code in mind in EVENT section.
Do assign to me if possible ,under GSSOC 2023.

**Comment by akshathar-navada** [comment]
Yes sure!! @ManishaSwain8

**Comment by Saurabhrajput1234** [comment]
Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
I will try to make it as different as possible and exciting also.
Please assign it to me. Thank you in advance.
