### ISSUE TITLE
Navbar and Starting landing page needs to be Attractive

### ISSUE THREAD

**Issue by amanjaiman1** [OSCode-Community/OSCodeCommunitySite#88]
Hey man,
I just checkout the complete website and what i think we should make the header i.e. the 'Navbar' and the start of the landing page should be more attractive. Assign me, I will do what I have expertise in.

**Comment by akshathar-navada** [comment]
Yes sure, thanks for stepping up ,yea try to enhance it and open a PR, we would be happy to merge it @amanjaiman1

**Comment by amanjaiman1** [comment]
Assign me bro !

**Comment by amanjaiman1** [comment]
> Yes sure, thanks for stepping up ,yea try to enhance it and open a PR, we would be happy to merge it @amanjaiman1

bro you are not on discord server , why?
and please check my pull request , i have done my work.

**Comment by akshathar-navada** [comment]
> > Yes sure, thanks for stepping up ,yea try to enhance it and open a PR, we would be happy to merge it @amanjaiman1
> 
> bro you are not on discord server , why? and please check my pull request , i have done my work.

Hey , we are there in the discord
