### ISSUE TITLE
Needs documentation (Readme file)[GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [OSCode-Community/OSCodeCommunitySite#89]
I have noticed there some basic steps missing in documentation that would be use full to the beginners and there are not much of the info about the website.
Would like to add some detailed documentation.
Assign to me if possible , under GSOCC 2023 !

**Comment by akshathar-navada** [comment]
Yes sure, thanks for stepping up ,yea try to enhance it and open a PR, we would be happy to merge it @ManishaSwain8
