### ISSUE TITLE
In the Chapters page, the navbar linking to Contact  Events and About us is not working

### ISSUE THREAD

**Issue by PoulavBhowmick03** [OSCode-Community/OSCodeCommunitySite#892]
### Description

In the Chapters page, the navbar linking to Contact  Events and About us is not working

### Expected Behavior

The navbar should be able to open the different pages

### Enviroment:

- OS:  Windows
- Browser: Chrome 
- Version: Latest
- Device: Desktop

**Comment by HumbleFool830** [comment]
@PoulavBhowmick03 I'm also coming here to contribute on this issue but you are already created this issue , go ahead I find another issue .

There are so many things need to change in this repo.
