### ISSUE TITLE
On hovering over the logo, it goes outside of the screen

### ISSUE THREAD

**Issue by PoulavBhowmick03** [OSCode-Community/OSCodeCommunitySite#896]
### Description

In the services page, on hovering over the logo, the logo goes outside of the screen
### Screenshots

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/133862694/93eb1bb3-d5d9-4175-8d02-aa435545f511)

### Enviroment:

- OS:  Windows
- Browser: Chrome -
-  Version: Latest
- Device: Desktop

**Comment by lalitkumawat1m** [comment]
can i work on this issue

**Comment by PoulavBhowmick03** [comment]
> can i work on this issue

Hey man, you can create an issue by looking through the project and finding something. When someone is creating an issue, it gets assigned to them to work on it. In this way by just commenting , it would be difficult for you to get assigned. Hope you understand how to get assigned and work in GSSoC. Keep contributing <3
