### ISSUE TITLE
Navbar 'Chapter' as active when on chapter link issue fix

### ISSUE THREAD

**Issue by Suhaani07** [OSCode-Community/OSCodeCommunitySite#91]
<img width="1080" alt="image" src="https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98284331/f0dd556a-ccee-40e4-902c-7e4379b22718">

About item is being active even when on chapter page.
Please assign me this issue to fix this under GSSOC 2023

**Comment by akshathar-navada** [comment]
Yes go ahead, thanks for stepping up ,yea try to fix it and open a PR, we would be happy to merge it @Suhaani07

**Comment by Suhaani07** [comment]
Have made the pull request which fixes the issue. Thank You

**Comment by akshathar-navada** [comment]
@Suhaani07 I didn't want that box effect on hovering colleges, so I had close that. 
Can u please change this and open a PR, we would be happy to merge it;)

**Comment by Suhaani07** [comment]
@akshathar-navada have made the pull request. The branch is up to date with the latest commits. There are no conflicts with the main branch. Please tell if any changes or issues are faced

**Comment by akshathar-navada** [comment]
Yes sure, we will review and merge it soon!
