### ISSUE TITLE
fix all the issues related to navigation bar

### ISSUE THREAD

**Issue by Sarita-021** [OSCode-Community/OSCodeCommunitySite#914]
### Description

Navigation bar at different parts like chapter, event is different. It must be same at everywhere.
Also navigation links are not upto date (for ex :  Contact Page link is not updated to other pages, etc)
Responsiveness and many more

### Screenshots
![Screenshot (81)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121181405/f68cbdff-4bf0-4294-9432-430d0c3cad87)
![Screenshot (82)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/121181405/ff8984be-1a53-4a3d-9cab-124d182db670)

**Comment by Shubham1450** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23.
