### ISSUE TITLE
"GET STARTED" Button Hover Effect Border Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [OSCode-Community/OSCodeCommunitySite#915]
### Current Behavior
The current design of the button is nice but it can be improved by working on the hover effect of the button especially the border styling. By working on the styling of the border, I can make it look even better.

### Desired Behavior
Minimal and attractive hover effect of button

### Screenshots / Mockups
Current Design
![oscode (4)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115794049/5e7d28b3-5047-4a62-8712-35ede18b47cb)

Expected Updated Design
![oscode (3)](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/115794049/f0f3d71d-7485-4f92-857f-ff730041c89d)

**Comment by YashPandey7** [comment]
Please assign me this issue.

**Comment by iamRabia-N** [comment]
@Divesh2003
