### ISSUE TITLE
Update Contact Us Section GSSoC'23

### ISSUE THREAD

**Issue by AdityaLahane-2003** [OSCode-Community/OSCodeCommunitySite#92]
- Can update the Contact Us Section - It should be more attractive!
- Please assign this issue to me, I would like to contribute as a part of GSSoC'23.

**Comment by akshathar-navada** [comment]
Yes sure,  try to enhance it and open a PR, we would be happy to merge it .
Thank you! @AdityaLahane-2003

**Comment by AdityaLahane-2003** [comment]
Thank you for assigning me this issue 
@akshathar-navada
