### ISSUE TITLE
NAV BAR ITEMS GOING OUT OF THE PAGE NOT RESPONSIVE AT ALL

### ISSUE THREAD

**Issue by abansal15** [OSCode-Community/OSCodeCommunitySite#928]
### Description

on reducing the size of screen nav bar items are going out of the page

### Expected Behavior

on reducing the size hamburger should come

### Screenshots

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/120590200/b8ed35b7-dfd2-4bc8-b0b7-5404e32afed6)

### Enviroment:

- OS: Mac Linux Windows
- Browser: Chrome Safari Firefox
- Version:
- Device: Desktop Mobile

**Comment by abansal15** [comment]
hello i would like to work on this issue could you please assign it to me

**Comment by Kajal2468** [comment]
I would like to work on this issue in under GSSoc'23 please assign this issue.

Thank You!

**Comment by abansal15** [comment]
hello @Kajal2468 I am also a gssoc contributor and raised this issue first so kindly search for another issue not interfere in someone else issue....
thanks..
