### ISSUE TITLE
College Chapter hover effects

### ISSUE THREAD

**Issue by Suhaani07** [OSCode-Community/OSCodeCommunitySite#93]
We can add hover (1.5 px purple glow) effect on the college chapter names.
Please assign me this issue under GSSOC 20203

**Comment by akshathar-navada** [comment]
Yes sure,  try to enhance it and open a PR, we would be happy to merge it.
Thank you! @Suhaani07

**Comment by Suhaani07** [comment]
Have  made the pull request. Please check it out. Thank You
