### ISSUE TITLE
to get back to home page there is NO option

### ISSUE THREAD

**Issue by Sushilverma002** [OSCode-Community/OSCodeCommunitySite#940]
### Current Behavior

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114687502/ca22d304-cb4b-4a61-bdf8-bcd57067d438

### Desired Behavior

i would like add the link so that we get back to home page
### Screenshots / Mockups

---

**Comment by addymistrel** [comment]
Can you assign this issue to me?

**Comment by Sushilverma002** [comment]
hey @Vaishnavi-Patil2211 this can't be solved from my side as there is direct link of the website so i could not get the source and i have checked no source code is present for blog section.
here i attached a ss please refer this . Sry my side i can't resolve until i get source code.
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114687502/8cb45cc8-07b2-453e-b84e-321eab5ac3f8)

**Comment by Sushilverma002** [comment]
@Vaishnavi-Patil2211
