### ISSUE TITLE
Overlapping navbar + Invisible Text + inappropriate background size

### ISSUE THREAD

**Issue by akanksha984** [OSCode-Community/OSCodeCommunitySite#956]
### Description

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/07e05199-7b11-4958-8eac-f8d23445d177)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/93f2f9ea-8049-41e0-bea2-0107c795f1ef)
![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/400aa924-440c-4273-ab49-da96d522deec)

### Expected Behavior

I would like to fix these bugs.
Please assign it to me under gssoc'23

### Show us the trouble with screenshots

-

### Enter the version of your web browser

all browsers afftected.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by KHADIJA-09** [comment]
Please, please assign me this task.

**Comment by akanksha984** [comment]
@Vaishnavi-Patil2211 Please assign this to me

**Comment by KHADIJA-09** [comment]
Thank you so much. I will do my best to.


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
