### ISSUE TITLE
In events section, logo text or button size reduced

### ISSUE THREAD

**Issue by Anshkaran7** [OSCode-Community/OSCodeCommunitySite#96]
If we reduce the size of the "OS CODE" text and the "Contact Us" button, it will look quite good. Please assign me this issue under GSSOC 2023.
![Screenshot 2023-05-21 011225](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/106963118/d9cf8436-d559-4585-a095-5a08f0969d57)

**Comment by akshathar-navada** [comment]
Yes sure, go ahead @Anshkaran7

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by syedawanya18** [comment]
sure, ill start working on it
