### ISSUE TITLE
Duplicate bullets

### ISSUE THREAD

**Issue by akanksha984** [OSCode-Community/OSCodeCommunitySite#963]
### Description

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/926ac66a-ba6d-4601-8b72-7a222c5ba883)

### Expected Behavior

Remove the bulllet points that is duplicate.

### Show us the trouble with screenshots

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/97845909/b9f150fa-9ce3-4b77-8e62-251429f1a258)

### Enter the version of your web browser

all

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
I have completed the previous issues, Please assign this to me @Vaishnavi-Patil2211

**Comment by akanksha984** [comment]
@Vaishnavi-Patil2211 This has been fixed already as of now should I close this ?

**Comment by Vaishnavi-Patil2211** [comment]
Yes
