### ISSUE TITLE
Improving Contact Us btn

### ISSUE THREAD

**Issue by Aryan123-rgb** [OSCode-Community/OSCodeCommunitySite#97]
On clicking the contact us btn it should take you to the contact us section on home page . But on clicking it it scrolling to the footer section .Please assign it to me under gssoc-23 . 

Thank you :)

**Comment by Saurabhrajput1234** [comment]
yes ,Contact Us btn not working properly .
Hello, I'm a contributor to GSSOC'23 .
I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
I will try to make it as different as possible and exciting also.
Please assign it to me. Thank you in advance.😇

**Comment by akshathar-navada** [comment]
We didn't want to direct every time to the home page contact section, so linked to footer section in chapter and event page as there is contact info there too.
Thank you!
