### ISSUE TITLE
[Feat]:  Add Github icon and navigation in the footer for all pages

### ISSUE THREAD

**Issue by PoulavBhowmick03** [OSCode-Community/OSCodeCommunitySite#976]
### What feature?

While looking for issues and coming to the github repo, I realised that there is not github icon or link available in the footer of any page. I would like to add this so that user doesn't need to separately visit github and look out for the repository

### Show us the magic with screenshots

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/133862694/0f87469a-3b94-460e-96ec-d74d6c66a558)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PoulavBhowmick03** [comment]
@Vaishnavi-Patil2211 Please assign this to me

**Comment by apoorvsharmaaa** [comment]
I had solved this  issue
 yesterday

**Comment by PoulavBhowmick03** [comment]
@Vaishnavi-Patil2211 please assign this
