### ISSUE TITLE
[Feat]: Enhancing the UI 

### ISSUE THREAD

**Issue by Saloni020** [OSCode-Community/OSCodeCommunitySite#984]
### What feature?

To improve the UI of the chapters page by making the search button more prominent and improve how the listing of colleges is done.
@Divesh2003 @Vaishnavi-Patil2211 @akshathar-navada @akashgreninja Please assign me this issue under GSSoC'23

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by BANGBANG1999** [comment]
@Saloni020 are you working on it?
