### ISSUE TITLE
[Feat]: Removing overlap of navbar from the login and signup form.

### ISSUE THREAD

**Issue by Saloni020** [OSCode-Community/OSCodeCommunitySite#985]
### What feature?

On the login page and signup page the navbar covers the forms , I'd like to improve this .
Please assign me this issue @Divesh2003 @Vaishnavi-Patil2211 @akshathar-navada @akashgreninja Please assign me this issue under GSSoC'23

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Neha626177** [comment]
I would like to work on this issue please assign me this issue.
Thank You!
