### ISSUE TITLE
[Bug]: Scrolling Action is Not Performed in Contact Us Section

### ISSUE THREAD

**Issue by NarendraKoya999** [OSCode-Community/OSCodeCommunitySite#993]
### Description

- **In Contact Us Page, Scrolling Action is not Performed.**

### Expected Behavior

- **Fix this Scrolling Action in Contact Us Page. Scrolling action Behaves smoothly likely other Related Pages**

### Show us the trouble with screenshots

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/84512164/dff6fe66-0152-4a4e-9a78-9f4403209a77

### Which browsers are affected?

Chrome

### Which OS are affected?

Windows

### Enter the version of your web browser

**Google Chrome- Version 114.0.5735.199 (Official Build) (64-bit)**

### Device?

Desktop

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by gobbledy-gook** [comment]
Please assign this issue to me.
